project:
  type: website
  title: "Data Science"
  output-dir: ../_site
  render:
    - "ds*1*"

website:
  navbar:
    # background: primary
    search: true
    
    # Right side for language selector
    right:
      - text: Langage
        icon: globe
        menu:
          - text: "English"
            href: index.html
          - text: "French"
            href: fr/index.html
  sidebar:
      style: "docked"
      search: true
      collapse-level: 2
      contents:
      - section: "Part I"
        contents:
        - section: "High-dimensional representation spaces"
          contents: "ds21*"
        - section: "Principal Component Analysis"
          contents: "ds31*"
        - section: "Linear Discriminant Analysis"
          contents: "ds51*"
        - section: "k-Means"
          contents: "ds71*"
        - section: "Expectation-Maximization"
          contents: "ds61*"
      - section: "Part II"
        contents: "dsp2*"


format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
  pdf:
    toc: true