project:
  type: website
  title: "ISS"
  output-dir: ../_site

website:
  navbar:
    # background: primary
    search: true
    left:
      - text: Course
        file: ds2.qmd
    
    # Right side for language selector
    right:
      - text: Langage
        icon: globe
        menu:
          - text: "English"
            href: index.html
          - text: "French"
            href: fr/index.html
  sidebar:
      style: "docked"
      search: true
      contents:
      - section: "High-dimensional representation spaces"
        contents: "ds2*"


format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true