---
title: "TP A : Linear Algebra"
author:
  - name: "Donnet Michel Jean Joseph"
    email: "Donnet.Michel@etu.unige.ch"
Monthyear: September 2025
TPid: A
TPname: Linear Algebra
Firstname: Donnet
Familyname: Michel Jean Joseph
Email: Michel.Donnet@etu.unige.ch
format:
  pdf:
    pdf-engine: lualatex
    latexmk-options: -shell-escape
---

# Theory questions

Use the slides and your notes to answer these questions. You do not need to write code. Provide short explanations and examples where possible.

1. What is a vector? What is a vector space? Give an example of a vector in $\mathbb{R}^2$ or $\mathbb{R}^3$.

   \hrulefill

    A vector is a mathematical object that has a length, a direction and a sense.

    A vector space is a space of vectors with linear operations such as addition between vectors and multiplication by a scalar. It can be generated by the combination of a few vectors, according to the dimension of the space. For instance, we can generate all vectors of a vector space of dimension 2 by using 2 vectors.

2. What do we mean by the “dimension” $D$ of a dataset?

   \hrulefill

    The dimension of a dataset indicates the minimum number of vectors useful to generate the entire dataset by combinations between these vectors.

3. Create two small datasets: one scalar dataset of 5 numbers, and one vector dataset of 5 vectors in $\mathbb{R}^3$.
   Compute their mean and variance. Then, write the formal mathematical definitions of mean and variance.

   \hrulefill

    The dataset are the following:
$$A = \left\{1, 2, 3, 4, 5 \right\} \in \mathbb{R}$$
$$B = \left\{
      \begin{pmatrix}
      3 & 9 & 6 \\
      8 & 4 & 5 \\
      5 & 6 & 6 \\
      0 & 8 & 5 \\
      6 & 3 & 2
      \end{pmatrix}
      \right\} \in \mathbb{R}^3$$
  - The mean is given by the formula [-@eq-mean]
$$\boldsymbol{\mu} = \frac{1}{n} \sum_{i=1}^{n} \mathbf{x}_i \ \text{for} \ \mathbf{x}_i, \boldsymbol{\mu} \in \mathbb{R}^d$$ {#eq-mean}


    So for the first dataset, we have the following computation:
$$\mu = \frac{1}{n} \sum_{i=1}^{n} A_i = \frac{1 + 2 + 3 + 4 + 5}{5} = 3 \ \in \ \mathbb{R} $$
    And for the second dataset, we have the following computation:
$$\boldsymbol{\mu} 
= \frac{1}{n} \sum_{i=1}^{n} B_i
= \frac{1}{n} \begin{pmatrix} \sum_{i=1}^{n} B_{i1} &  \sum_{i=1}^{n} B_{i2} & \sum_{i=1}^{n} B_{i3} \end{pmatrix}
= \frac{1}{5} \begin{pmatrix} 22 & 30 & 24\end{pmatrix}
= \begin{pmatrix} 4,4 & 6 & 4,8\end{pmatrix} \ \in \ \mathbb{R}^3$$
  - The variance $\boldsymbol{\sigma^2}$ is given by the formula [-@eq-var] by taking the square racin of the result
$$
\sigma_j^2 = \frac{1}{n} \sum_{i=1}^{n} (x_{ij} - \mu_j)^2 \ \text{for} \ \mathbf{x}_{i}, \boldsymbol{\sigma} \in \mathbb{R}^d
$$ {#eq-var}
    So we have for the first dataset
$$
\sigma^2 = \frac{1}{n} \sum_{i=1}^{n} (A_i - \mu)^2
= \frac{1}{5} \left((1 - 3)^2 + (2 - 3)^2 + (3 - 3)^2 + (4 - 3)^2 + (5 - 3)^2 \right)
= \frac{10}{5}
= 2
$$
    And for the second dataset
    - j = 1
$$
\sigma_1^2 
= \frac{1}{n} \sum_{i=1}^{n} (x_{i1} - \mu_1)^2
= \frac{1}{5} \left( (3 - 4.4)^2 + (8 - 4.4)^2 + (5 - 4.4)^2 + (0 - 4.4)^2 + (6 - 4.4)^2 \right)
= \frac{37.2}{5}
= 7.44
$$
    - j = 2
$$
\sigma_2^2 
= \frac{1}{n} \sum_{i=1}^{n} (x_{i2} - \mu_2)^2
= \frac{1}{5} \left( (9 - 6)^2 + (4 - 6)^2 + (6 - 6)^2 + (8 - 6)^2 + (3 - 6)^2 \right)
= \frac{1}{5} \left( 9 + 4 + 0 + 4 + 9 \right)
= \frac{26}{5}
= 5.2
$$
    -  j = 3
$$
\sigma_3^2 
= \frac{1}{n} \sum_{i=1}^{n} (x_{i3} - \mu_3)^2
= \frac{1}{5} \left( (6 - 4.8)^2 + (5 - 4.8)^2 + (6 - 4.8)^2 + (5 - 4.8)^2 + (2 - 4.8)^2 \right)
= \frac{10.8}{5}
= 2.16$$
    So
$$\boldsymbol{\sigma^2} = \begin{pmatrix} 7.44 & 5.2 & 2.16 \end{pmatrix} \ \in \ \mathbb{R}^3$$


4. Define the scalar product. Compute it for two vectors from your vector dataset above. How does the scalar product allow us to compute the projection of one vector onto another?

   \hrulefill

    The scalar product is defined for two vectors $\mathbf{x}$ and $\mathbf{y}$ like the formula [-@eq-scalar]

    $$\mathbf{x} \cdot \mathbf{y} = \sum_{i=1}^{d} x_i y_i
    = |\mathbf{x}|\, |\mathbf{y}| \cos(\theta) \ \ \ \forall \mathbf{x}, \mathbf{y} \in S^d$$ {#eq-scalar}

    with $S$ the vector space of dimension $d$.

    So for vector $\mathbf{x} = \begin{pmatrix}3 & 9 & 6 \end{pmatrix}$
    and $\mathbf{y} = \begin{pmatrix}8 & 4 & 5 \end{pmatrix}$,
    the scalar product is given by the following calculs.

    $$\mathbf{x} \cdot \mathbf{y} = \sum_{i=1}^{d} x_i y_i
    = 3 \times 8 + 9 \times 4 + 6 \times 5
    = 90 $$

5. What is a basis of a vector space?

   \hrulefill

    A basis of a vector space is a set of vectors that can generate the entire vector space by basics operations, such as addition between vectors and multiplication by scalars.

6. Explain the eigenvalue decomposition (EVD) and singular value decomposition (SVD). Why are they important in data science?

    \hrulefill

    $X \in \mathbb{R}^{n \times n}$ is a square matrix.
    The eigen vector $\mathbf{u}$ is a vector that satisfies the equality [-@eq-eigen].

    $$\left(\exists \sigma \ \text{such as} \ X\mathbf{u} = \sigma \mathbf{u} \ \text{with} \ \mathbf{u} \neq 0 \right) \ \Rightarrow \ \left( X - \sigma I \right)\mathbf{u} = 0$$ {#eq-eigen}

    So if $X$ is diagonalisable, the matrix admits an Eigen Value Decomposition, given by the formula [-@eq-evd].
    
    $$\forall i, \  X\mathbf{u}_i = \sigma_i \mathbf{u}_i \ \text{and} \ \mathbf{u}_i \neq 0
    \ \ \Rightarrow \ \ XU = U\Sigma \ \Leftrightarrow \ X = U\Sigma U^{-1}$${#eq-evd}

    Where
    - $U \in \mathbb{R}^{n \times n}$ is a matrix composed of linearly independant eigen vectors $\mathbf{u}$
    - $\Sigma \in \mathbb{R}^{n \times n}$ is a diagonal matrix with on the diagonal the values of the corresponding eigenvalues $\sigma_i$ of the eigenvectors.
    - $U^{-1}$ the inverse of $U$.

    Similarly, $\forall X \ \in \ \mathbb{R}^{n*m}$, there exists a factorization $X = U S V^{T}$ which is called the Singular Value Decomposition (SVD).

    This two notions are very important in data science because they allow us to uncorrelate data, which is very useful for data analysis and processing because it saves a lot of time and ressources.

7. Give one concrete example of the curse of dimensionality, and one example of the blessing of dimensionality.

    \hrulefill

    - Curse of dimensionality.
    A concrete example of this can be the data sparsity problem.
    We have an hypercube $[a, b]^D$ with $D$ the dimensionality of the hypercube.
    We want to create an histogram that represents an empiric estimation of the probability density function (pdf) for this hypercube.
    For that, we quantize each dimension into $b$ bins.
    Now, we hope an average of $n$ samples per bin since if the number of samples per bin is too small, we can't have a good estimation because the density can vary a lot between bins.
    This generate noise for our estimation whereas with a great number of samples per bin, the variance will decrease and the empiric estimation will be closest to the real pdf, according to the Central Limit Theorem which says that when the number of samples increase, the empiric mean is closest to the real mean. 

    - Blessing of dimensionality.
    According to the lemma of Johnson-Lindenstrauss, we can find a linear projection that maps the datas in a space of smaller dimensionality that conserves the structure of our data with a distortion factor $\epsilon \in ]0, 1[$.
    This lemma is a blessing of dimensionality because it says also that the projection depends only on the number of samples and not on the dimensionality of our data.
    So for instace, we have $10 000$ samples $\in \mathbb{R}^{3000}$ and we choose a distortion factor $\epsilon$ of $50\%$
    According to the lemma, we can project this datas with linear projection into a space of dimensionality given by the formula [-@eq-dim].
    $$d = O\left( \frac{\log_2 N}{\epsilon^2} \right)
    = O\left( \frac{\log_2 10000}{0.5^2} \right)
    = O\left( \frac{13.28}{0.25} \right)
    \approx 50$$ {#eq-dim}
    So we can reduce the dimensionality from $3000$ to only $50$ !!!
    This is an answer to the curse of dimensionality since it allows to work with big dimensionalities.

8. If you divide a $D$-dimensional space into $b$ bins per dimension, and want $k$ samples per bin, how many samples are needed in total?

    \hrulefill

    If we divide each dimension into $b$ bins, we have for $D$ dimensions a number of bins:
    $$\underbrace{b \times b \times \cdots \times b}_{D\ \text{times}}
    =b^D$$
    Now, if we want $k$ samples per bin, the total number of samples needed is:
    $$N = k \times b^D$$

9. Why does data become more sparse as $D$ grows? What happens if the number of samples stays fixed?

    \hrulefill

    We suppose that we have a fixed number of samples $N$.
    The number of samples per bin is given by:
    $$N = k \times b^D \Leftrightarrow k = \frac{N}{b^D}$$
    So the expectation to have a sample $x_i$ in a bin $b_j$ is given by:
    $$\mathbb{E}\left[P(x_i \in b_j)\right]
    = \frac{1}{N}\cdot\frac{N}{b^D}
    = \frac{1}{b^D}$$
    When $D$ increase, this expectation will approach $0$, so it means that when $D$ increase, most bins are likely to be empty since expectation to have a sample inside a bin approach $0$.

10. Compare a hypersphere of radius $r$ with its enclosing hypercube $[-r,r]^D$. As $D$ increases, what happens to their volume ratio? What does this imply for uniform sampling?

    \hrulefill

    We have the volum of the hypersphere of dimension $D$ and radius $r$ given by the formula [-@eq-sphere].
    $$\text{vol}(B^D(r)) = \frac{2 r^D \pi^{D/2}}{D \, \Gamma(D/2)}$$ {#eq-sphere}
    And the volum of the hypercube of $[-r, r]^D$ given by the formula [-@eq-cube].
    $$\text{vol}(C^D(r)) = (2r)^D$$ {#eq-cube}
    So the ratio of this two volums is given by the formula [-@eq-ratio].
    $$\frac{\text{vol}(B^D(r))}{\text{vol}(C^D(r))}
    = \frac{2 r^D \pi^{D/2}}{D \, \Gamma(D/2)} \cdot \frac{1}{(2r)^D}
    = \frac{\pi^{D/2}}{D \, \Gamma(D/2)\cdot 2^{D - 1}}
    $$ {#eq-ratio}
    When $D$ increase, we have that:
    $$\lim_{D \to \infty}\frac{\text{vol}(B^D(r))}{\text{vol}(C^D(r))}
    = \lim_{D \to \infty} \frac{\pi^{D/2}}{D \, \Gamma(D/2)\cdot 2^{D - 1}} = 0$$
    So when the dimension is big, the volum of the hypersphere is neglectible compared to the volum of the hypercube.
    So this implies for uniform sampling that if we make uniform sampling in hypercube, there are no samples in hypersphere because the ratio of volums is $0$.
    It means that all samples will be concentrated, like the volum, in the corners of the hypercube and not in the hypersphere.

11. In high dimensions, what is the typical angle between two random vectors? How does this angle change as $D$ increases?

    \hrulefill

    We create two vectors by creating 4 random variables independant and identically distribued (iid) $W, X, Y, Z$ in the space $\Omega \subset \mathbb{R}^D$ of dimension $D$.
    We define $u = X - Y$, and $v = Z - W$ two vectors.
    Now, we are interested to compute the $\mathbb{E}(cos(\theta))$ between the two vectors.
    We have:
    $$\mathbb{E} \left[ \cos\left(\theta\right) \right]
    = \mathbb{E} \left[ \frac{ \langle u,\; v \rangle }{ \|u\| \cdot \|v\| } \right]
    = \mathbb{E} \left[ \frac{ \langle X - Y,\; Z - W \rangle }{ \|X - Y\| \cdot \|Z - W\| } \right]$$
    As $W, X, Y, Z$ are iid, $X - Y$ and $Z - W$ are also iid and centered.
    So $\mathbb{E}[X - Y] = \mathbb{E}[Z - W] = 0$ so we have $\mathbb{E}\left[\langle X - Y,\; Z - W \rangle\right] = 0$
    
    As the denominator is a normalizer, $\mathbb{E}[\theta] = 0 \Rightarrow \theta = \frac{\pi}{2}$

    So the two vectors seems to be quasi-orthogonal.

    So when $D$ increase, the vectors seems to be orthogonal.


12. What is meant by a “concentration phenomenon”? Give one example where it is useful, and one where it is problematic.

    \hrulefill

    A concentration phenomenon is that in a high dimensional space, random variables tend to be concentrated around their mean value, with a variance that tend to be null, so with a probability of significant deviation that becomes small when $D$ increase.

13. State one concentration inequality (e.g., Markov, Chebyshev, Hoeffding). Explain briefly what it tells us.

    \hrulefill

    The Chebyshev inequality say that for a random variable $X$, a finite variance $\sigma^2$ and a finite expected value $\mu$, it exists $\epsilon > 0$ such that:
    $$\mathbb{P}(|X - \mu| > \epsilon) \leq \frac{\sigma^2}{\epsilon^2}$$
    That means that when the variance decrease, the values are significant more close to the mean.
    It allows to estimate the contentration of data when we only know the variance of the datas, so it is very useful in case we analyse data without a knowledge of the distribution of the datas.


14. What is a PAC (Probably Approximately Correct) analysis in machine learning?

    \hrulefill

    A PAC analysis in machine learning is when we try to train a model to learn a function, and we want a model approximately correct, that means with a small deviation or a small error.
    It means that we think that the function used to train the model is closest to the best function, based on a data sample.
    And we speak about probably because we want a strong probability to have a small error according to the data sample.




# Matrix

1. Find a quadratic polynomial, say $f(x) = ax^2 + bx + c$, such that
   $$
   f(1) = -5, \quad f(2) = 1, \quad f(3) = 11.
   $$

   \hrulefill

    To solve the equation, we use the pivot method (Gaussian elimination with pivoting):
    $$
    \begin{aligned}
        \begin{cases}
        a\times 1^2 + b \times 1 + c = -5\\
        a\times 2^2 + b \times 2 + c = 1 \\
        a\times 3^2 + b \times 3 + c = 11
        \end{cases}
        &\;\;\Longrightarrow\;\;
        \underbrace{\begin{pmatrix}
        1 & 1 & 1 & \vline & -5\\
        4 & 2 & 1 & \vline & 1 \\
        9 & 3 & 1 & \vline & 11
        \end{pmatrix}}_{\;[\begin{bmatrix}a & b & c\end{bmatrix}\mid \text{values}]}\\
        &\;\;\Longrightarrow\;\;
        \begin{pmatrix}
        1 & 1 & 1 & \vline & -5\\
        0 & -2 & -3 & \vline & 21 \\
        0 & -6 & -8 & \vline & 56
        \end{pmatrix} \\
        &\;\;\Longrightarrow\;\;
        \begin{pmatrix}
        1 & 1 & 1 & \vline & -5\\
        0 & -2 & -3 & \vline & 21 \\
        0 & 0 & 1 & \vline & -7
        \end{pmatrix} \\
        &\;\;\Longrightarrow\;\;
        \begin{pmatrix}
        1 & 1 & 0 & \vline & 2\\
        0 & -2 & 0 & \vline & 0 \\
        0 & 0 & 1 & \vline & -7
        \end{pmatrix} \\
        &\;\;\Longrightarrow\;\;
        \begin{pmatrix}
        1 & 0 & 0 & \vline & 2\\
        0 & 1 & 0 & \vline & 0 \\
        0 & 0 & 1 & \vline & -7
        \end{pmatrix} \\
        &\;\;\Longrightarrow\;\;
        \begin{cases}
        a = 2\\
        b =  0 \\
        c = -7
        \end{cases} \\
    \end{aligned}
    $$

2. Let $a$, $b$ be some fixed parameters. Solve the system of linear equations
   $$
   \begin{cases}
   x + ay = 2 \\
   bx + 2y = 3
   \end{cases}
   $$

   \hrulefill

    $$
    \begin{aligned}
    \begin{cases}
    x + ay = 2 \\
    bx + 2y = 3
    \end{cases}
    &\;\;\Longrightarrow\;\;
    \begin{cases}
    x = 2 - ay \\
    b(2 - ay) + 2y = 3
    \end{cases} \\[1em]
    &\;\;\Longrightarrow\;\;
    \begin{cases}
    x = 2 - ay \\
    y(2 - ab) = 3 - 2b
    \end{cases} \\[1em]
    &\;\;\Longrightarrow\;\;
    \begin{cases}
    x = 2 - a\dfrac{3 - 2b}{2 - ab} \\
    y = \dfrac{3 - 2b}{2 - ab}
    \end{cases}
    \end{aligned}
    $$

    <!-- $$
   \begin{cases}
   x + ay = 2 \\
   bx + 2y = 3
   \end{cases}
   = \begin{cases}
   x = 2 - ay \\
   b(2 - ay) + 2y = 3
   \end{cases}
   = \begin{cases}
   x = 2 - ay \\
   y(2 - ba) = 3 - 2b
   \end{cases}
   = \begin{cases}
   x = 2 - a\frac{3 - 2b}{2 - ba} \\
   y = \frac{3 - 2b}{2 - ba}
   \end{cases}
   = \begin{cases}
   x = 2 - \frac{a(3 - 2b)}{2 - ba} \\
   y = \frac{3 - 2b}{2 - ba}
   \end{cases}
   $$ -->

3. Find the inverse of the following matrix, if it exists:
   $$
   A = \begin{pmatrix}
   1 & 2 & 3 \\
   0 & 1 & 4 \\
   5 & 6 & 0
   \end{pmatrix}
   $$

   \hrulefill

    The inverse of the matrix is given, according to pivot method:
    $$
    \begin{aligned}
        \underbrace{\begin{pmatrix}
        1 & 2 & 3 & \vline & 1 & 0 & 0\\
        0 & 1 & 4 & \vline & 0 & 1 & 0\\
        5 & 6 & 0 & \vline & 0 & 0 & 1
        \end{pmatrix}}_{\;[A\mid I]} 
        &\;\;\Longrightarrow\;\;
        \begin{pmatrix}
        1 & 2 & 3 & \vline & 1 & 0 & 0\\
        0 & 1 & 4 & \vline & 0 & 1 & 0\\
        0 & -4 & -15 & \vline & -5 & 0 & 1
        \end{pmatrix} \\
        &\;\;\Longrightarrow\;\;
        \begin{pmatrix}
        1 & 0 & -5 & \vline & 1 & -2 & 0\\
        0 & 1 & 4  & \vline & 0 & 1  & 0\\
        0 & 0 & 1  & \vline & -5 & 4 & 1
        \end{pmatrix} \\
        &\;\;\Longrightarrow\;\;
        \begin{pmatrix}
        1 & 0 & 0 & \vline & -24 & 18 & 5\\
        0 & 1 & 0 & \vline & 20  & -15 & -4\\
        0 & 0 & 1 & \vline & -5  & 4   & 1
        \end{pmatrix}
    \end{aligned}
    $$
   Hence
   $$
   A^{-1} \;=\;
   \begin{pmatrix}
   -24 & 18 & 5\\
   20  & -15 & -4\\
   -5  & 4 & 1
   \end{pmatrix}.
   $$

   <!-- $$
   \begin{pmatrix}
   1 & 2 & 3 & 1 & 0 & 0\\
   0 & 1 & 4 & 0 & 1 & 0\\
   5 & 6 & 0 & 0 & 0 & 1
   \end{pmatrix}
   = \begin{pmatrix}
   1 & 2 & 3 & 1 & 0 & 0\\
   0 & 1 & 4 & 0 & 1 & 0\\
   0 & -4 & -15 & -5 & 0 & 1
   \end{pmatrix}
   = \begin{pmatrix}
   1 & 0 & -5 & 1 & -2 & 0\\
   0 & 1 & 4 & 0 & 1 & 0\\
   0 & 0 & 1 & -5 & 4 & 1
   \end{pmatrix}
   = \begin{pmatrix}
   1 & 0 & 0 & -24 & 18 & 5\\
   0 & 1 & 0 & 20 & -15 & -4\\
   0 & 0 & 1 & -5 & 4 & 1
   \end{pmatrix}
   $$ -->

4. Solve the following matrix equation for \( X \):
   $$
   AX = B, \quad \text{where} \quad A = \begin{pmatrix} 1 & 3 \\ 2 & 5 \end{pmatrix}, \quad B = \begin{pmatrix} 7 & 8 \\ 9 & 10 \end{pmatrix}.
   $$

   \hrulefill

    First, as $det(A) = 1 \times 5 - 2 \times 3 \neq 0$, $A$ is invertible.
    So we want to find $A^{-1}$ with the same method than the precedent question:
    $$
    \begin{aligned}
        \underbrace{\begin{pmatrix}
        1 & 3 & \vline & 1 & 0 \\
        2 & 5 & \vline & 0 & 1
        \end{pmatrix}}_{\ [A|I]}
        &\;\;\Longrightarrow\;\;
        \begin{pmatrix}
        1 & 3 & \vline & 1 & 0 \\
        0 & -1 & \vline & -2 & 1
        \end{pmatrix} \\
        &\;\;\Longrightarrow\;\;
        \begin{pmatrix}
        1 & 0 & \vline & -5 & 3 \\
        0 & 1 & \vline & 2 & -1
        \end{pmatrix}
    \end{aligned}
    $$
    So $A^{-1} = \begin{pmatrix} -5 & 3 \\ 2 & -1 \end{pmatrix}$.
    Now, we can solve the equation:
    $$
    \begin{aligned}
        AX = B
        &\;\;\Longrightarrow\;\;
        X = A^{-1}B \\
        &\;\;\Longrightarrow\;\;
        \begin{pmatrix}
        -5 & 3 \\
        2 & -1
        \end{pmatrix} \times
        \begin{pmatrix}
        7 & 8 \\
        9 & 10
        \end{pmatrix} \\
        &\;\;\Longrightarrow\;\;
        \begin{pmatrix}
        3 \times 9 - 5\times 7 &  3 \times 10 - 5 \times 8 \\
        2 \times 7 - 1 \times 9 & 2 \times 8 - 1 \times 10
        \end{pmatrix} \\
        &\;\;\Longrightarrow\;\;
        \begin{pmatrix}
        -8 & -10 \\
        5 & 6
        \end{pmatrix}
    \end{aligned}
    $$



# The importance of the mathematical concept behind a code

1. Download, open and run several times the PYTHON file "some\_script.py".

   Explain the function \mintinline{python}{def project_on_first(u, v)} in geometrical terms and then explain the results of this code with clear mathematical concepts (you have to talk about projections and scalar product).

   \hrulefill

    The execution of the script gives always "Result = 0.0".

    The function \mintinline{python}{def project_on_first(u, v)} is composed by a single code line:
    \begin{minted}{python}
    return np.dot(u,v) / np.dot(u,u) * u
    \end{minted}
    It correspond for the vector $u$ and $v$ to the scalar product between $u$ and $v$ divided by the scalar product between $u$ and $u$ (which give us a scalar) multiplied by $u$.
    If we write it in term of mathematic, we have:
    $\dfrac{\langle u, v \rangle}{\langle u, u \rangle} u$.
    This formula is the formula of the orthogonal projection of $v$ on $u$.
    
    In fact, in an orthogonal projection, we search a vector on $u$ (that we call $p$) such as the vector $v - p$ is perpendicular to the vector $u$. As $p$ is on $u$, we search a scalar $\lambda$ to find our vector $p$: $p = \lambda u$.

    So as the scalar product of 2 ortogonal vectors is $0$, we have:
    $$\langle v - \lambda u, u \rangle = 0 \
    \Longrightarrow \ \langle v, u \rangle - \lambda \langle u, u \rangle = 0
    \Longrightarrow \ \lambda = \frac{\langle v, u \rangle}{\langle u, u \rangle}$$
    So the orthogonal projection is given by $p = \lambda u = \frac{\langle u, v \rangle}{\langle u, u \rangle} u$, which is what our function compute.

2. Consider $u = (u_i)_{1 \le i \le 7}$ and $v = (v_i)_{1 \le i \le 7}$, two vectors of length 7. How would you clearly write the following part of the script using some mathematical notation?

    \begin{minted}{python}
    import numpy as np
    u = np.random.randn(7)
    v = np.random.randn(7)
    r = 0
    for ui, vi in zip(u, v):
        r += ui * vi
    \end{minted}

   Name the mathematics behind and rewrite the last 3 lines of code in one.

   \hrulefill

    This code is simply the computation of the scalar product.
    In mathematical notation, we can write it like this:
    $\sum_{i = 1}^{n} u_i \cdot v_i$ with $n = 7$ in our case.

    We can replace the last 3 lines of code by the numpy function np.dot that compute the scalar product.

    So the updated code is like this:
    \begin{minted}{python}
    import numpy as np
    u = np.random.randn(7)
    v = np.random.randn(7)
    np.dot(u, v)
    \end{minted}

3. Complete the code to construct a vector $v$ orthogonal to the vector $u$ and with the same norm as $u$. Comment each line of your code.

   \hrulefill

    \begin{minted}{python}
    import numpy as np
    u = np.random.randn(7)
    v = np.random.randn(7)
    # vector orthogonal to u obtained by the difference between v
    # and a projection of v on u.
    z = v - np.dot(u, v) / np.dot(u, u) * u
    # normalize vector to have a norm of 1
    z /= np.linalg.norm(z)
    # multiply vector by norm of u to have same norm than u
    z *= np.linalg.norm(u)
    # print results
    # As we work on discrete space, there is machine precision to consider.
    print(f"Check orthogonality: {np.round(np.dot(z, u))}")
    print(f"Norm of u: {np.linalg.norm(u)}")
    print(f"Norm of created vector: {np.linalg.norm(z)}")
    \end{minted}

4. Given two vectors \( u \) and \( v \) in $\mathbb{R}^n$, write Python code to compute the cosine of the angle between them. Explain the mathematical concept behind this computation, and show how you would write it in one equation.

   \hrulefill

    \begin{minted}{python}
    import numpy as np
    u = np.random.randn(7)
    v = np.random.randn(7)
    # Get vector from orthogonal projection
    p = np.dot(u, v) / np.dot(u, u) * u
    # Get cosinus according to Thales theorem
    cos_1 = np.linalg.norm(p) / np.linalg.norm(v)
    # Same thing in one line because dot(..)/dot(..) is a scalar
    cos_2 = np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))
    # Print result in degrees
    print(f"theta: {np.degrees(np.arccos(cos_1))}")
    print(f"theta in multiple lines: {np.degrees(np.arccos(cos_2))}")
    \end{minted}

    In the first way, we simply make an orthogonal projection, that create a rectangle triangle. Then we apply Thales theorem that indicate that $\cos(\theta) = \dfrac{\text{adjacent}}{\text{hypotenuse}}$ by taking the norm of our vectors (the norm used is euclidian norm that give us the euclidian distance from the vector).

    In the second way, we use the fact that the scalar product can be written as $\langle u, v \rangle = \cos(\theta) \cdot ||u|| \cdot ||v||$ (with $||\cdot||$ the euclidian norm).
    So it give us that $\cos(\theta) = \dfrac{\langle u, v \rangle}{||u|| \cdot ||v||}$.
    This formula is simpler to code in 1 line, and it's easy to proove equivalence between the two formulas obtained by developping and simplify the computation of $\dfrac{||p||}{||v||}$



# Computing Eigenvalues, Eigenvectors, and Determinants

1. Find the determinant, eigenvectors, and eigenvalues of the matrix
   $$A = 
   \begin{bmatrix}
   5  & 6 & 3  \\
   -1 & 0 & 1  \\
   1  & 2 & -1
   \end{bmatrix}
   $$
   Compare your results with those of the computer.

   \hrulefill

    The determinant of a matrix can be computed by following the formula [-@eq-det], according to the Laplace expansion.

    <!-- $$
    \begin{align}
    \det(A) = \sum_{\sigma \in S_n} \text{sgn}(\sigma) \prod_{i=1}^{n} a_{i,\sigma(i)} \\ 
    \text{sgn}(\sigma) =
    \begin{cases} 
        +1 & \text{if} \ \sigma \ \text{is pair} \\
        -1 & \text{else} 
    \end{cases}
    \end{align}$$ -->
    $$
     \det(A) = \sum_{j=1}^{n} (-1)^{i+j} a_{ij} \det(M_{ij})
    $$ {#eq-det}
    With $M_{ij}$ the sumatrix obtained by removing the $i$-th row and the $j$-th column of $A$.
    So we have for $i = 1$:
    $$
     \begin{aligned}
        \det(A) & = \sum_{j=1}^{n} (-1)^{1+j} a_{1j} \det(A_{1j}) \\
    &= + 5 \times (0 \times (-1) - (2 \times 1)) - 6 \times ((-1) \times (-1)- (1 \times 1)) + 3 \times ((-1) \times 2 - 1 \times 0)\\
    &= -10 - 0 - 6 \\
    &= -16
    \end{aligned}
    $$

    The eigen values are the result of the equation $\det(A - \lambda I) = 0$ with $\det(A - \lambda I)$ the characteristic polynomial of $A$.
    $$
    \begin{aligned}
        \det(A - \lambda I) &=
        \begin{bmatrix}
        5 - \lambda  & 6 & 3  \\
        -1 & 0 - \lambda & 1  \\
        1  & 2 & -1 - \lambda
        \end{bmatrix} \\
        &= (5 - \lambda)(\lambda^2 + \lambda - 2) - 3\lambda - 6 \\
        &= 5 \lambda^2 + 5 \lambda - 10 - \lambda^3 - \lambda^2 + 2\lambda - 3 \lambda - 6 \\
        &= -\lambda^3 + 4\lambda^2 + 4\lambda - 16 \\
    \end{aligned}
    $$
    Now we search a first root of this polynom to factorize it.
    According to the rational root theorem, we search root that can divide $16$.
    - $\lambda = 1$:
        $$-1^3 + 4\cdot 1^2 + 4 \cdot 1 - 16 = -9$$
    - $\lambda = 2$:
        $$-2^3 + 4 \cdot 2^2 + 4 \cdot 2 - 16 = 0$$
    So $2$ is a root of the polynom.
    So we can factorize the polynom by $\lambda - 2$. To achieve our goal, we use $x$ instead of $\lambda$ to use a latex package that compute details of the operation.
    $$
    \polylongdiv[style=D]{-x^{3} + 4x^{2} + 4x - 16}{x - 2}
    $$
    So we have the polynom $(\lambda - 2)(-\lambda^2 + 2 \lambda + 8) = (2 - \lambda)(\lambda^2 - 2 \lambda - 8)$
    As eigen values are given by the roots of the polynom $\det(A - \lambda I)$, we have the following eigen values:
    $$
    \begin{aligned}
        &(2 - \lambda)(\lambda^2 - 2\lambda - 8) = 0 \\
        \ \Longleftrightarrow \ &
        \begin{cases}
            2 - \lambda = 0 \\
            \lambda^2 - 2\lambda - 8 = 0
        \end{cases} \\
        \ \Longleftrightarrow \ &
        \begin{cases}
            \lambda = 2 \\
            \lambda = \dfrac{2 \pm \sqrt{(-2)^2 - 4 \cdot 1 \cdot (-8)}}{2 \cdot 1} & \text{(quadratic formula)}
        \end{cases} \\
        \ \Longleftrightarrow \ &
        \begin{cases}
            \lambda_1 = 2 \\
            \lambda = \dfrac{2 \pm \sqrt{36}}{2} = \dfrac{2 \pm 6}{2}
        \end{cases} \\
        \ \Longleftrightarrow \ & 
        \begin{cases}
            \lambda_1 = 2 \\
            \lambda_2 = 4 \\
            \lambda_3 = -2
        \end{cases}
    \end{aligned}
    $$

    Now, we will find a eigen vector $\mathbf{v}$ of the matrix $A$ such that $(A - \lambda I)\mathbf{v} = \mathbf{0}$.
    We have:
    - $\lambda_1 = 2$
    $$
    A - \lambda I = 
    \begin{bmatrix}
    5 - 2  & 6 & 3  \\
    -1 & 0 - 2 & 1  \\
    1  & 2 & -1 - 2
    \end{bmatrix}
    = \begin{bmatrix}
    3  & 6 & 3  \\
    -1 & - 2 & 1  \\
    1  & 2 & -3
    \end{bmatrix}
    $$
    So we can etablish the equation system as follow:
    $$
    \begin{aligned}
    & (A - \lambda I)\mathbf{v}  = \mathbf{0} \\
    \ \Longleftrightarrow \ &
    \begin{cases}
        3 v_1 + 6 v_2 + 3 v_3 = 0 \\
        -v_1 - 2 v_2 + v_3 = 0 \\
        v_1 + 2 v_2 - 3 v_3 = 0
    \end{cases} \\
    \ \Longleftrightarrow \ &
    \begin{cases}
        v_1 + 2 v_2 = 0 \\
        v_3 = 0
    \end{cases} \\
    \ \Longleftrightarrow \ &
    \begin{cases}
        v_1 = -2 v_2 \\
        v_3 = 0
    \end{cases}
    \end{aligned}
    $$
    So $v_1 = \begin{bmatrix} -2 t \\ t \\ 0 \end{bmatrix}$ for $t \in \mathbb{R}$

    - $\lambda_2 = 4$
    $$
    A - \lambda I = 
    \begin{bmatrix}
    5 - 4  & 6 & 3  \\
    -1 & 0 - 4 & 1  \\
    1  & 2 & -1 - 4
    \end{bmatrix}
    = \begin{bmatrix}
    1  & 6 & 3  \\
    -1 & - 4 & 1  \\
    1  & 2 & -5
    \end{bmatrix}
    $$
    So we can etablish the equation system as follow:
    $$
    \begin{aligned}
    & (A - \lambda I)\mathbf{v}  = \mathbf{0} \\
    \ \Longleftrightarrow \ &
    \begin{cases}
        v_1 + 6 v_2 + 3 v_3 = 0 \\
        -v_1 - 4 v_2 + v_3 = 0 \\
        v_1 + 2 v_2 - 5 v_3 = 0
    \end{cases} \\
    \ \Longleftrightarrow \ &
    \begin{cases}
        v_1 = 9 v_3 \\
        v_2 = - 2 v_3
    \end{cases} \\
    \end{aligned}
    $$
    So $v_2 = \begin{bmatrix} 9t \\ -2t \\ t \end{bmatrix}$ for $t \in \mathbb{R}$

    - $\lambda_3 = -2$
    $$
    A - \lambda I = 
    \begin{bmatrix}
    5 + 2  & 6 & 3  \\
    -1 & 0 + 2 & 1  \\
    1  & 2 & -1 + 2
    \end{bmatrix}
    = \begin{bmatrix}
    7  & 6 & 3  \\
    -1 & 2 & 1  \\
    1  & 2 & 1
    \end{bmatrix}
    $$
    So we can etablish the equation system as follow:
    $$
    \begin{aligned}
    & (A - \lambda I)\mathbf{v}  = \mathbf{0} \\
    \ \Longleftrightarrow \ &
    \begin{cases}
        7 v_1 + 6 v_2 + 3 v_3 = 0 \\
        -v_1 + 2 v_2 + v_3 = 0 \\
        v_1 + 2 v_2 + v_3 = 0
    \end{cases} \\
    \ \Longleftrightarrow \ &
    \begin{cases}
        v_1 = 0 \\
        v_3 = -2 v_2
    \end{cases} \\
    \end{aligned}
    $$
    So $v_3 = \begin{bmatrix} 0 \\ t \\ -2t \end{bmatrix}$ for $t \in \mathbb{R}$

    This is the code used to verify the results. Note that we use sympy to have exact values instead of numpy which is better for computation.

    \begin{minted}{python}
    import sympy as sp

    A = sp.Matrix([[5, 6, 3],
                  [-1, 0, 1],
                  [1, 2, -1]])
    eigenvals = A.eigenvals()
    eigenvects = A.eigenvects()
    eigenvals = [i for i, _ in eigenvals.items()]
    print(f"Eigen values: {eigenvals}")
    print(f"Eigen vectors: {sp.pprint([(i, j) for i, _, j in eigenvects])}")
    \end{minted}



2. The covariance matrix for n samples $x_1, \dots, x_n$ , each represented by a $d \times 1$ column vector, is given by
   $$
   C = \frac{1}{n - 1} \sum^n_{i=1} (x_i - \mu)(x_i - \mu)^T,
   $$
   where $C$ is a $d \times d$ matrix and $\mu = \sum^n_{i=1} x_i/n$ is the sample mean.

   Prove that $C$ is always positive semidefinite. (Note: A symmetric matrix $C$ of size $d \times d$ is positive semidefinite if $v^T C v \geq 0$ for every $d \times 1$ vector $v$.)

   \hrulefill

    A symmetric matrix $C$ of size $d \times d$ is positive semidefinite if $v^T C v \geq 0 \ \forall v \in \mathbb{R}^d$.

    We define $X$ the matrix $\begin{bmatrix}x_1 & x_2 & \cdots & x_n\end{bmatrix}$ with $x_i$ the column vectors, and $M$ the matrix $\underbrace{\begin{bmatrix} \mu & \cdots & \mu \end{bmatrix}}_{n \ \text{times}}$ such as $X, M \in \mathbb{R}^{d \times n}$
    Then, we can write:
    $$
    C = \frac{1}{n - 1} \sum^n_{i=1} (x_i - \mu)(x_i - \mu)^T = \frac{1}{n - 1}\underbrace{(X - M)}_{d \times n}\underbrace{(X - M)^T}_{n \times d}
    $$
    Let $v \in \mathbb{R}^d$ a vector.
    We have:
    $$
    v^TCv = v^T \frac{1}{n - 1} (X - M)(X - M)^Tv = \frac{1}{n - 1} \underbrace{\left(v^T(X - M)\right)}_{A \in \mathbb{R}^{1 \times n}}\left(v^T(X - M)\right)^T = \frac{1}{n - 1}AA^T
    $$
    As $n \geq 1$, $\frac{1}{n - 1} \geq 0$.
    As the dimension of $A$ is $1 \times n$, $AA^T = \sum_{i = 1}^n (A_i)^2$ and as a sum of squared number is always greater or equal to $0$, we have that $\frac{1}{n - 1}AA^T \geq 0 \ \Longleftrightarrow \ v^T C v \geq 0$.

    So the covariance matrix is always positive semidefinite.


3. In this portion of the exercise, we will calculate the eigenvalues of the covariance matrices of six data sets listed as follows:

   | filename                       | $n$  | $d$ | description                                                |
   |:-------------------------------:|:------:|:-----:|:-----------------------------------------------------------:|
   | tp1_artificialdata[1-3]         | 1024 | 100 | Artificial data generated from various auto-regression     |
   | tp1_artificialdata4             | 1024 | 100 | Random Gaussian data                                       |
   | tp1_freyfaces                   | 1965 | 560 | Facial images of a man named Brendan                       |
   | tp1_digit2                      | 5958 | 784 | Hand-written images of "2"                                 |

   Download and unzip `data for python.zip`. Each file contains a $n \times d$ data matrix with rows representing $n$ different samples in $\mathbb{R}^d$.

   (a) Compute the covariance matrix of each dataset.

   (b) Compute the eigenvalues for each covariance matrix.

   (c) Compute the determinant of each covariance matrix.

   (d) Compute the product of the eigenvalues for each covariance matrix.

   (e) Display the eigenspectrum for each covariance matrix in a 2D plot.

   _Describe the relationship between the product of the eigenvalues and the determinant of each covariance matrix. In addition, describe the observations you made regarding the plot of the spectrum of eigenvalues of each covariance matrix. How can you explain the disparities between datasets?_

   \hrulefill

   The code **code.py** given takes several minutes to execute !!! So I put all the output of the code in the report.

    We can see that the product of the eigenvalues is always 0, as the determinant for each covariance matrix.
    It's due to the relation between the product of the eigenvalues and the determinant.
    According to the eigen value decomposition, the covariance matrix (which is positive semidefinite) can be written as $A = U \Sigma U^{-1}$ with $\Sigma$ the matrix composed by the eigen values of $A$.

    So we have
    $$
    \det(A) = \det(U\Sigma U^{-1}) = \det(U) \det(\Sigma) \det(U^{-1}) = \dfrac{\det(U)}{\det(U)} \det(\Sigma) = \det(\Sigma) = \prod_i \lambda_i
    $$
    So the product of the eigenvalues is equal to the determinant of the covariance matrix.
    On top of that, we can see that the eigenspectrum has always the same form: a decrease curve that go around 0.
    We can constate that this curve decrease like inverse of exponential, and it's more marked when the number of data increase.
    As the eigen values represent the variance of the data in each dimension, it means that when the spectrum dercrease quickly until values near 0, the variance of each dimension decrease also quickly.
    So the variance of a lot of dimensions is in the neighborhood of $0$.
    It means that for this dataset, all the dimensions are not required because if the variance is near $0$, all the data have approximatively the same value in this dimension.
    So looking at the spectre of the eigen value is very interesting to know the number of dimensions needed to represent our datas.

4. Let $A \in \mathbb{R}^{n \times n}$ be a square matrix. Show that if \( A \) has an eigenvalue \( \lambda = 0 \), then the matrix \( A \)  is singular. Furthermore, prove that the determinant of \( A \) must be zero if any eigenvalue is zero.

   \hrulefill

    Let ${\lambda_1, \cdots, \lambda_n}$ the eigenvalues of $A$.
    The caracteristic polynom $p$ can be written as [-@eq-poly].
    $$
    p(x) = \det(A - xI) = (\lambda_1 - x)(\lambda_2 - x)\cdots(\lambda_n - x) = \prod_i^n (\lambda_i - x)
    $$ {#eq-poly}
    If we evaluate this polynom in $x = 0$, we obtain the following result [-@eq-detpoly].
    $$
    p(0) = \det(A - 0I) = \det(A) = \prod_i^n \lambda_i
    $$ {#eq-detpoly}
    So if $A$ has an eigenvalue $\lambda_i = 0$, then we have
    $$
    \prod_i^n \lambda_i = 0 = \det(A)
    $$
    So $\det(A) = 0$ so the matrix is singular.
    So if any eigenvalue is $0$, the determinant of the matrix is equal to $0$ and the matrix is singular.  


# Computing Projection Onto a Line

There are given a line $\alpha : 3x + 4y = -6$ and a point $A$ with the coordinates $(-1, 3)$.

1. Find a distance from the point $A$ to the line $\alpha$ using linear algebra (not coordinate method).
2. Explain your code using a sketch and some mathematics (there should be a scalar product somewhere).

\hrulefill

1. First, we define a point on the line to create vector.
    To achieve our goal, I choose $x = -2$.
    So I have
    $$
    3x + 4y = -6 \ \Longleftrightarrow \ 4y = -6 + 6 \ \Longleftrightarrow \ y = 0
    $$
    So the point $B = (-2, 0)$ is on the line $\alpha$.
    We can define a vector $\vec{n} = \begin{bmatrix} 3 \\ 4 \end{bmatrix}$ which is the vector normal, perpendicular to the line.
    We can define a vector from the point of the line to the point $A$: $\vec{u} = \begin{bmatrix} -1 + 2 \\ 3 - 0 \end{bmatrix} = \begin{bmatrix} 1 \\ 3 \end{bmatrix}$
    Now, we want to find the orthogonal projection of the vector $\vec{u}$ on the vector $\vec{n}$.
    The orthogonal projection $\vec{p}$ give us:
    $$
    \vec{p}
    = \frac{\langle \vec{u}, \vec{n} \rangle}{\langle\vec{n}, \vec{n}\rangle}\vec{n}
    = \frac{3 + 12}{9 + 16}\begin{bmatrix} 3 \\ 4 \end{bmatrix}
    = \begin{bmatrix} \frac{9}{5} \\ \frac{12}{5} \end{bmatrix}
    $$

    If we calculate the norm of this vector, we obtain the shortest distance between the point and the line.
    It give us:
    $$
    || \vec{n} ||_2
    = \sqrt{\left(frac{9}{5}\right)^2 + \left(\frac{12}{5}\right)^2}
    = \sqrt{\frac{81}{25} + \frac{144}{25}}
    = \sqrt{\frac{225}{25}}
    = \sqrt{9}
    = 3
    $$
    So the distance from the point $B$ to the line $\alpha$ is of $3$.

2. My code is basically what I have explained in the precedent question.

    \begin{minted}{python}
    import numpy as np

    A = np.array([-1, 3])
    y = lambda x: (-6 -3 * x)/4
    B = np.array([-2, y(-2)])
    n = np.array([3, 4])
    u = A - B

    p = np.dot(n, u) / np.dot(n, n) * n
    d = np.sqrt(sum(p**2))
    print(f"Distance of the point to the line: {d}")
    \end{minted}
