# Generated by qwen3-coder:480b-cloud
# Reviewed and improved by me
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

def shifted_exponential_samples(a, lam, n_samples=100):
    """
    Generate samples from shifted exponential distribution
    """
    standard_exp_samples = np.random.exponential(scale=1/lam, size=n_samples)
    samples = standard_exp_samples + a
    return samples

def shifted_exponential_pdf(x, a, lam):
    """
    Probability density function of shifted exponential distribution
    """
    pdf_values = np.where(x >= a, lam * np.exp(-lam * (x - a)), 0)
    return pdf_values

def mom_estimators(samples):
    """
    Method of Moments estimators for shifted exponential distribution
    
    For Shifted Exp(a, λ):
    E[X] = a + 1/λ
    Var[X] = 1/λ²
    
    MoM estimations:
    λ_hat = 1/sqrt(sample_variance)
    a_hat = sample_mean - 1/λ_hat
    """
    sample_mean = np.mean(samples)
    sample_var = np.var(samples)  # Population variance for MoM
    
    # MoM estimator: λ based on variance
    lam_mom = 1 / np.sqrt(sample_var)
    
    # MoM estimator: a based on λ_mom
    a_mom = sample_mean - 1 / lam_mom
    return a_mom, lam_mom

def mle_estimators(samples):
    """
    Maximum Likelihood Estimators for shifted exponential distribution
    
    MLE equations:
    â = min(X₁, X₂, ..., Xₙ) (minimum of samples)
    λ̂ = n / Σ(Xᵢ - â)
    """
    n = len(samples)
    a_mle = np.min(samples)  # MLE of shift parameter
    lam_mle = n / np.sum(samples - a_mle)  # MLE of rate parameter
    
    return a_mle, lam_mle

# Parameters
true_a = 2.0        # true shift parameter
true_lam = 0.7      # true rate parameter
n_samples = 100
n_experiments = 5000

print("="*70)
print("SHIFTED EXPONENTIAL DISTRIBUTION")
print("="*70)
print(f"True parameters: a = {true_a}, λ = {true_lam}")
print(f"Sample size: {n_samples}")
print(f"Number of experiments: {n_experiments}")
print()

# Initialize arrays to store estimates
a_mom_estimates = np.zeros(n_experiments)
lam_mom_estimates = np.zeros(n_experiments)
a_mle_estimates = np.zeros(n_experiments)
lam_mle_estimates = np.zeros(n_experiments)

# Run experiments
for i in range(n_experiments):
    if (i + 1) % 1000 == 0:
        print(f"Completed {i + 1}/{n_experiments} experiments...")
    
    # Generate samples
    samples = shifted_exponential_samples(true_a, true_lam, n_samples)
    
    # Compute MoM estimators
    a_mom, lam_mom = mom_estimators(samples)
    a_mom_estimates[i] = a_mom
    lam_mom_estimates[i] = lam_mom
    
    # Compute MLE estimators
    a_mle, lam_mle = mle_estimators(samples)
    a_mle_estimates[i] = a_mle
    lam_mle_estimates[i] = lam_mle

print("All experiments completed!")
print()

# Calculate statistics
print("ESTIMATOR VALUES OVER 1 EXPERIMENTS:")
print("="*50)

print("Parameter 'a' estimators:")
print("-" * 30)
print(f"True value: {true_a}")
print(f"MoM: {a_mom_estimates[0]:.6f}")
print(f"MLE: {a_mle_estimates[0]:.6f}")
print()

print("Parameter 'λ' estimators:")
print("-" * 30)
print(f"True value: {true_lam}")
print(f"MoM: {lam_mom_estimates[0]:.6f}")
print(f"MLE: {lam_mle_estimates[0]:.6f}")
print()

# Create histograms
plt.figure(figsize=(15, 12))

# Histogram for 'a' parameter estimators
plt.subplot(1, 2, 1)
plt.axvline(true_a, color='green', linewidth=2, linestyle='--', label=f'True a = {true_a}')
plt.axvline(np.mean(a_mom_estimates), color='cyan', linewidth=2, linestyle='--', label=f'MoM mean = {np.mean(a_mom_estimates):.4f}')
plt.axvline(np.mean(a_mle_estimates), color='magenta', linewidth=2, linestyle='--', label=f'MLE mean = {np.mean(a_mle_estimates):.4f}')
plt.hist(a_mom_estimates, bins=50, alpha=0.7, color='blue', edgecolor='black', density=True, 
         label=f'MoM    (var={np.var(a_mom_estimates):.4f})')
plt.hist(a_mle_estimates, bins=50, alpha=0.7, color='red', edgecolor='black', density=True, 
         label=f'MLE    (var={np.var(a_mle_estimates):.4f})')
# Get some kind of zoom inside interesting zones
plt.xlim(true_a - 0.2, true_a + 0.2)
plt.xlabel('Estimated value of a')
plt.ylabel('Density')
plt.title('Empirical Distribution of Estimator for Parameter a')
plt.legend()
plt.grid(True, alpha=0.3)

# Histogram for 'λ' parameter estimators
plt.subplot(1, 2, 2)
plt.axvline(true_lam, color='green', linewidth=2, linestyle='--', label=f'True λ = {true_lam}')
plt.axvline(np.mean(lam_mom_estimates), color='cyan', linewidth=2, linestyle='--', label=f'MoM mean = {np.mean(lam_mom_estimates):.4f}')
plt.axvline(np.mean(lam_mle_estimates), color='magenta', linewidth=2, linestyle='--', label=f'MLE mean = {np.mean(lam_mle_estimates):.4f}')
plt.hist(lam_mom_estimates, bins=50, alpha=0.7, color='blue', edgecolor='black', density=True, label=f'MoM  (var={np.var(lam_mom_estimates):.4f})')
plt.hist(lam_mle_estimates, bins=50, alpha=0.7, color='red', edgecolor='black', density=True, label=f'MLE   (var={np.var(lam_mle_estimates):.4f})')
plt.xlabel('Estimated value of λ')
plt.ylabel('Density')
plt.title('Empirical Distribution of Estimator for Parameter λ')
plt.legend()
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Summary comparison
print("SUMMARY COMPARISON:")
print("="*30)
print("For parameter 'a':")
print(f"  MoM Variance: {np.var(a_mom_estimates):.6f}")
print(f"  MLE Variance: {np.var(a_mle_estimates):.6f}")
print(f"  MLE has {(np.var(a_mom_estimates)/np.var(a_mle_estimates) - 1)*100:.1f}% smaller variance")
print()
print("For parameter 'λ':")
print(f"  MoM Variance: {np.var(lam_mom_estimates):.6f}")
print(f"  MLE Variance: {np.var(lam_mle_estimates):.6f}")
print(f"  MLE has {(np.var(lam_mom_estimates)/np.var(lam_mle_estimates) - 1)*100:.1f}% smaller variance")
print()

# Bias comparison
print("BIAS COMPARISON:")
print("="*20)
print("For parameter 'a':")
print(f"  MoM Bias: {np.mean(a_mom_estimates) - true_a:.6f}")
print(f"  MLE Bias: {np.mean(a_mle_estimates) - true_a:.6f}")
print()
print("For parameter 'λ':")
print(f"  MoM Bias: {np.mean(lam_mom_estimates) - true_lam:.6f}")
print(f"  MLE Bias: {np.mean(lam_mle_estimates) - true_lam:.6f}")
print()
