== Markovianity

We can keep only neighborhood of $x_i$ and not all the $x_j$...
$p(x_1)product_(i = 2)^N p(x_i | x_(i - 1))$

We can obtain some sofistical distribution by applying a succession of linear transformation with small non-linear transformation at each step...

== Conditional independence

$x_1$ and $x_3$ are independent ACCORDING to $x_2$ given.

$p(x_1, x_2, x_3) = p(x_2) p(x_1 | x_2) p(x_3 | x_2)$

Unfolding: decompose very complex form to linear forms...

All vectors generated by a gaussian distribution have the same euclidean norm !

Taking L_1, L_2, L_3 etc... norms is the same than taking 1, 2, 3 moments

Le Jepa 12 Nov 2025 Yann Yelem

Batch norm: we must make all vectors having the same norm to right train the AI models !!!
