project:
  type: website
  title: "ISS"
  output-dir: ../_site/fr
  render:
    - "ds*1*"


website:
  # Language switching setup

  navbar:
    # background: primary
    search: true
    
    # Right side for language selector
    right:
      - text: Langage
        icon: globe
        menu:
          - text: "Anglais"
            href: ../index.html
          - text: "Français"
            href: index.html
  sidebar:
      style: "docked"
      search: true
      contents:
      - section: "Espaces de Représentation en Haute Dimension"
        contents: "ds21*"
      - section: "Principal Component Analysis"
        contents: "ds31*"
      - section: "Linear Discriminant Analysis"
        contents: "ds51*"
      - section: "k-Means"
        contents: "ds7*"
      - section: "Expectation-Maximization"
        contents: "ds6*"



format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
  pdf:
    toc: true