<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ds91 – ISS</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-96c1bb8b336142dcc39f931773fab1b9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-9ee82e006983bafa07c9ac29a901142c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-96c1bb8b336142dcc39f931773fab1b9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">ISS</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-langage" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-globe" role="img">
</i> 
 <span class="menu-text">Langage</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-langage">    
        <li>
    <a class="dropdown-item" href="./../index.html">
 <span class="dropdown-text">Anglais</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./index.html">
 <span class="dropdown-text">Français</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Espaces de Représentation en Haute Dimension</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ds21.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Représentations en Haute Dimension en Data Science</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ds21q.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exam question</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Principal Component Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ds31.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cours : Analyse en Composantes Principales (PCA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ds31q.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Analyse en Composantes Principales (PCA) : Méthode, Calcul et Interprétation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Linear Discriminant Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ds51.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cours : Analyse Discriminante Linéaire (LDA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ds51q.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Relation entre l’Analyse Discriminante Linéaire (LDA) et la modélisation conditionnelle pour la classification</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">k-Means</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ds7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cours détaillé</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ds7q.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Questions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ds7s.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">L’essentiel</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ds7s1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Intuition</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Expectation-Maximization</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ds6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cours détaillé</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ds6q.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Questions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ds6s.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">L’essentiel</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ds6s1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Intuition</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#fondamentaux-de-la-théorie-de-linformation-pour-la-data-science" id="toc-fondamentaux-de-la-théorie-de-linformation-pour-la-data-science" class="nav-link active" data-scroll-target="#fondamentaux-de-la-théorie-de-linformation-pour-la-data-science">Fondamentaux de la Théorie de l’Information pour la Data Science</a>
  <ul class="collapse">
  <li><a href="#introduction-et-contexte" id="toc-introduction-et-contexte" class="nav-link" data-scroll-target="#introduction-et-contexte">Introduction et Contexte</a>
  <ul class="collapse">
  <li><a href="#vue-densemble" id="toc-vue-densemble" class="nav-link" data-scroll-target="#vue-densemble">Vue d’ensemble</a></li>
  <li><a href="#applications-en-data-science" id="toc-applications-en-data-science" class="nav-link" data-scroll-target="#applications-en-data-science">Applications en Data Science</a></li>
  <li><a href="#notations-et-conventions" id="toc-notations-et-conventions" class="nav-link" data-scroll-target="#notations-et-conventions">Notations et Conventions</a></li>
  </ul></li>
  <li><a href="#fondements-probabilistes" id="toc-fondements-probabilistes" class="nav-link" data-scroll-target="#fondements-probabilistes">Fondements Probabilistes</a>
  <ul class="collapse">
  <li><a href="#rappel-espérance-mathématique" id="toc-rappel-espérance-mathématique" class="nav-link" data-scroll-target="#rappel-espérance-mathématique">Rappel : Espérance mathématique</a></li>
  <li><a href="#règle-de-chaîne-pour-les-probabilités" id="toc-règle-de-chaîne-pour-les-probabilités" class="nav-link" data-scroll-target="#règle-de-chaîne-pour-les-probabilités">Règle de Chaîne pour les Probabilités</a></li>
  <li><a href="#exemples-de-décompositions" id="toc-exemples-de-décompositions" class="nav-link" data-scroll-target="#exemples-de-décompositions">Exemples de Décompositions</a></li>
  </ul></li>
  <li><a href="#entropie-mesure-de-lincertitude" id="toc-entropie-mesure-de-lincertitude" class="nav-link" data-scroll-target="#entropie-mesure-de-lincertitude">Entropie : Mesure de l’Incertitude</a>
  <ul class="collapse">
  <li><a href="#entropie-discrète" id="toc-entropie-discrète" class="nav-link" data-scroll-target="#entropie-discrète">Entropie Discrète</a></li>
  <li><a href="#cas-binaire-variable-de-bernoulli" id="toc-cas-binaire-variable-de-bernoulli" class="nav-link" data-scroll-target="#cas-binaire-variable-de-bernoulli">Cas Binaire : Variable de Bernoulli</a></li>
  <li><a href="#entropies-multivariées" id="toc-entropies-multivariées" class="nav-link" data-scroll-target="#entropies-multivariées">Entropies Multivariées</a></li>
  <li><a href="#propriétés-fondamentales-de-lentropie" id="toc-propriétés-fondamentales-de-lentropie" class="nav-link" data-scroll-target="#propriétés-fondamentales-de-lentropie">Propriétés Fondamentales de l’Entropie</a></li>
  <li><a href="#application-aux-vecteurs-dimages" id="toc-application-aux-vecteurs-dimages" class="nav-link" data-scroll-target="#application-aux-vecteurs-dimages">Application aux Vecteurs d’Images</a></li>
  </ul></li>
  <li><a href="#applications-au-codage-et-à-la-compression" id="toc-applications-au-codage-et-à-la-compression" class="nav-link" data-scroll-target="#applications-au-codage-et-à-la-compression">Applications au Codage et à la Compression</a>
  <ul class="collapse">
  <li><a href="#concepts-fondamentaux-du-codage" id="toc-concepts-fondamentaux-du-codage" class="nav-link" data-scroll-target="#concepts-fondamentaux-du-codage">Concepts Fondamentaux du Codage</a></li>
  <li><a href="#assignation-optimale-de-codes" id="toc-assignation-optimale-de-codes" class="nav-link" data-scroll-target="#assignation-optimale-de-codes">Assignation Optimale de Codes</a></li>
  <li><a href="#codage-de-huffman" id="toc-codage-de-huffman" class="nav-link" data-scroll-target="#codage-de-huffman">Codage de Huffman</a></li>
  <li><a href="#codes-préfixes" id="toc-codes-préfixes" class="nav-link" data-scroll-target="#codes-préfixes">Codes Préfixes</a></li>
  <li><a href="#exemple-complet-image-à-8-niveaux" id="toc-exemple-complet-image-à-8-niveaux" class="nav-link" data-scroll-target="#exemple-complet-image-à-8-niveaux">Exemple Complet : Image à 8 Niveaux</a></li>
  <li><a href="#complexité-et-limitations" id="toc-complexité-et-limitations" class="nav-link" data-scroll-target="#complexité-et-limitations">Complexité et Limitations</a></li>
  </ul></li>
  <li><a href="#mesures-de-divergence-et-similarité" id="toc-mesures-de-divergence-et-similarité" class="nav-link" data-scroll-target="#mesures-de-divergence-et-similarité">Mesures de Divergence et Similarité</a>
  <ul class="collapse">
  <li><a href="#divergence-de-kullback-leibler-kl" id="toc-divergence-de-kullback-leibler-kl" class="nav-link" data-scroll-target="#divergence-de-kullback-leibler-kl">Divergence de Kullback-Leibler (KL)</a></li>
  <li><a href="#exemple-numérique-de-kl-divergence" id="toc-exemple-numérique-de-kl-divergence" class="nav-link" data-scroll-target="#exemple-numérique-de-kl-divergence">Exemple Numérique de KL Divergence</a></li>
  <li><a href="#cross-entropy-entropie-croisée" id="toc-cross-entropy-entropie-croisée" class="nav-link" data-scroll-target="#cross-entropy-entropie-croisée">Cross-Entropy (Entropie Croisée)</a></li>
  </ul></li>
  <li><a href="#information-mutuelle" id="toc-information-mutuelle" class="nav-link" data-scroll-target="#information-mutuelle">Information Mutuelle</a>
  <ul class="collapse">
  <li><a href="#définitions-et-formulations" id="toc-définitions-et-formulations" class="nav-link" data-scroll-target="#définitions-et-formulations">Définitions et Formulations</a></li>
  <li><a href="#propriétés-fondamentales-1" id="toc-propriétés-fondamentales-1" class="nav-link" data-scroll-target="#propriétés-fondamentales-1">Propriétés Fondamentales</a></li>
  <li><a href="#relations-avec-lentropie" id="toc-relations-avec-lentropie" class="nav-link" data-scroll-target="#relations-avec-lentropie">Relations avec l’Entropie</a></li>
  <li><a href="#information-mutuelle-conditionnelle" id="toc-information-mutuelle-conditionnelle" class="nav-link" data-scroll-target="#information-mutuelle-conditionnelle">Information Mutuelle Conditionnelle</a></li>
  <li><a href="#règle-de-chaîne-pour-linformation-mutuelle" id="toc-règle-de-chaîne-pour-linformation-mutuelle" class="nav-link" data-scroll-target="#règle-de-chaîne-pour-linformation-mutuelle">Règle de Chaîne pour l’Information Mutuelle</a></li>
  <li><a href="#décompositions-complexes" id="toc-décompositions-complexes" class="nav-link" data-scroll-target="#décompositions-complexes">Décompositions Complexes</a></li>
  <li><a href="#inégalité-de-traitement-des-données-data-processing-inequality" id="toc-inégalité-de-traitement-des-données-data-processing-inequality" class="nav-link" data-scroll-target="#inégalité-de-traitement-des-données-data-processing-inequality">Inégalité de Traitement des Données (Data Processing Inequality)</a></li>
  </ul></li>
  <li><a href="#variables-continues-entropie-différentielle" id="toc-variables-continues-entropie-différentielle" class="nav-link" data-scroll-target="#variables-continues-entropie-différentielle">Variables Continues : Entropie Différentielle</a>
  <ul class="collapse">
  <li><a href="#motivation-et-limite" id="toc-motivation-et-limite" class="nav-link" data-scroll-target="#motivation-et-limite">Motivation et Limite</a></li>
  <li><a href="#définition-de-lentropie-différentielle" id="toc-définition-de-lentropie-différentielle" class="nav-link" data-scroll-target="#définition-de-lentropie-différentielle">Définition de l’Entropie Différentielle</a></li>
  <li><a href="#entropie-différentielle-dune-gaussienne" id="toc-entropie-différentielle-dune-gaussienne" class="nav-link" data-scroll-target="#entropie-différentielle-dune-gaussienne">Entropie Différentielle d’une Gaussienne</a></li>
  <li><a href="#propriétés-de-lentropie-différentielle" id="toc-propriétés-de-lentropie-différentielle" class="nav-link" data-scroll-target="#propriétés-de-lentropie-différentielle">Propriétés de l’Entropie Différentielle</a></li>
  </ul></li>
  <li><a href="#applications-en-machine-learning" id="toc-applications-en-machine-learning" class="nav-link" data-scroll-target="#applications-en-machine-learning">Applications en Machine Learning</a>
  <ul class="collapse">
  <li><a href="#fonctions-de-perte" id="toc-fonctions-de-perte" class="nav-link" data-scroll-target="#fonctions-de-perte">Fonctions de Perte</a></li>
  <li><a href="#sélection-de-features-1" id="toc-sélection-de-features-1" class="nav-link" data-scroll-target="#sélection-de-features-1">Sélection de Features</a></li>
  <li><a href="#régularisation-et-variational-autoencoders" id="toc-régularisation-et-variational-autoencoders" class="nav-link" data-scroll-target="#régularisation-et-variational-autoencoders">Régularisation et Variational Autoencoders</a></li>
  </ul></li>
  <li><a href="#aide-mémoire-et-synthèse" id="toc-aide-mémoire-et-synthèse" class="nav-link" data-scroll-target="#aide-mémoire-et-synthèse">Aide-Mémoire et Synthèse</a>
  <ul class="collapse">
  <li><a href="#formules-essentielles" id="toc-formules-essentielles" class="nav-link" data-scroll-target="#formules-essentielles">Formules Essentielles</a></li>
  <li><a href="#propriétés-clés-à-retenir" id="toc-propriétés-clés-à-retenir" class="nav-link" data-scroll-target="#propriétés-clés-à-retenir">Propriétés Clés à Retenir</a></li>
  <li><a href="#questions-types-dexamen" id="toc-questions-types-dexamen" class="nav-link" data-scroll-target="#questions-types-dexamen">Questions Types d’Examen</a></li>
  <li><a href="#tableaux-récapitulatifs" id="toc-tableaux-récapitulatifs" class="nav-link" data-scroll-target="#tableaux-récapitulatifs">Tableaux Récapitulatifs</a></li>
  <li><a href="#cas-particuliers-importants" id="toc-cas-particuliers-importants" class="nav-link" data-scroll-target="#cas-particuliers-importants">Cas Particuliers Importants</a></li>
  <li><a href="#conseils-pour-lexamen" id="toc-conseils-pour-lexamen" class="nav-link" data-scroll-target="#conseils-pour-lexamen">Conseils pour l’Examen</a></li>
  <li><a href="#ressources-et-approfondissements" id="toc-ressources-et-approfondissements" class="nav-link" data-scroll-target="#ressources-et-approfondissements">Ressources et Approfondissements</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="ds91.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>





<section id="fondamentaux-de-la-théorie-de-linformation-pour-la-data-science" class="level1">
<h1>Fondamentaux de la Théorie de l’Information pour la Data Science</h1>
<section id="introduction-et-contexte" class="level2">
<h2 class="anchored" data-anchor-id="introduction-et-contexte">Introduction et Contexte</h2>
<section id="vue-densemble" class="level3">
<h3 class="anchored" data-anchor-id="vue-densemble">Vue d’ensemble</h3>
<p>La <strong>théorie de l’information</strong>, développée par Claude Shannon en 1948, fournit un cadre mathématique rigoureux pour quantifier l’information, l’incertitude et la dépendance entre variables aléatoires.</p>
</section>
<section id="applications-en-data-science" class="level3">
<h3 class="anchored" data-anchor-id="applications-en-data-science">Applications en Data Science</h3>
<p>Les concepts de la théorie de l’information sont fondamentaux dans de nombreux domaines :</p>
<ul>
<li><strong>Compression de données</strong> : optimisation du stockage et de la transmission</li>
<li><strong>Apprentissage automatique</strong> : fonctions de perte, régularisation</li>
<li><strong>Sélection de features</strong> : identification des variables les plus informatives</li>
<li><strong>Mesure de similarité</strong> : comparaison entre distributions</li>
<li><strong>Optimisation de réseaux de neurones</strong> : théorie de l’information bottleneck</li>
<li><strong>Théorie de la communication</strong> : capacité de canal, codage</li>
</ul>
</section>
<section id="notations-et-conventions" class="level3">
<h3 class="anchored" data-anchor-id="notations-et-conventions">Notations et Conventions</h3>
<section id="variables-et-ensembles" class="level4">
<h4 class="anchored" data-anchor-id="variables-et-ensembles">Variables et ensembles</h4>
<ul>
<li><span class="math inline">\(X, Y, Z\)</span> : variables aléatoires (majuscules)</li>
<li><span class="math inline">\(x, y, z\)</span> : valeurs prises par les variables (minuscules)</li>
<li><span class="math inline">\(\mathcal{X}, \mathcal{Y}, \mathcal{Z}\)</span> : ensembles de valeurs possibles</li>
<li><span class="math inline">\(|\mathcal{X}|\)</span> : cardinalité de l’ensemble <span class="math inline">\(\mathcal{X}\)</span></li>
</ul>
</section>
<section id="distributions-de-probabilité" class="level4">
<h4 class="anchored" data-anchor-id="distributions-de-probabilité">Distributions de probabilité</h4>
<ul>
<li><span class="math inline">\(p_X(x)\)</span> ou <span class="math inline">\(p(x)\)</span> : fonction de masse de probabilité (pmf) ou densité (pdf)</li>
<li><span class="math inline">\(p_{X,Y}(x,y)\)</span> ou <span class="math inline">\(p(x,y)\)</span> : distribution jointe</li>
<li><span class="math inline">\(p_{X|Y}(x|y)\)</span> ou <span class="math inline">\(p(x|y)\)</span> : distribution conditionnelle</li>
<li><span class="math inline">\(\mathbb{P}[X = x]\)</span> : probabilité que <span class="math inline">\(X\)</span> prenne la valeur <span class="math inline">\(x\)</span></li>
<li><span class="math inline">\(\mathbb{E}_{p}[f(X)]\)</span> : espérance de <span class="math inline">\(f(X)\)</span> sous la distribution <span class="math inline">\(p\)</span></li>
</ul>
</section>
<section id="symboles-spéciaux" class="level4">
<h4 class="anchored" data-anchor-id="symboles-spéciaux">Symboles spéciaux</h4>
<ul>
<li><span class="math inline">\(X \perp Y\)</span> : <span class="math inline">\(X\)</span> et <span class="math inline">\(Y\)</span> sont indépendants</li>
<li><span class="math inline">\(X \perp Z | Y\)</span> : <span class="math inline">\(X\)</span> et <span class="math inline">\(Z\)</span> sont conditionnellement indépendants sachant <span class="math inline">\(Y\)</span></li>
<li><span class="math inline">\(X \to Y \to Z\)</span> : chaîne de Markov</li>
<li><span class="math inline">\(\log\)</span> : logarithme (base 2 sauf indication contraire)</li>
<li><span class="math inline">\(\ln\)</span> : logarithme naturel (base <span class="math inline">\(e\)</span>)</li>
</ul>
</section>
<section id="unités-de-mesure" class="level4">
<h4 class="anchored" data-anchor-id="unités-de-mesure">Unités de mesure</h4>
<ul>
<li><strong>Bits</strong> : logarithme en base 2 (<span class="math inline">\(\log_2\)</span>)</li>
<li><strong>Nats</strong> : logarithme naturel (<span class="math inline">\(\ln\)</span> ou <span class="math inline">\(\log_e\)</span>)</li>
<li>Notation parfois utilisée : <span class="math inline">\(H_\alpha(X)\)</span> où <span class="math inline">\(\alpha\)</span> spécifie la base</li>
</ul>
</section>
</section>
</section>
<section id="fondements-probabilistes" class="level2">
<h2 class="anchored" data-anchor-id="fondements-probabilistes">Fondements Probabilistes</h2>
<section id="rappel-espérance-mathématique" class="level3">
<h3 class="anchored" data-anchor-id="rappel-espérance-mathématique">Rappel : Espérance mathématique</h3>
<section id="définition-générale" class="level4">
<h4 class="anchored" data-anchor-id="définition-générale">Définition générale</h4>
<p>Pour une variable aléatoire discrète <span class="math inline">\(X\)</span> et une fonction <span class="math inline">\(g\)</span> :</p>
<p><span class="math display">\[\mathbb{E}_{p_X}[g(X)] = \sum_{x \in \mathcal{X}} p_X(x) g(x)\]</span></p>
<p>Pour une variable continue :</p>
<p><span class="math display">\[\mathbb{E}_{f_X}[g(X)] = \int_{\mathcal{X}} f_X(x) g(x) dx\]</span></p>
</section>
<section id="propriétés" class="level4">
<h4 class="anchored" data-anchor-id="propriétés">Propriétés</h4>
<ul>
<li>Linéarité : <span class="math inline">\(\mathbb{E}[aX + bY] = a\mathbb{E}[X] + b\mathbb{E}[Y]\)</span></li>
<li>Pour variables indépendantes : <span class="math inline">\(\mathbb{E}[XY] = \mathbb{E}[X]\mathbb{E}[Y]\)</span></li>
</ul>
</section>
</section>
<section id="règle-de-chaîne-pour-les-probabilités" class="level3">
<h3 class="anchored" data-anchor-id="règle-de-chaîne-pour-les-probabilités">Règle de Chaîne pour les Probabilités</h3>
<section id="cas-général-n-variables" class="level4">
<h4 class="anchored" data-anchor-id="cas-général-n-variables">Cas général : N variables</h4>
<p>Pour <span class="math inline">\(N\)</span> variables aléatoires <span class="math inline">\(X_1, X_2, \ldots, X_n\)</span> :</p>
<p><span class="math display">\[p(x_1, x_2, \ldots, x_n) = p(x_1) \cdot p(x_2 | x_1) \cdot p(x_3 | x_2, x_1) \cdots p(x_n | x_{n-1}, \ldots, x_1)\]</span></p>
<p><strong>Forme compacte :</strong></p>
<p><span class="math display">\[p(x_1, x_2, \ldots, x_n) = \prod_{i=1}^{n} p(x_i | x_{i-1}, \ldots, x_1)\]</span></p>
<p>avec la convention que <span class="math inline">\(p(x_1 | \emptyset) = p(x_1)\)</span>.</p>
</section>
<section id="cas-particulier-2-variables" class="level4">
<h4 class="anchored" data-anchor-id="cas-particulier-2-variables">Cas particulier : 2 variables</h4>
<p><span class="math display">\[p(x_1, x_2) = p(x_1) p(x_2 | x_1) = p(x_2) p(x_1 | x_2)\]</span></p>
<p>Cette égalité illustre la symétrie de la règle de chaîne.</p>
</section>
<section id="variables-indépendantes" class="level4">
<h4 class="anchored" data-anchor-id="variables-indépendantes">Variables indépendantes</h4>
<section id="définition-de-lindépendance" class="level5">
<h5 class="anchored" data-anchor-id="définition-de-lindépendance">Définition de l’indépendance</h5>
<p>Deux variables <span class="math inline">\(X_1\)</span> et <span class="math inline">\(X_2\)</span> sont <strong>indépendantes</strong>, noté <span class="math inline">\(X_1 \perp X_2\)</span>, si et seulement si :</p>
<p><span class="math display">\[p(x_1, x_2) = p(x_1) \cdot p(x_2)\]</span></p>
</section>
<section id="conséquence" class="level5">
<h5 class="anchored" data-anchor-id="conséquence">Conséquence</h5>
<p>Pour des variables indépendantes :</p>
<p><span class="math display">\[p(x_2 | x_1) = p(x_2) \quad \text{et} \quad p(x_1 | x_2) = p(x_1)\]</span></p>
</section>
<section id="généralisation-à-n-variables-i.i.d." class="level5">
<h5 class="anchored" data-anchor-id="généralisation-à-n-variables-i.i.d.">Généralisation à N variables i.i.d.</h5>
<p>Pour <span class="math inline">\(N\)</span> variables <strong>identiquement et indépendamment distribuées</strong> (i.i.d.) :</p>
<p><span class="math display">\[p(x_1, x_2, \ldots, x_n) = \prod_{i=1}^{n} p(x_i) = [p(x)]^n\]</span></p>
</section>
</section>
</section>
<section id="exemples-de-décompositions" class="level3">
<h3 class="anchored" data-anchor-id="exemples-de-décompositions">Exemples de Décompositions</h3>
<section id="trois-variables-différentes-structures" class="level4">
<h4 class="anchored" data-anchor-id="trois-variables-différentes-structures">Trois variables : différentes structures</h4>
<section id="chaîne-linéaire" class="level5">
<h5 class="anchored" data-anchor-id="chaîne-linéaire">Chaîne linéaire</h5>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    X --&gt; Y
    Y --&gt; Z
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><span class="math display">\[p(x, y, z) = p(x) \cdot p(y | x) \cdot p(z | y, x)\]</span></p>
<p>Si <span class="math inline">\(X \to Y \to Z\)</span> forme une chaîne de Markov : <span class="math inline">\(p(z | y, x) = p(z | y)\)</span></p>
</section>
<section id="indépendance-complète" class="level5">
<h5 class="anchored" data-anchor-id="indépendance-complète">Indépendance complète</h5>
<p><span class="math display">\[p(x, y, z) = p(x) \cdot p(y) \cdot p(z)\]</span></p>
</section>
<section id="indépendance-conditionnelle-parent-commun" class="level5">
<h5 class="anchored" data-anchor-id="indépendance-conditionnelle-parent-commun">Indépendance conditionnelle (parent commun)</h5>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph TD
    Y --&gt; X
    Y --&gt; Z
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><span class="math display">\[p(x, y, z) = p(y) \cdot p(x | y) \cdot p(z | y)\]</span></p>
<p>Si <span class="math inline">\(X \perp Z | Y\)</span> : <span class="math inline">\(X\)</span> et <span class="math inline">\(Z\)</span> sont conditionnellement indépendants sachant <span class="math inline">\(Y\)</span></p>
</section>
<section id="autres-structures" class="level5">
<h5 class="anchored" data-anchor-id="autres-structures">Autres structures</h5>
<p><strong>Décomposition alternative 1 :</strong> <span class="math display">\[p(x, y, z) = p(z) \cdot p(y | z) \cdot p(x | y, z)\]</span></p>
<p><strong>Décomposition alternative 2 :</strong> <span class="math display">\[p(x, y, z) = p(z | x, y) \cdot p(x) \cdot p(y)\]</span></p>
<p><strong>Décomposition avec indépendance conditionnelle :</strong> <span class="math display">\[p(x, y, z) = p(z) \cdot p(x | z) \cdot p(y | z)\]</span></p>
<p>(si <span class="math inline">\(X \perp Y | Z\)</span>)</p>
</section>
</section>
</section>
</section>
<section id="entropie-mesure-de-lincertitude" class="level2">
<h2 class="anchored" data-anchor-id="entropie-mesure-de-lincertitude">Entropie : Mesure de l’Incertitude</h2>
<section id="entropie-discrète" class="level3">
<h3 class="anchored" data-anchor-id="entropie-discrète">Entropie Discrète</h3>
<section id="définition-formelle" class="level4">
<h4 class="anchored" data-anchor-id="définition-formelle">Définition formelle</h4>
<section id="pour-une-variable-aléatoire-discrète" class="level5">
<h5 class="anchored" data-anchor-id="pour-une-variable-aléatoire-discrète">Pour une variable aléatoire discrète</h5>
<p>Soit <span class="math inline">\(X\)</span> une variable aléatoire discrète prenant ses valeurs dans <span class="math inline">\(\mathcal{X} = \{x_1, x_2, \ldots, x_n\}\)</span> avec une fonction de masse de probabilité <span class="math inline">\(p_X(x)\)</span>.</p>
<p>L’<strong>entropie</strong> de <span class="math inline">\(X\)</span> est définie par :</p>
<p><span class="math display">\[H(X) = -\sum_{x \in \mathcal{X}} p_X(x) \log_2 p_X(x)\]</span></p>
</section>
<section id="forme-espérance" class="level5">
<h5 class="anchored" data-anchor-id="forme-espérance">Forme espérance</h5>
<p><span class="math display">\[H(X) = \mathbb{E}_{p_X}[-\log_2 p_X(X)] = -\mathbb{E}_{p_X}[\log_2 p_X(X)]\]</span></p>
</section>
<section id="convention-importante" class="level5">
<h5 class="anchored" data-anchor-id="convention-importante">Convention importante</h5>
<p>Par convention : <span class="math inline">\(0 \log_2 0 = 0\)</span> (car <span class="math inline">\(\lim_{p \to 0^+} p \log p = 0\)</span>)</p>
</section>
</section>
<section id="interprétations" class="level4">
<h4 class="anchored" data-anchor-id="interprétations">Interprétations</h4>
<section id="interprétation-informationnelle" class="level5">
<h5 class="anchored" data-anchor-id="interprétation-informationnelle">Interprétation informationnelle</h5>
<p>L’entropie mesure :</p>
<ul>
<li>L’<strong>incertitude</strong> moyenne associée à la variable aléatoire <span class="math inline">\(X\)</span></li>
<li>Le <strong>nombre moyen de bits</strong> nécessaires pour encoder de manière optimale les réalisations de <span class="math inline">\(X\)</span></li>
<li>Le <strong>caractère aléatoire</strong> (randomness) de la distribution</li>
</ul>
</section>
<section id="interprétation-en-théorie-du-codage" class="level5">
<h5 class="anchored" data-anchor-id="interprétation-en-théorie-du-codage">Interprétation en théorie du codage</h5>
<p><span class="math inline">\(H(X)\)</span> représente la <strong>longueur moyenne minimale</strong> (en bits) d’un code optimal pour encoder les symboles de <span class="math inline">\(X\)</span>.</p>
</section>
<section id="propriété-clé" class="level5">
<h5 class="anchored" data-anchor-id="propriété-clé">Propriété clé</h5>
<p><span class="math inline">\(H(X)\)</span> dépend <strong>uniquement</strong> de la distribution <span class="math inline">\(p_X(x)\)</span>, pas des valeurs particulières que <span class="math inline">\(X\)</span> peut prendre.</p>
</section>
</section>
<section id="notations-équivalentes" class="level4">
<h4 class="anchored" data-anchor-id="notations-équivalentes">Notations équivalentes</h4>
<p>Les notations suivantes sont interchangeables :</p>
<ul>
<li><span class="math inline">\(H(X)\)</span> : entropie de la variable <span class="math inline">\(X\)</span></li>
<li><span class="math inline">\(H(p)\)</span> : entropie de la distribution <span class="math inline">\(p\)</span></li>
<li><span class="math inline">\(H(p_X)\)</span> ou <span class="math inline">\(H(p(x))\)</span> : entropie de la pmf <span class="math inline">\(p_X(x)\)</span></li>
</ul>
</section>
</section>
<section id="cas-binaire-variable-de-bernoulli" class="level3">
<h3 class="anchored" data-anchor-id="cas-binaire-variable-de-bernoulli">Cas Binaire : Variable de Bernoulli</h3>
<section id="définition" class="level4">
<h4 class="anchored" data-anchor-id="définition">Définition</h4>
<p>Une variable <strong>binaire</strong> <span class="math inline">\(X\)</span> prend ses valeurs dans <span class="math inline">\(\mathcal{X} = \{0, 1\}\)</span> avec :</p>
<p><span class="math display">\[\mathbb{P}[X = 1] = \theta\]</span> <span class="math display">\[\mathbb{P}[X = 0] = 1 - \theta\]</span></p>
<p><strong>Forme compacte :</strong> <span class="math display">\[\mathbb{P}[X = x] = \theta^x (1 - \theta)^{1-x}, \quad x \in \{0, 1\}\]</span></p>
</section>
<section id="formule-de-lentropie-binaire" class="level4">
<h4 class="anchored" data-anchor-id="formule-de-lentropie-binaire">Formule de l’entropie binaire</h4>
<p><span class="math display">\[H(X) = -\theta \log_2 \theta - (1 - \theta) \log_2(1 - \theta)\]</span></p>
<p>On note souvent cette fonction : <span class="math inline">\(H(\theta)\)</span> ou <span class="math inline">\(H_2(\theta)\)</span> (fonction d’entropie binaire).</p>
</section>
<section id="propriétés-de-htheta" class="level4">
<h4 class="anchored" data-anchor-id="propriétés-de-htheta">Propriétés de <span class="math inline">\(H(\theta)\)</span></h4>
<section id="symétrie" class="level5">
<h5 class="anchored" data-anchor-id="symétrie">Symétrie</h5>
<p>La fonction d’entropie binaire est <strong>symétrique</strong> autour de <span class="math inline">\(\theta = 0.5\)</span> :</p>
<p><span class="math display">\[H(\theta) = H(1 - \theta)\]</span></p>
</section>
<section id="maximum" class="level5">
<h5 class="anchored" data-anchor-id="maximum">Maximum</h5>
<p>Le maximum est atteint en <span class="math inline">\(\theta = 0.5\)</span> :</p>
<p><span class="math display">\[\max_{\theta \in [0,1]} H(\theta) = H(0.5) = 1 \text{ bit}\]</span></p>
<p><strong>Principe fondamental :</strong> L’entropie est maximale lorsque les deux symboles sont <strong>équiprobables</strong>.</p>
</section>
<section id="cas-limites" class="level5">
<h5 class="anchored" data-anchor-id="cas-limites">Cas limites</h5>
<ul>
<li><span class="math inline">\(H(0) = H(1) = 0\)</span> : aucune incertitude (variable déterministe)</li>
<li><span class="math inline">\(H(\theta) &gt; 0\)</span> pour <span class="math inline">\(\theta \in (0, 1)\)</span> : présence d’incertitude</li>
</ul>
</section>
</section>
<section id="exemples-numériques" class="level4">
<h4 class="anchored" data-anchor-id="exemples-numériques">Exemples numériques</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(\theta\)</span></th>
<th><span class="math inline">\(H(\theta)\)</span> (bits)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.11</td>
<td>≈ 0.50</td>
</tr>
<tr class="even">
<td>0.25</td>
<td>≈ 0.81</td>
</tr>
<tr class="odd">
<td>0.50</td>
<td>1.00</td>
</tr>
<tr class="even">
<td>0.75</td>
<td>≈ 0.81</td>
</tr>
<tr class="odd">
<td>0.89</td>
<td>≈ 0.50</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="entropies-multivariées" class="level3">
<h3 class="anchored" data-anchor-id="entropies-multivariées">Entropies Multivariées</h3>
<section id="entropie-jointe" class="level4">
<h4 class="anchored" data-anchor-id="entropie-jointe">Entropie Jointe</h4>
<section id="définition-1" class="level5">
<h5 class="anchored" data-anchor-id="définition-1">Définition</h5>
<p>Pour deux variables aléatoires discrètes <span class="math inline">\(X \in \mathcal{X}\)</span> et <span class="math inline">\(Y \in \mathcal{Y}\)</span> :</p>
<p><span class="math display">\[H(X, Y) = -\sum_{x \in \mathcal{X}} \sum_{y \in \mathcal{Y}} p_{X,Y}(x, y) \log_2 p_{X,Y}(x, y)\]</span></p>
</section>
<section id="forme-espérance-1" class="level5">
<h5 class="anchored" data-anchor-id="forme-espérance-1">Forme espérance</h5>
<p><span class="math display">\[H(X, Y) = -\mathbb{E}_{p_{X,Y}}[\log_2 p_{X,Y}(X, Y)]\]</span></p>
</section>
<section id="propriété-de-symétrie" class="level5">
<h5 class="anchored" data-anchor-id="propriété-de-symétrie">Propriété de symétrie</h5>
<p><span class="math display">\[H(X, Y) = H(Y, X)\]</span></p>
</section>
<section id="généralisation-à-n-variables" class="level5">
<h5 class="anchored" data-anchor-id="généralisation-à-n-variables">Généralisation à N variables</h5>
<p><span class="math display">\[H(X_1, \ldots, X_N) = -\sum_{x_1 \in \mathcal{X}_1} \cdots \sum_{x_N \in \mathcal{X}_N} p(x_1, \ldots, x_N) \log_2 p(x_1, \ldots, x_N)\]</span></p>
</section>
</section>
<section id="entropie-conditionnelle" class="level4">
<h4 class="anchored" data-anchor-id="entropie-conditionnelle">Entropie Conditionnelle</h4>
<section id="définition-générale-1" class="level5">
<h5 class="anchored" data-anchor-id="définition-générale-1">Définition générale</h5>
<p>L’entropie de <span class="math inline">\(X\)</span> <strong>sachant</strong> <span class="math inline">\(Y\)</span> est définie par :</p>
<p><span class="math display">\[H(X | Y) = \sum_{y \in \mathcal{Y}} p_Y(y) H(X | Y = y)\]</span></p>
</section>
<section id="forme-développée" class="level5">
<h5 class="anchored" data-anchor-id="forme-développée">Forme développée</h5>
<p><span class="math display">\[H(X | Y) = -\sum_{x \in \mathcal{X}} \sum_{y \in \mathcal{Y}} p_{X,Y}(x, y) \log_2 p_{X|Y}(x | y)\]</span></p>
</section>
<section id="forme-espérance-2" class="level5">
<h5 class="anchored" data-anchor-id="forme-espérance-2">Forme espérance</h5>
<p><span class="math display">\[H(X | Y) = -\mathbb{E}_{p_{X,Y}}[\log_2 p_{X|Y}(X | Y)]\]</span></p>
</section>
<section id="entropie-conditionnelle-pour-une-valeur-fixée" class="level5">
<h5 class="anchored" data-anchor-id="entropie-conditionnelle-pour-une-valeur-fixée">Entropie conditionnelle pour une valeur fixée</h5>
<p>Pour une valeur particulière <span class="math inline">\(Y = y\)</span> :</p>
<p><span class="math display">\[H(X | Y = y) = -\sum_{x \in \mathcal{X}} p_{X|Y}(x | y) \log_2 p_{X|Y}(x | y)\]</span></p>
</section>
<section id="développement-complet" class="level5">
<h5 class="anchored" data-anchor-id="développement-complet">Développement complet</h5>
<p><span class="math display">\[H(X | Y) = -\sum_{y \in \mathcal{Y}} p_Y(y) \left[\sum_{x \in \mathcal{X}} p_{X|Y}(x | y) \log_2 p_{X|Y}(x | y)\right]\]</span></p>
<p><span class="math display">\[= -\sum_{x \in \mathcal{X}} \sum_{y \in \mathcal{Y}} p_{X,Y}(x, y) \log_2 p_{X|Y}(x | y)\]</span></p>
</section>
<section id="asymétrie" class="level5">
<h5 class="anchored" data-anchor-id="asymétrie">Asymétrie</h5>
<p><strong>Attention :</strong> L’entropie conditionnelle n’est <strong>pas symétrique</strong> :</p>
<p><span class="math display">\[H(X | Y) \neq H(Y | X)\]</span></p>
<p>en général.</p>
</section>
</section>
</section>
<section id="propriétés-fondamentales-de-lentropie" class="level3">
<h3 class="anchored" data-anchor-id="propriétés-fondamentales-de-lentropie">Propriétés Fondamentales de l’Entropie</h3>
<section id="non-négativité" class="level4">
<h4 class="anchored" data-anchor-id="non-négativité">Non-négativité</h4>
<section id="énoncé" class="level5">
<h5 class="anchored" data-anchor-id="énoncé">Énoncé</h5>
<p>Pour toute variable aléatoire discrète :</p>
<p><span class="math display">\[H(X) \geq 0\]</span> <span class="math display">\[H(X, Y) \geq 0\]</span> <span class="math display">\[H(X | Y) \geq 0\]</span></p>
</section>
<section id="justification" class="level5">
<h5 class="anchored" data-anchor-id="justification">Justification</h5>
<p>Puisque <span class="math inline">\(0 \leq p_X(x) \leq 1\)</span>, on a <span class="math inline">\(\log_2 p_X(x) \leq 0\)</span>.</p>
<p>Donc : <span class="math inline">\(-p_X(x) \log_2 p_X(x) \geq 0\)</span> pour tout <span class="math inline">\(x\)</span>.</p>
<p>Par conséquent : <span class="math inline">\(H(X) = \sum_x [-p_X(x) \log_2 p_X(x)] \geq 0\)</span>.</p>
<p>Le même raisonnement s’applique à <span class="math inline">\(H(X,Y)\)</span> et <span class="math inline">\(H(X|Y)\)</span>.</p>
</section>
<section id="cas-dégalité" class="level5">
<h5 class="anchored" data-anchor-id="cas-dégalité">Cas d’égalité</h5>
<p><span class="math display">\[H(X) = 0 \quad \Leftrightarrow \quad X \text{ est déterministe}\]</span></p>
<p>C’est-à-dire <span class="math inline">\(\exists x_0 : p_X(x_0) = 1\)</span> et <span class="math inline">\(p_X(x) = 0\)</span> pour <span class="math inline">\(x \neq x_0\)</span>.</p>
</section>
</section>
<section id="règle-de-chaîne-pour-lentropie" class="level4">
<h4 class="anchored" data-anchor-id="règle-de-chaîne-pour-lentropie">Règle de Chaîne pour l’Entropie</h4>
<section id="cas-de-2-variables" class="level5">
<h5 class="anchored" data-anchor-id="cas-de-2-variables">Cas de 2 variables</h5>
<p>En utilisant la règle de chaîne des probabilités : <span class="math display">\[p(x, y) = p(x | y) p(y) = p(y | x) p(x)\]</span></p>
<p>On obtient :</p>
<p><span class="math display">\[H(X, Y) = H(X) + H(Y | X) = H(Y) + H(X | Y)\]</span></p>
</section>
<section id="démonstration" class="level5">
<h5 class="anchored" data-anchor-id="démonstration">Démonstration</h5>
<p><span class="math display">\[-\log_2 p_{X,Y}(x, y) = -\log_2[p_{Y|X}(y | x) p_X(x)]\]</span> <span class="math display">\[= -\log_2 p_{Y|X}(y | x) - \log_2 p_X(x)\]</span></p>
<p>En prenant l’espérance :</p>
<p><span class="math display">\[H(X, Y) = \mathbb{E}_{p_{X,Y}}[-\log_2 p_{X,Y}(X, Y)]\]</span> <span class="math display">\[= \mathbb{E}_{p_{X,Y}}[-\log_2 p_X(X)] + \mathbb{E}_{p_{X,Y}}[-\log_2 p_{Y|X}(Y | X)]\]</span> <span class="math display">\[= H(X) + H(Y | X)\]</span></p>
</section>
<section id="cas-général-de-n-variables" class="level5">
<h5 class="anchored" data-anchor-id="cas-général-de-n-variables">Cas général de N variables</h5>
<p>Pour la distribution jointe : <span class="math display">\[p(x_1, \ldots, x_N) = p(x_1) \prod_{i=2}^{N} p(x_i | x_{i-1}, \ldots, x_1)\]</span></p>
<p>On a :</p>
<p><span class="math display">\[H(X_1, X_2, \ldots, X_N) = \sum_{i=1}^{N} H(X_i | X_{i-1}, \ldots, X_1)\]</span></p>
<p>avec la convention <span class="math inline">\(H(X_1 | \emptyset) = H(X_1)\)</span>.</p>
</section>
<section id="conséquence-pour-variables-indépendantes" class="level5">
<h5 class="anchored" data-anchor-id="conséquence-pour-variables-indépendantes">Conséquence pour variables indépendantes</h5>
<p>Si <span class="math inline">\(X\)</span> et <span class="math inline">\(Y\)</span> sont indépendantes (<span class="math inline">\(X \perp Y\)</span>), alors <span class="math inline">\(H(Y|X) = H(Y)\)</span>, et donc :</p>
<p><span class="math display">\[H(X, Y) = H(X) + H(Y)\]</span></p>
<p>Plus généralement :</p>
<p><span class="math display">\[H(X, Y) \leq H(X) + H(Y)\]</span></p>
<p>avec égalité si et seulement si <span class="math inline">\(X \perp Y\)</span>.</p>
</section>
</section>
<section id="augmentation-de-lentropie-par-ajout-de-variables" class="level4">
<h4 class="anchored" data-anchor-id="augmentation-de-lentropie-par-ajout-de-variables">Augmentation de l’Entropie par Ajout de Variables</h4>
<section id="principe" class="level5">
<h5 class="anchored" data-anchor-id="principe">Principe</h5>
<p>Ajouter une nouvelle variable aléatoire <strong>augmente</strong> (ou laisse inchangée) l’entropie jointe :</p>
<p><span class="math display">\[H(X) \leq H(X, Y) \leq H(X, Y, Z) \leq \cdots\]</span></p>
</section>
<section id="conditions-dégalité" class="level5">
<h5 class="anchored" data-anchor-id="conditions-dégalité">Conditions d’égalité</h5>
<p><span class="math display">\[H(X) = H(X, Y) \quad \Leftrightarrow \quad Y = f(X)\]</span></p>
<p>où <span class="math inline">\(f\)</span> est une fonction déterministe (i.e., <span class="math inline">\(Y\)</span> est complètement déterminé par <span class="math inline">\(X\)</span>).</p>
<p><span class="math display">\[H(X, Y) = H(X, Y, Z) \quad \Leftrightarrow \quad Z = g(X, Y)\]</span></p>
<p>où <span class="math inline">\(g\)</span> est une fonction déterministe.</p>
</section>
<section id="justification-1" class="level5">
<h5 class="anchored" data-anchor-id="justification-1">Justification</h5>
<p>En utilisant la règle de chaîne :</p>
<p><span class="math display">\[H(X, Y) = H(X) + H(Y | X)\]</span></p>
<p>Puisque <span class="math inline">\(H(Y | X) \geq 0\)</span>, on a <span class="math inline">\(H(X, Y) \geq H(X)\)</span>.</p>
<p>L’égalité est atteinte si et seulement si <span class="math inline">\(H(Y | X) = 0\)</span>, ce qui signifie que <span class="math inline">\(Y\)</span> est déterministement déterminé par <span class="math inline">\(X\)</span>.</p>
</section>
</section>
<section id="conditionnement-réduit-lentropie" class="level4">
<h4 class="anchored" data-anchor-id="conditionnement-réduit-lentropie">Conditionnement Réduit l’Entropie</h4>
<section id="principe-fondamental" class="level5">
<h5 class="anchored" data-anchor-id="principe-fondamental">Principe fondamental</h5>
<p>Le conditionnement <strong>réduit</strong> (ou laisse inchangée) l’entropie :</p>
<p><span class="math display">\[H(X) \geq H(X | Y) \geq H(X | Y, Z) \geq \cdots\]</span></p>
</section>
<section id="interprétation-intuitive" class="level5">
<h5 class="anchored" data-anchor-id="interprétation-intuitive">Interprétation intuitive</h5>
<p>Connaître <span class="math inline">\(Y\)</span> ne peut que <strong>réduire l’incertitude</strong> sur <span class="math inline">\(X\)</span> (ou la laisser inchangée si <span class="math inline">\(X\)</span> et <span class="math inline">\(Y\)</span> sont indépendants).</p>
</section>
<section id="conditions-dégalité-1" class="level5">
<h5 class="anchored" data-anchor-id="conditions-dégalité-1">Conditions d’égalité</h5>
<p><span class="math display">\[H(X) = H(X | Y) \quad \Leftrightarrow \quad X \perp Y\]</span></p>
<p>(<span class="math inline">\(X\)</span> et <span class="math inline">\(Y\)</span> sont indépendants)</p>
<p><span class="math display">\[H(X | Y) = H(X | Y, Z) \quad \Leftrightarrow \quad X \perp Z | Y\]</span></p>
<p>(<span class="math inline">\(X\)</span> et <span class="math inline">\(Z\)</span> sont conditionnellement indépendants sachant <span class="math inline">\(Y\)</span>)</p>
</section>
<section id="démonstration-1" class="level5">
<h5 class="anchored" data-anchor-id="démonstration-1">Démonstration</h5>
<p>En utilisant la règle de chaîne :</p>
<p><span class="math display">\[H(X, Y) = H(X) + H(Y | X) = H(Y) + H(X | Y)\]</span></p>
<p>Donc :</p>
<p><span class="math display">\[H(X) - H(X | Y) = H(Y) - H(Y | X) = I(X; Y)\]</span></p>
<p>Puisque <span class="math inline">\(I(X; Y) \geq 0\)</span> (voir section sur l’information mutuelle), on a :</p>
<p><span class="math display">\[H(X) \geq H(X | Y)\]</span></p>
</section>
</section>
<section id="entropie-maximale" class="level4">
<h4 class="anchored" data-anchor-id="entropie-maximale">Entropie Maximale</h4>
<section id="théorème" class="level5">
<h5 class="anchored" data-anchor-id="théorème">Théorème</h5>
<p>Pour une variable aléatoire discrète <span class="math inline">\(X\)</span> prenant ses valeurs dans un ensemble <span class="math inline">\(\mathcal{X}\)</span> de cardinalité <span class="math inline">\(|\mathcal{X}| = N\)</span> :</p>
<p><span class="math display">\[H(X) \leq \log_2 N\]</span></p>
</section>
<section id="condition-dégalité" class="level5">
<h5 class="anchored" data-anchor-id="condition-dégalité">Condition d’égalité</h5>
<p>L’égalité est atteinte si et seulement si <span class="math inline">\(X\)</span> suit une <strong>distribution uniforme</strong> :</p>
<p><span class="math display">\[p_X(x) = \frac{1}{N} = \frac{1}{|\mathcal{X}|}, \quad \forall x \in \mathcal{X}\]</span></p>
</section>
<section id="principe-1" class="level5">
<h5 class="anchored" data-anchor-id="principe-1">Principe</h5>
<p>Parmi toutes les distributions sur un ensemble fini, la distribution <strong>uniforme</strong> maximise l’entropie.</p>
</section>
<section id="esquisse-de-démonstration" class="level5">
<h5 class="anchored" data-anchor-id="esquisse-de-démonstration">Esquisse de démonstration</h5>
<p>Soit <span class="math inline">\(\mathcal{X} = \{x_1, x_2, \ldots, x_N\}\)</span> et <span class="math inline">\(p_i = \mathbb{P}[X = x_i]\)</span>.</p>
<p><strong>Objectif :</strong> Maximiser <span class="math inline">\(H(X) = -\sum_{i=1}^N p_i \log_2 p_i\)</span> sous la contrainte <span class="math inline">\(\sum_{i=1}^N p_i = 1\)</span> et <span class="math inline">\(p_i \geq 0\)</span>.</p>
<p>En utilisant les multiplicateurs de Lagrange, on montre que l’optimum est atteint pour <span class="math inline">\(p_i = 1/N\)</span> pour tout <span class="math inline">\(i\)</span>.</p>
<p><strong>Valeur maximale :</strong> <span class="math display">\[H_{\max} = -\sum_{i=1}^N \frac{1}{N} \log_2 \frac{1}{N} = \log_2 N\]</span></p>
</section>
</section>
</section>
<section id="application-aux-vecteurs-dimages" class="level3">
<h3 class="anchored" data-anchor-id="application-aux-vecteurs-dimages">Application aux Vecteurs d’Images</h3>
<section id="représentation-vectorielle" class="level4">
<h4 class="anchored" data-anchor-id="représentation-vectorielle">Représentation vectorielle</h4>
<p>Une image peut être représentée comme un vecteur de pixels :</p>
<p><span class="math display">\[X = \begin{pmatrix} X_1 \\ X_2 \\ \vdots \\ X_N \end{pmatrix} \in \mathcal{X}^N\]</span></p>
<p>où <span class="math inline">\(N = n \times m\)</span> est le nombre total de pixels.</p>
</section>
<section id="modèle-dindépendance" class="level4">
<h4 class="anchored" data-anchor-id="modèle-dindépendance">Modèle d’indépendance</h4>
<p>Si on suppose les pixels <strong>indépendants</strong> :</p>
<p><span class="math display">\[p(x_1, x_2, \ldots, x_N) = \prod_{i=1}^{N} p(x_i)\]</span></p>
<p>Alors :</p>
<p><span class="math display">\[H(X_1, X_2, \ldots, X_N) = \sum_{i=1}^{N} H(X_i)\]</span></p>
<p><strong>Limitation :</strong> Cette hypothèse est <strong>irréaliste</strong> car les pixels voisins sont généralement corrélés.</p>
</section>
<section id="modèle-de-markov" class="level4">
<h4 class="anchored" data-anchor-id="modèle-de-markov">Modèle de Markov</h4>
<p>Un modèle plus réaliste est une chaîne de Markov d’ordre <span class="math inline">\(k\)</span> (par exemple, <span class="math inline">\(k=2\)</span>) :</p>
<p><span class="math display">\[p(x_i | x_{i-1}, x_{i-2}, \ldots, x_1) = p(x_i | x_{i-1}, x_{i-2})\]</span></p>
<p><strong>Entropie totale :</strong></p>
<p><span class="math display">\[H(X_1, X_2, \ldots, X_N) = \sum_{i=1}^{N} H(X_i | X_{i-1}, \ldots, X_1)\]</span></p>
<p>Pour un modèle de Markov d’ordre 2 :</p>
<p><span class="math display">\[H(X_1, X_2, \ldots, X_N) = H(X_1) + H(X_2 | X_1) + \sum_{i=3}^{N} H(X_i | X_{i-1}, X_{i-2})\]</span></p>
</section>
</section>
</section>
<section id="applications-au-codage-et-à-la-compression" class="level2">
<h2 class="anchored" data-anchor-id="applications-au-codage-et-à-la-compression">Applications au Codage et à la Compression</h2>
<section id="concepts-fondamentaux-du-codage" class="level3">
<h3 class="anchored" data-anchor-id="concepts-fondamentaux-du-codage">Concepts Fondamentaux du Codage</h3>
<section id="schéma-de-compression" class="level4">
<h4 class="anchored" data-anchor-id="schéma-de-compression">Schéma de compression</h4>
<section id="compression-sans-perte-lossless" class="level5">
<h5 class="anchored" data-anchor-id="compression-sans-perte-lossless">Compression sans perte (Lossless)</h5>
<p><span class="math display">\[X \xrightarrow{\text{Encodeur}} R \xrightarrow{\text{Décodeur}} \hat{X}\]</span></p>
<p><strong>Propriété :</strong></p>
<p><span class="math display">\[\hat{X} = X \quad \Rightarrow \quad D = \mathbb{E}[\|X - \hat{X}\|^2] = 0\]</span></p>
<p>La reconstruction est <strong>parfaite</strong>.</p>
</section>
<section id="compression-avec-perte-lossy" class="level5">
<h5 class="anchored" data-anchor-id="compression-avec-perte-lossy">Compression avec perte (Lossy)</h5>
<p><span class="math display">\[X \xrightarrow{\text{Encodeur}} R \xrightarrow{\text{Décodeur}} \hat{X}\]</span></p>
<p><strong>Propriété :</strong></p>
<p><span class="math display">\[\hat{X} \neq X \quad \Rightarrow \quad D = \mathbb{E}[\|X - \hat{X}\|^2] &gt; 0\]</span></p>
<p>On accepte une <strong>distorsion</strong> pour un meilleur taux de compression.</p>
</section>
</section>
<section id="taux-de-compression" class="level4">
<h4 class="anchored" data-anchor-id="taux-de-compression">Taux de compression</h4>
<section id="définition-2" class="level5">
<h5 class="anchored" data-anchor-id="définition-2">Définition</h5>
<p>Le <strong>ratio de compression</strong> (Compression Ratio) est défini par :</p>
<p><span class="math display">\[CR = \frac{\text{Taille originale (en bits)}}{\text{Taille compressée (en bits)}}\]</span></p>
<p>Un <span class="math inline">\(CR &gt; 1\)</span> indique une compression effective.</p>
</section>
<section id="exemples-de-taux-réels" class="level5">
<h5 class="anchored" data-anchor-id="exemples-de-taux-réels">Exemples de taux réels</h5>
<p><strong>Pour images réelles :</strong></p>
<ul>
<li><strong>Compression sans perte</strong> : <span class="math inline">\(CR \approx 2\)</span> (PNG, FLAC)</li>
<li><strong>Compression avec perte</strong> :
<ul>
<li><strong>JPEG</strong> : <span class="math inline">\(CR = 10\)</span> à <span class="math inline">\(50\)</span></li>
<li><strong>JPEG 2000</strong> : <span class="math inline">\(CR\)</span> jusqu’à <span class="math inline">\(150\)</span></li>
<li><strong>Codecs vidéo modernes</strong> : <span class="math inline">\(CR &gt; 100\)</span></li>
</ul></li>
</ul>
</section>
</section>
</section>
<section id="assignation-optimale-de-codes" class="level3">
<h3 class="anchored" data-anchor-id="assignation-optimale-de-codes">Assignation Optimale de Codes</h3>
<section id="principe-de-base" class="level4">
<h4 class="anchored" data-anchor-id="principe-de-base">Principe de base</h4>
<section id="histogramme-et-modèle" class="level5">
<h5 class="anchored" data-anchor-id="histogramme-et-modèle">Histogramme et modèle</h5>
<p>Pour une image représentée par <span class="math inline">\(N\)</span> pixels :</p>
<p><span class="math display">\[p_i = \mathbb{P}\{X(i, j) = k\} = \frac{\text{Nombre de pixels d'intensité } k}{N}\]</span></p>
<p><strong>Hypothèse simplificatrice</strong> (souvent irréaliste) : les pixels sont <strong>discrets</strong> et <strong>indépendants</strong>.</p>
</section>
<section id="lien-avec-lentropie" class="level5">
<h5 class="anchored" data-anchor-id="lien-avec-lentropie">Lien avec l’entropie</h5>
<p>Pour des symboles discrets et indépendants :</p>
<p><span class="math display">\[H(X) = -\sum_{i=0}^{L-1} p_i \log_2 p_i = \ell_{\text{av}}\]</span></p>
<p>où <span class="math inline">\(\ell_{\text{av}}\)</span> est la <strong>longueur moyenne minimale</strong> de code (en bits par symbole).</p>
</section>
</section>
<section id="longueur-de-code-optimale" class="level4">
<h4 class="anchored" data-anchor-id="longueur-de-code-optimale">Longueur de code optimale</h4>
<section id="relation-probabilité-longueur" class="level5">
<h5 class="anchored" data-anchor-id="relation-probabilité-longueur">Relation probabilité-longueur</h5>
<p>Pour encoder optimalement un symbole de probabilité <span class="math inline">\(p_i\)</span>, la longueur de code optimale est :</p>
<p><span class="math display">\[\ell_i \approx -\log_2 p_i = \log_2 \frac{1}{p_i}\]</span></p>
<p>Cette relation découle du théorème de codage de source de Shannon.</p>
</section>
<section id="exemples-numériques-1" class="level5">
<h5 class="anchored" data-anchor-id="exemples-numériques-1">Exemples numériques</h5>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Probabilité <span class="math inline">\(p_i\)</span></th>
<th><span class="math inline">\(\ell_i\)</span> (bits)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(0.5 = 2^{-1}\)</span></td>
<td><span class="math inline">\(\log_2 2 = 1\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(0.25 = 2^{-2}\)</span></td>
<td><span class="math inline">\(\log_2 4 = 2\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(0.125 = 2^{-3}\)</span></td>
<td><span class="math inline">\(\log_2 8 = 3\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(0.0625 = 2^{-4}\)</span></td>
<td><span class="math inline">\(\log_2 16 = 4\)</span></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="codage-à-longueur-variable" class="level4">
<h4 class="anchored" data-anchor-id="codage-à-longueur-variable">Codage à longueur variable</h4>
<section id="principe-fondamental-1" class="level5">
<h5 class="anchored" data-anchor-id="principe-fondamental-1">Principe fondamental</h5>
<p>Pour minimiser la longueur moyenne du code :</p>
<ul>
<li>Les symboles <strong>plus fréquents</strong> reçoivent des codes <strong>plus courts</strong></li>
<li>Les symboles <strong>moins fréquents</strong> reçoivent des codes <strong>plus longs</strong></li>
</ul>
<p>Ce principe est à la base du <strong>codage à longueur variable</strong> (Variable Length Coding).</p>
</section>
<section id="longueur-moyenne" class="level5">
<h5 class="anchored" data-anchor-id="longueur-moyenne">Longueur moyenne</h5>
<p>Pour un code optimal :</p>
<p><span class="math display">\[\ell_{\text{av}} = \sum_{i=0}^{L-1} p_i \ell_i \approx H(X)\]</span></p>
<p>Plus précisément, le théorème de Shannon garantit :</p>
<p><span class="math display">\[H(X) \leq \ell_{\text{av}} &lt; H(X) + 1\]</span></p>
</section>
</section>
</section>
<section id="codage-de-huffman" class="level3">
<h3 class="anchored" data-anchor-id="codage-de-huffman">Codage de Huffman</h3>
<section id="principe-général" class="level4">
<h4 class="anchored" data-anchor-id="principe-général">Principe général</h4>
<section id="objectif" class="level5">
<h5 class="anchored" data-anchor-id="objectif">Objectif</h5>
<p>Concevoir un <strong>code préfixe</strong> qui approche l’entropie de la source, c’est-à-dire un code de longueur moyenne minimale.</p>
</section>
<section id="optimalité" class="level5">
<h5 class="anchored" data-anchor-id="optimalité">Optimalité</h5>
<p>Le codage de Huffman est un code <strong>optimal</strong> pour l’encodage symbole par symbole de sources discrètes.</p>
</section>
</section>
<section id="hypothèses" class="level4">
<h4 class="anchored" data-anchor-id="hypothèses">Hypothèses</h4>
<p>Le codage de Huffman repose sur les hypothèses suivantes :</p>
<ol type="1">
<li><strong>Indépendance</strong> : tous les symboles sont indépendants (hypothèse simplificatrice)</li>
<li><strong>Symbole par symbole</strong> : encodage individuel de chaque symbole</li>
<li><strong>Connaissance de la distribution</strong> : la pmf <span class="math inline">\(p(x)\)</span> est connue (peut être estimée par l’histogramme)</li>
</ol>
</section>
<section id="algorithme-de-construction" class="level4">
<h4 class="anchored" data-anchor-id="algorithme-de-construction">Algorithme de construction</h4>
<section id="étapes-de-lalgorithme" class="level5">
<h5 class="anchored" data-anchor-id="étapes-de-lalgorithme">Étapes de l’algorithme</h5>
<p><strong>Étape 1 : Initialisation</strong> Arranger les symboles par <strong>probabilité décroissante</strong>. Considérer chaque symbole comme un nœud feuille.</p>
<p><strong>Étape 2 : Fusion itérative</strong> Répéter jusqu’à obtenir un seul nœud racine : - Sélectionner les deux nœuds de <strong>plus faible probabilité</strong> - Les fusionner en un nouveau nœud de probabilité égale à leur somme</p>
<p><strong>Étape 3 : Assignation des codes</strong> Assigner le bit <strong>0</strong> à la branche supérieure et <strong>1</strong> à la branche inférieure (ou l’inverse)</p>
<p><strong>Étape 4 : Lecture des codes</strong> Lire le code de chaque symbole en parcourant le chemin de la <strong>racine à la feuille</strong></p>
</section>
</section>
<section id="exemple-détaillé" class="level4">
<h4 class="anchored" data-anchor-id="exemple-détaillé">Exemple détaillé</h4>
<section id="données" class="level5">
<h5 class="anchored" data-anchor-id="données">Données</h5>
<p>Considérons 8 symboles avec les probabilités suivantes :</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Symbole</th>
<th>Probabilité</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.25</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.21</td>
</tr>
<tr class="odd">
<td>0</td>
<td>0.19</td>
</tr>
<tr class="even">
<td>3</td>
<td>0.16</td>
</tr>
<tr class="odd">
<td>4</td>
<td>0.08</td>
</tr>
<tr class="even">
<td>5</td>
<td>0.06</td>
</tr>
<tr class="odd">
<td>6</td>
<td>0.03</td>
</tr>
<tr class="even">
<td>7</td>
<td>0.02</td>
</tr>
</tbody>
</table>
<p>Vérification : <span class="math inline">\(\sum p_i = 1.00\)</span> ✓</p>
</section>
<section id="construction-de-larbre" class="level5">
<h5 class="anchored" data-anchor-id="construction-de-larbre">Construction de l’arbre</h5>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph TD
    A[1.00] --&gt;|1| B[0.60]
    A --&gt;|0| C[0.40]
    B --&gt;|1| D[0.35]
    B --&gt;|0| E[0.25: Symbole 1]
    C --&gt;|1| F[0.21: Symbole 2]
    C --&gt;|0| G[0.19: Symbole 0]
    D --&gt;|1| H[0.19]
    D --&gt;|0| I[0.16: Symbole 3]
    H --&gt;|1| J[0.11]
    H --&gt;|0| K[0.08: Symbole 4]
    J --&gt;|1| L[0.05]
    J --&gt;|0| M[0.06: Symbole 5]
    L --&gt;|1| N[0.03: Symbole 6]
    L --&gt;|0| O[0.02: Symbole 7]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="codes-résultants" class="level5">
<h5 class="anchored" data-anchor-id="codes-résultants">Codes résultants</h5>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Symbole</th>
<th>Probabilité</th>
<th>Code Huffman</th>
<th>Longueur</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.25</td>
<td>10</td>
<td>2</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.21</td>
<td>01</td>
<td>2</td>
</tr>
<tr class="odd">
<td>0</td>
<td>0.19</td>
<td>00</td>
<td>2</td>
</tr>
<tr class="even">
<td>3</td>
<td>0.16</td>
<td>110</td>
<td>3</td>
</tr>
<tr class="odd">
<td>4</td>
<td>0.08</td>
<td>1110</td>
<td>4</td>
</tr>
<tr class="even">
<td>5</td>
<td>0.06</td>
<td>11110</td>
<td>5</td>
</tr>
<tr class="odd">
<td>6</td>
<td>0.03</td>
<td>111111</td>
<td>6</td>
</tr>
<tr class="even">
<td>7</td>
<td>0.02</td>
<td>111110</td>
<td>6</td>
</tr>
</tbody>
</table>
<p><strong>Propriété observée :</strong> Les symboles avec la <strong>plus haute probabilité</strong> ont la <strong>longueur la plus courte</strong>.</p>
</section>
<section id="calculs-de-performances" class="level5">
<h5 class="anchored" data-anchor-id="calculs-de-performances">Calculs de performances</h5>
<p><strong>Entropie de la source :</strong> <span class="math display">\[H = -\sum_{i=0}^{7} p_i \log_2 p_i = 2.6508 \text{ bits/symbole}\]</span></p>
<p><strong>Longueur moyenne (code Huffman) :</strong> <span class="math display">\[\ell_{\text{av}} = \sum_{i=0}^{7} p_i \ell_i = 2.7000 \text{ bits/symbole}\]</span></p>
<p><strong>Efficacité :</strong> <span class="math display">\[\eta = \frac{H}{\ell_{\text{av}}} = \frac{2.6508}{2.7000} \approx 0.982 = 98.2\%\]</span></p>
</section>
</section>
</section>
<section id="codes-préfixes" class="level3">
<h3 class="anchored" data-anchor-id="codes-préfixes">Codes Préfixes</h3>
<section id="définition-3" class="level4">
<h4 class="anchored" data-anchor-id="définition-3">Définition</h4>
<p>Un <strong>code préfixe</strong> (prefix code ou prefix-free code) est un code tel qu’<strong>aucun code n’est le préfixe d’un autre code</strong>.</p>
<p><strong>Formellement :</strong> Pour tous codes distincts <span class="math inline">\(c_i\)</span> et <span class="math inline">\(c_j\)</span>, <span class="math inline">\(c_i\)</span> n’est pas un préfixe de <span class="math inline">\(c_j\)</span>.</p>
</section>
<section id="importance" class="level4">
<h4 class="anchored" data-anchor-id="importance">Importance</h4>
<section id="décodage-unique" class="level5">
<h5 class="anchored" data-anchor-id="décodage-unique">Décodage unique</h5>
<p>Un code préfixe garantit un <strong>décodage unique</strong> sans ambiguïté :</p>
<ul>
<li>Pas besoin de délimiteurs entre les codes</li>
<li>Pas besoin de voir le symbole suivant pour décoder</li>
<li>Le décodage peut être effectué <strong>instantanément</strong> (symbole par symbole)</li>
</ul>
</section>
<section id="propriété-de-kraft-mcmillan" class="level5">
<h5 class="anchored" data-anchor-id="propriété-de-kraft-mcmillan">Propriété de Kraft-McMillan</h5>
<p>Pour qu’un code préfixe existe avec des longueurs <span class="math inline">\(\{\ell_1, \ldots, \ell_n\}\)</span>, il faut et il suffit que :</p>
<p><span class="math display">\[\sum_{i=1}^{n} 2^{-\ell_i} \leq 1\]</span></p>
<p>Cette condition est appelée <strong>inégalité de Kraft</strong>.</p>
</section>
</section>
<section id="exemple-comparatif" class="level4">
<h4 class="anchored" data-anchor-id="exemple-comparatif">Exemple comparatif</h4>
<section id="code-a-non-préfixe" class="level5">
<h5 class="anchored" data-anchor-id="code-a-non-préfixe">Code A (NON préfixe)</h5>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Symbole</th>
<th>Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>2</td>
<td>00</td>
</tr>
<tr class="odd">
<td>3</td>
<td>11</td>
</tr>
<tr class="even">
<td>4</td>
<td>110</td>
</tr>
</tbody>
</table>
<p><strong>Problème :</strong> Le code “1” est un préfixe de “11” et “110”</p>
</section>
<section id="code-b-préfixe" class="level5">
<h5 class="anchored" data-anchor-id="code-b-préfixe">Code B (Préfixe)</h5>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Symbole</th>
<th>Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td>2</td>
<td>10</td>
</tr>
<tr class="odd">
<td>3</td>
<td>110</td>
</tr>
<tr class="even">
<td>4</td>
<td>111</td>
</tr>
</tbody>
</table>
<p><strong>Propriété :</strong> Aucun code n’est le préfixe d’un autre ✓</p>
</section>
<section id="test-de-décodage-séquence-1234321" class="level5">
<h5 class="anchored" data-anchor-id="test-de-décodage-séquence-1234321">Test de décodage : séquence “1234321”</h5>
<p><strong>Code A (NON préfixe) :</strong> - Encodage : <code>100011110110010</code> ou <code>1|00|00|110|...</code> ? - <strong>Problème</strong> : Ambiguïté de décodage ✗</p>
<p><strong>Code B (Préfixe) :</strong> - Encodage : <code>010110111110100</code> - Décodage : <code>0|10|110|111|110|10|0</code> = <code>1234321</code> - <strong>Décodage unique</strong> ✓</p>
</section>
</section>
</section>
<section id="exemple-complet-image-à-8-niveaux" class="level3">
<h3 class="anchored" data-anchor-id="exemple-complet-image-à-8-niveaux">Exemple Complet : Image à 8 Niveaux</h3>
<section id="configuration" class="level4">
<h4 class="anchored" data-anchor-id="configuration">Configuration</h4>
<p>Une image utilise 8 niveaux de gris (3 bits en codage fixe).</p>
</section>
<section id="table-de-codage" class="level4">
<h4 class="anchored" data-anchor-id="table-de-codage">Table de codage</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Niveau</th>
<th>Probabilité</th>
<th>Code fixe</th>
<th>Code Huffman</th>
<th>Longueur</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0.19</td>
<td>000</td>
<td>00</td>
<td>2</td>
</tr>
<tr class="even">
<td>1</td>
<td>0.25</td>
<td>001</td>
<td>10</td>
<td>2</td>
</tr>
<tr class="odd">
<td>2</td>
<td>0.21</td>
<td>010</td>
<td>01</td>
<td>2</td>
</tr>
<tr class="even">
<td>3</td>
<td>0.16</td>
<td>011</td>
<td>110</td>
<td>3</td>
</tr>
<tr class="odd">
<td>4</td>
<td>0.08</td>
<td>100</td>
<td>1110</td>
<td>4</td>
</tr>
<tr class="even">
<td>5</td>
<td>0.06</td>
<td>101</td>
<td>11110</td>
<td>5</td>
</tr>
<tr class="odd">
<td>6</td>
<td>0.03</td>
<td>110</td>
<td>111111</td>
<td>6</td>
</tr>
<tr class="even">
<td>7</td>
<td>0.02</td>
<td>111</td>
<td>111110</td>
<td>6</td>
</tr>
</tbody>
</table>
</section>
<section id="analyse-des-performances" class="level4">
<h4 class="anchored" data-anchor-id="analyse-des-performances">Analyse des performances</h4>
<section id="entropie-de-la-source" class="level5">
<h5 class="anchored" data-anchor-id="entropie-de-la-source">Entropie de la source</h5>
<p><span class="math display">\[H = -\sum_{i=0}^{7} p_i \log_2 p_i = 2.6508 \text{ bits}\]</span></p>
</section>
<section id="longueur-moyenne-code-fixe" class="level5">
<h5 class="anchored" data-anchor-id="longueur-moyenne-code-fixe">Longueur moyenne : code fixe</h5>
<p><span class="math display">\[\ell_{\text{av}}^{\text{fixe}} = 3 \text{ bits}\]</span></p>
<p>(tous les symboles utilisent 3 bits)</p>
</section>
<section id="longueur-moyenne-code-variable" class="level5">
<h5 class="anchored" data-anchor-id="longueur-moyenne-code-variable">Longueur moyenne : code variable</h5>
<p><span class="math display">\[\ell_{\text{av}}^{\text{var}} = \sum_{i=0}^{7} p_i \ell_i = 2.7000 \text{ bits}\]</span></p>
</section>
<section id="comparaison" class="level5">
<h5 class="anchored" data-anchor-id="comparaison">Comparaison</h5>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Métrique</th>
<th>Code fixe</th>
<th>Code Huffman</th>
<th>Entropie</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Longueur moyenne</td>
<td>3.00</td>
<td>2.70</td>
<td>2.65</td>
</tr>
<tr class="even">
<td>Efficacité</td>
<td>88.4%</td>
<td>98.2%</td>
<td>100%</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="impact-pratique" class="level4">
<h4 class="anchored" data-anchor-id="impact-pratique">Impact pratique</h4>
<section id="gain-pour-une-grande-image" class="level5">
<h5 class="anchored" data-anchor-id="gain-pour-une-grande-image">Gain pour une grande image</h5>
<p>Pour une image de <span class="math inline">\(1000 \times 1000 = 10^6\)</span> pixels :</p>
<p><strong>Différence par pixel :</strong> <span class="math display">\[\Delta = 3.00 - 2.70 = 0.30 \text{ bits}\]</span></p>
<p><strong>Gain total :</strong> <span class="math display">\[\text{Gain} = 10^6 \times 0.30 = 3 \times 10^5 \text{ bits} = 37.5 \text{ Ko}\]</span></p>
</section>
<section id="par-rapport-à-lentropie" class="level5">
<h5 class="anchored" data-anchor-id="par-rapport-à-lentropie">Par rapport à l’entropie</h5>
<p><strong>Différence entre code fixe et entropie :</strong> <span class="math display">\[\Delta = 3.00 - 2.65 = 0.35 \text{ bits/pixel}\]</span></p>
<p><strong>Gain théorique maximal :</strong> <span class="math display">\[\text{Gain max} = 10^6 \times 0.35 = 3.5 \times 10^5 \text{ bits} \approx 42.7 \text{ Ko}\]</span></p>
</section>
</section>
</section>
<section id="complexité-et-limitations" class="level3">
<h3 class="anchored" data-anchor-id="complexité-et-limitations">Complexité et Limitations</h3>
<section id="complexité-de-compression-pour-images" class="level4">
<h4 class="anchored" data-anchor-id="complexité-de-compression-pour-images">Complexité de compression pour images</h4>
<section id="problématique-générale" class="level5">
<h5 class="anchored" data-anchor-id="problématique-générale">Problématique générale</h5>
<p>Une image <span class="math inline">\(X\)</span> peut être vue comme un vecteur :</p>
<p><span class="math display">\[X \sim p_X(x) = p_X(x_1, x_2, \ldots, x_N)\]</span></p>
<p>où <span class="math inline">\(N\)</span> est le nombre de pixels.</p>
</section>
<section id="défis-pratiques" class="level5">
<h5 class="anchored" data-anchor-id="défis-pratiques">Défis pratiques</h5>
<ol type="1">
<li><strong>Modélisation complexe</strong> : la distribution jointe <span class="math inline">\(p_X(x_1, \ldots, x_N)\)</span> est en dimension très élevée</li>
<li><strong>Distribution inconnue</strong> : la vraie distribution est généralement inconnue</li>
<li><strong>Hypothèse d’indépendance</strong> : simplifier en supposant les pixels indépendants <strong>augmente l’entropie</strong> (sous-optimal)</li>
<li><strong>Corrélations spatiales</strong> : les pixels voisins sont corrélés, ce qui contredit l’hypothèse d’indépendance</li>
</ol>
</section>
</section>
<section id="théorie-de-shannon-codage-par-blocs" class="level4">
<h4 class="anchored" data-anchor-id="théorie-de-shannon-codage-par-blocs">Théorie de Shannon : codage par blocs</h4>
<section id="codage-optimal" class="level5">
<h5 class="anchored" data-anchor-id="codage-optimal">Codage optimal</h5>
<p>La théorie <strong>rate-distortion</strong> de Shannon suggère un <strong>codage par blocs</strong> pour approcher l’entropie :</p>
<p><span class="math display">\[\text{Encoder des blocs : } (X_1, \ldots, X_k) \text{ au lieu de symboles individuels}\]</span></p>
</section>
<section id="problème-de-complexité" class="level5">
<h5 class="anchored" data-anchor-id="problème-de-complexité">Problème de complexité</h5>
<p><strong>Codage par blocs de longueur <span class="math inline">\(k\)</span> :</strong> - Nécessite <span class="math inline">\(|\mathcal{X}|^k\)</span> codes différents - Complexité <strong>exponentielle</strong> en <span class="math inline">\(k\)</span></p>
<p><strong>Exemple :</strong> Pour <span class="math inline">\(|\mathcal{X}| = 256\)</span> (8 bits) et <span class="math inline">\(k = 10\)</span> : <span class="math display">\[\text{Nombre de codes} = 256^{10} \approx 10^{24}\]</span></p>
</section>
</section>
<section id="solutions-pratiques" class="level4">
<h4 class="anchored" data-anchor-id="solutions-pratiques">Solutions pratiques</h4>
<section id="codage-par-sous-blocs" class="level5">
<h5 class="anchored" data-anchor-id="codage-par-sous-blocs">Codage par sous-blocs</h5>
<p>Compromis entre optimalité et complexité :</p>
<ul>
<li><strong>JPEG</strong> : blocs de <span class="math inline">\(8 \times 8\)</span> pixels</li>
<li><strong>JPEG 2000</strong> : ondelettes multi-échelles</li>
<li><strong>Codecs modernes</strong> : blocs adaptatifs</li>
</ul>
</section>
<section id="modèles-statistiques" class="level5">
<h5 class="anchored" data-anchor-id="modèles-statistiques">Modèles statistiques</h5>
<p>Utiliser des modèles pour capturer les dépendances :</p>
<ul>
<li><strong>Modèles de Markov</strong> : dépendance locale</li>
<li><strong>Modèles contextuels</strong> : prédiction basée sur le voisinage</li>
<li><strong>Réseaux de neurones</strong> : apprentissage de représentations compactes</li>
</ul>
</section>
</section>
</section>
</section>
<section id="mesures-de-divergence-et-similarité" class="level2">
<h2 class="anchored" data-anchor-id="mesures-de-divergence-et-similarité">Mesures de Divergence et Similarité</h2>
<section id="divergence-de-kullback-leibler-kl" class="level3">
<h3 class="anchored" data-anchor-id="divergence-de-kullback-leibler-kl">Divergence de Kullback-Leibler (KL)</h3>
<section id="définition-4" class="level4">
<h4 class="anchored" data-anchor-id="définition-4">Définition</h4>
<section id="formulation-générale" class="level5">
<h5 class="anchored" data-anchor-id="formulation-générale">Formulation générale</h5>
<p>La <strong>divergence KL</strong> (ou entropie relative) entre deux distributions <span class="math inline">\(p(x)\)</span> et <span class="math inline">\(q(x)\)</span> sur le même ensemble <span class="math inline">\(\mathcal{X}\)</span> est :</p>
<p><span class="math display">\[D_{\text{KL}}(p \| q) = \sum_{x \in \mathcal{X}} p(x) \log_2 \frac{p(x)}{q(x)}\]</span></p>
</section>
<section id="forme-espérance-3" class="level5">
<h5 class="anchored" data-anchor-id="forme-espérance-3">Forme espérance</h5>
<p><span class="math display">\[D_{\text{KL}}(p \| q) = \mathbb{E}_{p(x)}\left[\log_2 \frac{p(x)}{q(x)}\right]\]</span></p>
</section>
<section id="notations-alternatives" class="level5">
<h5 class="anchored" data-anchor-id="notations-alternatives">Notations alternatives</h5>
<ul>
<li><span class="math inline">\(D(p \| q)\)</span> : notation courte</li>
<li><span class="math inline">\(D_{\text{KL}}(p \| q)\)</span> : notation explicite</li>
<li><span class="math inline">\(KL(p \| q)\)</span> : notation abrégée</li>
</ul>
</section>
</section>
<section id="conventions-mathématiques" class="level4">
<h4 class="anchored" data-anchor-id="conventions-mathématiques">Conventions mathématiques</h4>
<section id="valeurs-limites" class="level5">
<h5 class="anchored" data-anchor-id="valeurs-limites">Valeurs limites</h5>
<p>Pour assurer la cohérence mathématique :</p>
<p><span class="math display">\[0 \log_2 \frac{0}{q(x)} = 0, \quad \forall q(x)\]</span></p>
<p>(par continuité : <span class="math inline">\(\lim_{p \to 0^+} p \log p = 0\)</span>)</p>
<p><span class="math display">\[p(x) \log_2 \frac{p(x)}{0} = +\infty, \quad \forall p(x) &gt; 0\]</span></p>
<p><strong>Conséquence :</strong> Si <span class="math inline">\(\exists x : p(x) &gt; 0\)</span> et <span class="math inline">\(q(x) = 0\)</span>, alors <span class="math inline">\(D_{\text{KL}}(p \| q) = +\infty\)</span>.</p>
</section>
<section id="support" class="level5">
<h5 class="anchored" data-anchor-id="support">Support</h5>
<p>Pour que <span class="math inline">\(D_{\text{KL}}(p \| q)\)</span> soit fini, il faut que :</p>
<p><span class="math display">\[\text{Support}(p) \subseteq \text{Support}(q)\]</span></p>
<p>C’est-à-dire : <span class="math inline">\(p(x) &gt; 0 \Rightarrow q(x) &gt; 0\)</span>.</p>
</section>
</section>
<section id="propriétés-fondamentales" class="level4">
<h4 class="anchored" data-anchor-id="propriétés-fondamentales">Propriétés fondamentales</h4>
<section id="non-négativité-inégalité-de-gibbs" class="level5">
<h5 class="anchored" data-anchor-id="non-négativité-inégalité-de-gibbs">Non-négativité (Inégalité de Gibbs)</h5>
<p><span class="math display">\[D_{\text{KL}}(p \| q) \geq 0\]</span></p>
<p>avec égalité si et seulement si <span class="math inline">\(p(x) = q(x)\)</span> pour tout <span class="math inline">\(x \in \mathcal{X}\)</span>.</p>
</section>
<section id="démonstration-esquisse" class="level5">
<h5 class="anchored" data-anchor-id="démonstration-esquisse">Démonstration (esquisse)</h5>
<p>En utilisant l’inégalité de Jensen et la concavité du logarithme :</p>
<p><span class="math display">\[-D_{\text{KL}}(p \| q) = \sum_x p(x) \log \frac{q(x)}{p(x)} \leq \log \sum_x p(x) \frac{q(x)}{p(x)} = \log 1 = 0\]</span></p>
</section>
<section id="asymétrie-1" class="level5">
<h5 class="anchored" data-anchor-id="asymétrie-1">Asymétrie</h5>
<p><span class="math display">\[D_{\text{KL}}(p \| q) \neq D_{\text{KL}}(q \| p)\]</span></p>
<p>en général.</p>
<p><strong>Conséquence :</strong> La divergence KL <strong>n’est pas une distance</strong> au sens mathématique : - Elle n’est pas symétrique - Elle ne vérifie pas l’inégalité triangulaire</p>
</section>
<section id="additivité-pour-distributions-indépendantes" class="level5">
<h5 class="anchored" data-anchor-id="additivité-pour-distributions-indépendantes">Additivité pour distributions indépendantes</h5>
<p>Si <span class="math inline">\(X \perp Y\)</span> sous <span class="math inline">\(p\)</span> et sous <span class="math inline">\(q\)</span> :</p>
<p><span class="math display">\[D_{\text{KL}}(p(x,y) \| q(x,y)) = D_{\text{KL}}(p(x) \| q(x)) + D_{\text{KL}}(p(y) \| q(y))\]</span></p>
</section>
</section>
<section id="interprétation-en-théorie-du-codage-1" class="level4">
<h4 class="anchored" data-anchor-id="interprétation-en-théorie-du-codage-1">Interprétation en théorie du codage</h4>
<section id="problème-de-codage-sous-optimal" class="level5">
<h5 class="anchored" data-anchor-id="problème-de-codage-sous-optimal">Problème de codage sous-optimal</h5>
<p><strong>Situation :</strong> - <strong>Distribution réelle</strong> des données : <span class="math inline">\(p(x)\)</span> (souvent inconnue) - <strong>Distribution supposée</strong> pour le codage : <span class="math inline">\(q(x)\)</span></p>
</section>
<section id="longueurs-de-code" class="level5">
<h5 class="anchored" data-anchor-id="longueurs-de-code">Longueurs de code</h5>
<p>Si on conçoit un code optimal pour <span class="math inline">\(q(x)\)</span> : <span class="math display">\[\ell_q(x) = -\log_2 q(x)\]</span></p>
<p>Le code optimal pour <span class="math inline">\(p(x)\)</span> serait : <span class="math display">\[\ell_p(x) = -\log_2 p(x)\]</span></p>
</section>
<section id="longueur-moyenne-attendue" class="level5">
<h5 class="anchored" data-anchor-id="longueur-moyenne-attendue">Longueur moyenne attendue</h5>
<p>En utilisant le code conçu pour <span class="math inline">\(q\)</span> pour encoder des données de <span class="math inline">\(p\)</span> :</p>
<p><span class="math display">\[\ell_{\text{av}}^q = \mathbb{E}_{X \sim p}[\ell_q(X)] = \sum_x p(x) \cdot (-\log_2 q(x))\]</span></p>
</section>
<section id="décomposition" class="level5">
<h5 class="anchored" data-anchor-id="décomposition">Décomposition</h5>
<p><span class="math display">\[\ell_{\text{av}}^q = \sum_x p(x) (-\log_2 q(x))\]</span></p>
<p><span class="math display">\[= \sum_x p(x) \left(-\log_2 p(x) + \log_2 \frac{p(x)}{q(x)}\right)\]</span></p>
<p><span class="math display">\[= \underbrace{\sum_x p(x) (-\log_2 p(x))}_{H(p)} + \underbrace{\sum_x p(x) \log_2 \frac{p(x)}{q(x)}}_{D_{\text{KL}}(p \| q)}\]</span></p>
<p><strong>Formule fondamentale :</strong></p>
<p><span class="math display">\[\mathbb{E}_{X \sim p}[\ell_q(X)] = H(p) + D_{\text{KL}}(p \| q)\]</span></p>
</section>
<section id="interprétation" class="level5">
<h5 class="anchored" data-anchor-id="interprétation">Interprétation</h5>
<p>La divergence KL représente les <strong>bits supplémentaires</strong> nécessaires en moyenne lorsqu’on utilise un code sous-optimal :</p>
<p><span class="math display">\[D_{\text{KL}}(p \| q) = \text{Perte d'efficacité (en bits)}\]</span></p>
<p><strong>Optimum :</strong> <span class="math display">\[D_{\text{KL}}(p \| q) = 0 \quad \Leftrightarrow \quad p = q \quad \Leftrightarrow \quad \text{Codage optimal}\]</span></p>
</section>
</section>
<section id="interprétation-en-machine-learning" class="level4">
<h4 class="anchored" data-anchor-id="interprétation-en-machine-learning">Interprétation en Machine Learning</h4>
<section id="mesure-de-similarité" class="level5">
<h5 class="anchored" data-anchor-id="mesure-de-similarité">Mesure de similarité</h5>
<p>En apprentissage automatique, la divergence KL mesure à quel point deux distributions sont <strong>similaires</strong> ou <strong>différentes</strong> :</p>
<ul>
<li><span class="math inline">\(D_{\text{KL}}(p \| q)\)</span> faible : <span class="math inline">\(p\)</span> et <span class="math inline">\(q\)</span> sont similaires</li>
<li><span class="math inline">\(D_{\text{KL}}(p \| q)\)</span> élevé : <span class="math inline">\(p\)</span> et <span class="math inline">\(q\)</span> sont très différentes</li>
</ul>
</section>
<section id="applications" class="level5">
<h5 class="anchored" data-anchor-id="applications">Applications</h5>
<ul>
<li><strong>Approximation variationnelle</strong> : trouver <span class="math inline">\(q\)</span> qui minimise <span class="math inline">\(D_{\text{KL}}(p \| q)\)</span></li>
<li><strong>Apprentissage génératif</strong> : minimiser <span class="math inline">\(D_{\text{KL}}(p_{\text{data}} \| p_{\text{model}})\)</span></li>
<li><strong>Régularisation</strong> : pénaliser l’écart par rapport à un prior</li>
</ul>
</section>
</section>
</section>
<section id="exemple-numérique-de-kl-divergence" class="level3">
<h3 class="anchored" data-anchor-id="exemple-numérique-de-kl-divergence">Exemple Numérique de KL Divergence</h3>
<section id="configuration-binaire" class="level4">
<h4 class="anchored" data-anchor-id="configuration-binaire">Configuration binaire</h4>
<p>Considérons deux distributions binaires sur <span class="math inline">\(\mathcal{X} = \{0, 1\}\)</span> :</p>
<p><strong>Distribution <span class="math inline">\(p\)</span> :</strong> <span class="math display">\[p(0) = a, \quad p(1) = 1 - a\]</span></p>
<p><strong>Distribution <span class="math inline">\(q\)</span> :</strong> <span class="math display">\[q(0) = b, \quad q(1) = 1 - b\]</span></p>
</section>
<section id="formules" class="level4">
<h4 class="anchored" data-anchor-id="formules">Formules</h4>
<section id="d_textklp-q" class="level5">
<h5 class="anchored" data-anchor-id="d_textklp-q"><span class="math inline">\(D_{\text{KL}}(p \| q)\)</span></h5>
<p><span class="math display">\[D_{\text{KL}}(p \| q) = a \log_2 \frac{a}{b} + (1-a) \log_2 \frac{1-a}{1-b}\]</span></p>
</section>
<section id="d_textklq-p" class="level5">
<h5 class="anchored" data-anchor-id="d_textklq-p"><span class="math inline">\(D_{\text{KL}}(q \| p)\)</span></h5>
<p><span class="math display">\[D_{\text{KL}}(q \| p) = b \log_2 \frac{b}{a} + (1-b) \log_2 \frac{1-b}{1-a}\]</span></p>
</section>
</section>
<section id="calcul-numérique" class="level4">
<h4 class="anchored" data-anchor-id="calcul-numérique">Calcul numérique</h4>
<p><strong>Paramètres :</strong> <span class="math inline">\(a = 1/4 = 0.25\)</span>, <span class="math inline">\(b = 1/8 = 0.125\)</span></p>
<section id="d_textklp-q-1" class="level5">
<h5 class="anchored" data-anchor-id="d_textklp-q-1"><span class="math inline">\(D_{\text{KL}}(p \| q)\)</span></h5>
<p><span class="math display">\[D_{\text{KL}}(p \| q) = 0.25 \log_2 \frac{0.25}{0.125} + 0.75 \log_2 \frac{0.75}{0.875}\]</span></p>
<p><span class="math display">\[= 0.25 \log_2 2 + 0.75 \log_2 \frac{0.75}{0.875}\]</span></p>
<p><span class="math display">\[= 0.25 \times 1 + 0.75 \times (-0.2223)\]</span></p>
<p><span class="math display">\[= 0.25 - 0.1667 = 0.0832 \text{ bit}\]</span></p>
</section>
<section id="d_textklq-p-1" class="level5">
<h5 class="anchored" data-anchor-id="d_textklq-p-1"><span class="math inline">\(D_{\text{KL}}(q \| p)\)</span></h5>
<p><span class="math display">\[D_{\text{KL}}(q \| p) = 0.125 \log_2 \frac{0.125}{0.25} + 0.875 \log_2 \frac{0.875}{0.75}\]</span></p>
<p><span class="math display">\[= 0.125 \log_2 0.5 + 0.875 \log_2 1.1667\]</span></p>
<p><span class="math display">\[= 0.125 \times (-1) + 0.875 \times 0.2223\]</span></p>
<p><span class="math display">\[= -0.125 + 0.1945 = 0.0696 \text{ bit}\]</span></p>
</section>
</section>
<section id="vérification-de-lasymétrie" class="level4">
<h4 class="anchored" data-anchor-id="vérification-de-lasymétrie">Vérification de l’asymétrie</h4>
<p><span class="math display">\[D_{\text{KL}}(p \| q) = 0.0832 \neq 0.0696 = D_{\text{KL}}(q \| p)\]</span></p>
<p>✓ Confirme que la divergence KL <strong>n’est pas symétrique</strong>.</p>
</section>
</section>
<section id="cross-entropy-entropie-croisée" class="level3">
<h3 class="anchored" data-anchor-id="cross-entropy-entropie-croisée">Cross-Entropy (Entropie Croisée)</h3>
<section id="définition-5" class="level4">
<h4 class="anchored" data-anchor-id="définition-5">Définition</h4>
<section id="formulation" class="level5">
<h5 class="anchored" data-anchor-id="formulation">Formulation</h5>
<p>L’<strong>entropie croisée</strong> entre deux distributions <span class="math inline">\(p\)</span> et <span class="math inline">\(q\)</span> est :</p>
<p><span class="math display">\[H(p, q) = -\sum_{x \in \mathcal{X}} p(x) \log_2 q(x)\]</span></p>
</section>
<section id="forme-espérance-4" class="level5">
<h5 class="anchored" data-anchor-id="forme-espérance-4">Forme espérance</h5>
<p><span class="math display">\[H(p, q) = -\mathbb{E}_{p(x)}[\log_2 q(x)]\]</span></p>
</section>
<section id="asymétrie-2" class="level5">
<h5 class="anchored" data-anchor-id="asymétrie-2">Asymétrie</h5>
<p>Comme pour la KL divergence :</p>
<p><span class="math display">\[H(p, q) \neq H(q, p)\]</span></p>
<p>en général.</p>
</section>
</section>
<section id="lien-avec-la-divergence-kl" class="level4">
<h4 class="anchored" data-anchor-id="lien-avec-la-divergence-kl">Lien avec la Divergence KL</h4>
<section id="relation-fondamentale" class="level5">
<h5 class="anchored" data-anchor-id="relation-fondamentale">Relation fondamentale</h5>
<p><span class="math display">\[H(p, q) = H(p) + D_{\text{KL}}(p \| q)\]</span></p>
</section>
<section id="démonstration-2" class="level5">
<h5 class="anchored" data-anchor-id="démonstration-2">Démonstration</h5>
<p><span class="math display">\[D_{\text{KL}}(p \| q) = \sum_x p(x) \log_2 \frac{p(x)}{q(x)}\]</span></p>
<p><span class="math display">\[= \sum_x p(x) \log_2 p(x) - \sum_x p(x) \log_2 q(x)\]</span></p>
<p><span class="math display">\[= -H(p) + H(p, q)\]</span></p>
<p>D’où :</p>
<p><span class="math display">\[H(p, q) = H(p) + D_{\text{KL}}(p \| q)\]</span></p>
</section>
</section>
<section id="propriété-doptimisation" class="level4">
<h4 class="anchored" data-anchor-id="propriété-doptimisation">Propriété d’optimisation</h4>
<section id="équivalence-doptimisation" class="level5">
<h5 class="anchored" data-anchor-id="équivalence-doptimisation">Équivalence d’optimisation</h5>
<p>Puisque <span class="math inline">\(H(p)\)</span> ne dépend <strong>pas</strong> de <span class="math inline">\(q\)</span>, minimiser <span class="math inline">\(H(p, q)\)</span> par rapport à <span class="math inline">\(q\)</span> est <strong>équivalent</strong> à minimiser <span class="math inline">\(D_{\text{KL}}(p \| q)\)</span> :</p>
<p><span class="math display">\[\arg\min_q H(p, q) = \arg\min_q D_{\text{KL}}(p \| q)\]</span></p>
</section>
<section id="optimum" class="level5">
<h5 class="anchored" data-anchor-id="optimum">Optimum</h5>
<p>Le minimum est atteint pour <span class="math inline">\(q = p\)</span> :</p>
<p><span class="math display">\[H(p, p) = H(p) + D_{\text{KL}}(p \| p) = H(p) + 0 = H(p)\]</span></p>
</section>
</section>
<section id="application-en-machine-learning" class="level4">
<h4 class="anchored" data-anchor-id="application-en-machine-learning">Application en Machine Learning</h4>
<section id="fonction-de-perte-pour-classification" class="level5">
<h5 class="anchored" data-anchor-id="fonction-de-perte-pour-classification">Fonction de perte pour classification</h5>
<p>En apprentissage supervisé, la cross-entropy est largement utilisée comme <strong>fonction de perte</strong> :</p>
<p><strong>Configuration :</strong> - <span class="math inline">\(p(y)\)</span> : distribution vraie (souvent one-hot en classification) - <span class="math inline">\(q(y)\)</span> ou <span class="math inline">\(q(y|x)\)</span> : distribution prédite par le modèle</p>
<p><strong>Fonction de perte :</strong></p>
<p><span class="math display">\[\mathcal{L} = H(p, q) = -\sum_{y} p(y) \log q(y)\]</span></p>
<p>ou pour un batch :</p>
<p><span class="math display">\[\mathcal{L} = -\frac{1}{N} \sum_{i=1}^{N} \sum_{y} p(y_i) \log q(y_i | x_i)\]</span></p>
</section>
<section id="cas-de-la-classification-binaire" class="level5">
<h5 class="anchored" data-anchor-id="cas-de-la-classification-binaire">Cas de la classification binaire</h5>
<p>Pour une classification binaire (<span class="math inline">\(y \in \{0, 1\}\)</span>) :</p>
<p><span class="math display">\[\mathcal{L} = -[y \log \hat{y} + (1-y) \log(1-\hat{y})]\]</span></p>
<p>où <span class="math inline">\(\hat{y} = q(y=1|x)\)</span> est la probabilité prédite.</p>
</section>
<section id="avantages" class="level5">
<h5 class="anchored" data-anchor-id="avantages">Avantages</h5>
<ul>
<li><strong>Gradient bien défini</strong> : évite les problèmes de saturation</li>
<li><strong>Interprétation probabiliste</strong> : minimiser la distance entre distributions</li>
<li><strong>Lien avec maximum de vraisemblance</strong> : équivalent à maximiser la log-vraisemblance</li>
</ul>
</section>
</section>
</section>
</section>
<section id="information-mutuelle" class="level2">
<h2 class="anchored" data-anchor-id="information-mutuelle">Information Mutuelle</h2>
<section id="définitions-et-formulations" class="level3">
<h3 class="anchored" data-anchor-id="définitions-et-formulations">Définitions et Formulations</h3>
<section id="définition-générale-2" class="level4">
<h4 class="anchored" data-anchor-id="définition-générale-2">Définition générale</h4>
<section id="information-mutuelle-entre-deux-variables" class="level5">
<h5 class="anchored" data-anchor-id="information-mutuelle-entre-deux-variables">Information mutuelle entre deux variables</h5>
<p>L’<strong>information mutuelle</strong> entre <span class="math inline">\(X\)</span> et <span class="math inline">\(Y\)</span> est :</p>
<p><span class="math display">\[I(X; Y) = \sum_{x \in \mathcal{X}} \sum_{y \in \mathcal{Y}} p_{X,Y}(x, y) \log_2 \frac{p_{X,Y}(x, y)}{p_X(x) p_Y(y)}\]</span></p>
</section>
<section id="forme-espérance-5" class="level5">
<h5 class="anchored" data-anchor-id="forme-espérance-5">Forme espérance</h5>
<p><span class="math display">\[I(X; Y) = \mathbb{E}_{p_{X,Y}}\left[\log_2 \frac{p_{X,Y}(X, Y)}{p_X(X) p_Y(Y)}\right]\]</span></p>
</section>
</section>
<section id="formulation-via-divergence-kl" class="level4">
<h4 class="anchored" data-anchor-id="formulation-via-divergence-kl">Formulation via divergence KL</h4>
<section id="kl-divergence-entre-jointe-et-produit-des-marginales" class="level5">
<h5 class="anchored" data-anchor-id="kl-divergence-entre-jointe-et-produit-des-marginales">KL divergence entre jointe et produit des marginales</h5>
<p><span class="math display">\[I(X; Y) = D_{\text{KL}}(p_{X,Y}(x, y) \| p_X(x) p_Y(y))\]</span></p>
</section>
<section id="interprétation-1" class="level5">
<h5 class="anchored" data-anchor-id="interprétation-1">Interprétation</h5>
<p>L’information mutuelle mesure à quel point la <strong>distribution jointe</strong> <span class="math inline">\(p_{X,Y}(x, y)\)</span> diffère du produit des marginales <span class="math inline">\(p_X(x) p_Y(y)\)</span>.</p>
<p><strong>Autrement dit :</strong> mesure la <strong>dépendance</strong> entre <span class="math inline">\(X\)</span> et <span class="math inline">\(Y\)</span> par rapport à l’hypothèse d’<strong>indépendance</strong>.</p>
</section>
</section>
<section id="formulations-alternatives" class="level4">
<h4 class="anchored" data-anchor-id="formulations-alternatives">Formulations alternatives</h4>
<section id="forme-conditionnelle-1" class="level5">
<h5 class="anchored" data-anchor-id="forme-conditionnelle-1">Forme conditionnelle 1</h5>
<p><span class="math display">\[I(X; Y) = \sum_{x, y} p_{X,Y}(x, y) \log_2 \frac{p_{X|Y}(x | y)}{p_X(x)}\]</span></p>
<p><span class="math display">\[= \mathbb{E}_{p(y)}[D_{\text{KL}}(p(x|y) \| p(x))]\]</span></p>
</section>
<section id="forme-conditionnelle-2" class="level5">
<h5 class="anchored" data-anchor-id="forme-conditionnelle-2">Forme conditionnelle 2</h5>
<p><span class="math display">\[I(X; Y) = \sum_{x, y} p_{X,Y}(x, y) \log_2 \frac{p_{Y|X}(y | x)}{p_Y(y)}\]</span></p>
<p><span class="math display">\[= \mathbb{E}_{p(x)}[D_{\text{KL}}(p(y|x) \| p(y))]\]</span></p>
</section>
</section>
</section>
<section id="propriétés-fondamentales-1" class="level3">
<h3 class="anchored" data-anchor-id="propriétés-fondamentales-1">Propriétés Fondamentales</h3>
<section id="symétrie-1" class="level4">
<h4 class="anchored" data-anchor-id="symétrie-1">Symétrie</h4>
<p><span class="math display">\[I(X; Y) = I(Y; X)\]</span></p>
<p><strong>Conséquence :</strong> Contrairement à la divergence KL, l’information mutuelle est <strong>symétrique</strong>.</p>
</section>
<section id="non-négativité-1" class="level4">
<h4 class="anchored" data-anchor-id="non-négativité-1">Non-négativité</h4>
<p><span class="math display">\[I(X; Y) \geq 0\]</span></p>
<p><strong>Égalité :</strong></p>
<p><span class="math display">\[I(X; Y) = 0 \quad \Leftrightarrow \quad X \perp Y\]</span></p>
<p>(<span class="math inline">\(X\)</span> et <span class="math inline">\(Y\)</span> sont indépendants)</p>
<section id="démonstration-3" class="level5">
<h5 class="anchored" data-anchor-id="démonstration-3">Démonstration</h5>
<p>Puisque <span class="math inline">\(I(X; Y) = D_{\text{KL}}(p_{X,Y} \| p_X p_Y)\)</span> et que la divergence KL est toujours non-négative, on a <span class="math inline">\(I(X; Y) \geq 0\)</span>.</p>
<p>L’égalité est atteinte si et seulement si <span class="math inline">\(p_{X,Y}(x,y) = p_X(x) p_Y(y)\)</span> pour tout <span class="math inline">\(x, y\)</span>, c’est-à-dire si <span class="math inline">\(X\)</span> et <span class="math inline">\(Y\)</span> sont indépendants.</p>
</section>
</section>
<section id="borne-supérieure" class="level4">
<h4 class="anchored" data-anchor-id="borne-supérieure">Borne supérieure</h4>
<p><span class="math display">\[I(X; Y) \leq \min\{H(X), H(Y)\}\]</span></p>
<p><strong>Égalité :</strong> - <span class="math inline">\(I(X; Y) = H(X)\)</span> si <span class="math inline">\(Y\)</span> détermine complètement <span class="math inline">\(X\)</span> (i.e., <span class="math inline">\(X = f(Y)\)</span>) - <span class="math inline">\(I(X; Y) = H(Y)\)</span> si <span class="math inline">\(X\)</span> détermine complètement <span class="math inline">\(Y\)</span> (i.e., <span class="math inline">\(Y = g(X)\)</span>)</p>
</section>
<section id="auto-information" class="level4">
<h4 class="anchored" data-anchor-id="auto-information">Auto-information</h4>
<p><span class="math display">\[I(X; X) = H(X)\]</span></p>
<p><strong>Justification :</strong></p>
<p><span class="math display">\[I(X; X) = H(X) - H(X | X) = H(X) - 0 = H(X)\]</span></p>
<p>car <span class="math inline">\(H(X | X) = 0\)</span> (connaître <span class="math inline">\(X\)</span> élimine toute incertitude sur <span class="math inline">\(X\)</span>).</p>
</section>
</section>
<section id="relations-avec-lentropie" class="level3">
<h3 class="anchored" data-anchor-id="relations-avec-lentropie">Relations avec l’Entropie</h3>
<section id="relations-fondamentales" class="level4">
<h4 class="anchored" data-anchor-id="relations-fondamentales">Relations fondamentales</h4>
<section id="relation-1" class="level5">
<h5 class="anchored" data-anchor-id="relation-1">Relation 1</h5>
<p><span class="math display">\[I(X; Y) = H(X) - H(X | Y)\]</span></p>
<p><strong>Interprétation :</strong> L’information mutuelle est la <strong>réduction d’incertitude</strong> sur <span class="math inline">\(X\)</span> apportée par la connaissance de <span class="math inline">\(Y\)</span>.</p>
</section>
<section id="relation-2" class="level5">
<h5 class="anchored" data-anchor-id="relation-2">Relation 2</h5>
<p><span class="math display">\[I(X; Y) = H(Y) - H(Y | X)\]</span></p>
<p><strong>Interprétation :</strong> Par symétrie, c’est aussi la réduction d’incertitude sur <span class="math inline">\(Y\)</span> apportée par <span class="math inline">\(X\)</span>.</p>
</section>
<section id="relation-3" class="level5">
<h5 class="anchored" data-anchor-id="relation-3">Relation 3</h5>
<p><span class="math display">\[I(X; Y) = H(X) + H(Y) - H(X, Y)\]</span></p>
<p><strong>Démonstration :</strong></p>
<p>En utilisant la règle de chaîne : <span class="math inline">\(H(X, Y) = H(X) + H(Y | X)\)</span></p>
<p>Donc : <span class="math display">\[I(X; Y) = H(Y) - H(Y | X) = H(Y) - [H(X, Y) - H(X)]\]</span> <span class="math display">\[= H(X) + H(Y) - H(X, Y)\]</span></p>
</section>
<section id="cas-dindépendance" class="level5">
<h5 class="anchored" data-anchor-id="cas-dindépendance">Cas d’indépendance</h5>
<p>Si <span class="math inline">\(X \perp Y\)</span> : <span class="math display">\[I(X; Y) = 0\]</span> <span class="math display">\[H(X, Y) = H(X) + H(Y)\]</span></p>
</section>
</section>
<section id="diagramme-de-venn" class="level4">
<h4 class="anchored" data-anchor-id="diagramme-de-venn">Diagramme de Venn</h4>
<p>Les relations entre entropies peuvent être visualisées avec un diagramme de Venn :</p>
<pre><code>     H(X)              H(Y)
    ┌────────────┬────────────┐
    │            │            │
    │  H(X|Y)    │  I(X;Y)    │  H(Y|X)
    │            │            │
    └────────────┴────────────┘
         H(X,Y)</code></pre>
<p><strong>Lecture :</strong> - <strong>Zone totale</strong> : <span class="math inline">\(H(X, Y)\)</span> (entropie jointe) - <strong>Zone gauche</strong> : <span class="math inline">\(H(X|Y)\)</span> (incertitude sur <span class="math inline">\(X\)</span> sachant <span class="math inline">\(Y\)</span>) - <strong>Zone centrale</strong> (intersection) : <span class="math inline">\(I(X; Y)\)</span> (information mutuelle) - <strong>Zone droite</strong> : <span class="math inline">\(H(Y|X)\)</span> (incertitude sur <span class="math inline">\(Y\)</span> sachant <span class="math inline">\(X\)</span>) - <strong>Cercle gauche</strong> : <span class="math inline">\(H(X) = H(X|Y) + I(X;Y)\)</span> - <strong>Cercle droit</strong> : <span class="math inline">\(H(Y) = H(Y|X) + I(X;Y)\)</span></p>
</section>
</section>
<section id="information-mutuelle-conditionnelle" class="level3">
<h3 class="anchored" data-anchor-id="information-mutuelle-conditionnelle">Information Mutuelle Conditionnelle</h3>
<section id="définition-6" class="level4">
<h4 class="anchored" data-anchor-id="définition-6">Définition</h4>
<section id="information-mutuelle-entre-x-et-y-sachant-z" class="level5">
<h5 class="anchored" data-anchor-id="information-mutuelle-entre-x-et-y-sachant-z">Information mutuelle entre <span class="math inline">\(X\)</span> et <span class="math inline">\(Y\)</span> sachant <span class="math inline">\(Z\)</span></h5>
<p><span class="math display">\[I(X; Y | Z) = H(X | Z) - H(X | Y, Z)\]</span></p>
</section>
<section id="formes-alternatives" class="level5">
<h5 class="anchored" data-anchor-id="formes-alternatives">Formes alternatives</h5>
<p><span class="math display">\[I(X; Y | Z) = H(Y | Z) - H(Y | X, Z)\]</span></p>
<p><span class="math display">\[I(X; Y | Z) = H(X | Z) + H(Y | Z) - H(X, Y | Z)\]</span></p>
</section>
</section>
<section id="formulation-via-kl-divergence" class="level4">
<h4 class="anchored" data-anchor-id="formulation-via-kl-divergence">Formulation via KL divergence</h4>
<p><span class="math display">\[I(X; Y | Z) = \mathbb{E}_{p(z)}[D_{\text{KL}}(p(x,y|z) \| p(x|z)p(y|z))]\]</span></p>
<p><span class="math display">\[= \mathbb{E}_{p(x,y,z)}\left[\log_2 \frac{p_{X,Y|Z}(x, y | z)}{p_{X|Z}(x | z) p_{Y|Z}(y | z)}\right]\]</span></p>
<p><span class="math display">\[= \mathbb{E}_{p(x,y,z)}\left[\log_2 \frac{p_{X|Y,Z}(x | y, z)}{p_{X|Z}(x | z)}\right]\]</span></p>
</section>
<section id="démonstration-4" class="level4">
<h4 class="anchored" data-anchor-id="démonstration-4">Démonstration</h4>
<p>En utilisant la décomposition :</p>
<p><span class="math display">\[p_{X,Y|Z}(x, y | z) = p_{Y|Z}(y | z) \cdot p_{X|Y,Z}(x | y, z)\]</span></p>
<p>On a :</p>
<p><span class="math display">\[I(X; Y | Z) = \mathbb{E}_{p(x,y,z)}[\log_2 p_{X|Y,Z}(x | y, z)] - \mathbb{E}_{p(x,y,z)}[\log_2 p_{X|Z}(x | z)]\]</span></p>
<p><span class="math display">\[= -H(X | Y, Z) + H(X | Z)\]</span></p>
</section>
<section id="diagramme" class="level4">
<h4 class="anchored" data-anchor-id="diagramme">Diagramme</h4>
<pre><code>     H(X|Z)         H(Y|Z)
    ┌──────────┬──────────┐
    │          │          │
    │          │ I(X;Y|Z) │
    │          │          │
    └──────────┴──────────┘</code></pre>
</section>
</section>
<section id="règle-de-chaîne-pour-linformation-mutuelle" class="level3">
<h3 class="anchored" data-anchor-id="règle-de-chaîne-pour-linformation-mutuelle">Règle de Chaîne pour l’Information Mutuelle</h3>
<section id="énoncé-général" class="level4">
<h4 class="anchored" data-anchor-id="énoncé-général">Énoncé général</h4>
<section id="pour-n-variables" class="level5">
<h5 class="anchored" data-anchor-id="pour-n-variables">Pour N variables</h5>
<p><span class="math display">\[I(X_1, X_2, \ldots, X_N; Y) = \sum_{i=1}^{N} I(X_i; Y | X_{i-1}, \ldots, X_1)\]</span></p>
</section>
</section>
<section id="démonstration-5" class="level4">
<h4 class="anchored" data-anchor-id="démonstration-5">Démonstration</h4>
<p>En utilisant la règle de chaîne pour l’entropie :</p>
<p><span class="math display">\[I(X_1, \ldots, X_N; Y) = H(X_1, \ldots, X_N) - H(X_1, \ldots, X_N | Y)\]</span></p>
<p><span class="math display">\[= \sum_{i=1}^{N} H(X_i | X_{i-1}, \ldots, X_1) - \sum_{i=1}^{N} H(X_i | X_{i-1}, \ldots, X_1, Y)\]</span></p>
<p><span class="math display">\[= \sum_{i=1}^{N} [H(X_i | X_{i-1}, \ldots, X_1) - H(X_i | X_{i-1}, \ldots, X_1, Y)]\]</span></p>
<p><span class="math display">\[= \sum_{i=1}^{N} I(X_i; Y | X_{i-1}, \ldots, X_1)\]</span></p>
</section>
<section id="application-analyse-de-features" class="level4">
<h4 class="anchored" data-anchor-id="application-analyse-de-features">Application : analyse de features</h4>
<section id="sélection-de-features" class="level5">
<h5 class="anchored" data-anchor-id="sélection-de-features">Sélection de features</h5>
<p>Pour sélectionner les features les plus informatives par rapport à un label <span class="math inline">\(Y\)</span> :</p>
<p><strong>Approche greedy :</strong></p>
<ol type="1">
<li>Sélectionner <span class="math inline">\(X_1 = \arg\max_{X_i} I(X_i; Y)\)</span></li>
<li>Sélectionner <span class="math inline">\(X_2 = \arg\max_{X_i} I(X_i; Y | X_1)\)</span></li>
<li>Continuer jusqu’à obtenir <span class="math inline">\(k\)</span> features</li>
</ol>
<p><strong>Information totale :</strong></p>
<p><span class="math display">\[I(X_1, \ldots, X_k; Y) = \sum_{i=1}^{k} I(X_i; Y | X_{i-1}, \ldots, X_1)\]</span></p>
</section>
</section>
<section id="exemple-pixels-dimage-et-label" class="level4">
<h4 class="anchored" data-anchor-id="exemple-pixels-dimage-et-label">Exemple : pixels d’image et label</h4>
<section id="configuration-1" class="level5">
<h5 class="anchored" data-anchor-id="configuration-1">Configuration</h5>
<p>Une image représentée par <span class="math inline">\(N\)</span> pixels :</p>
<p><span class="math display">\[X = \begin{pmatrix} X_1 \\ X_2 \\ \vdots \\ X_N \end{pmatrix} \in \mathcal{X}^N\]</span></p>
<p>avec <span class="math inline">\(N = n \times m\)</span> (dimensions de l’image).</p>
<p>Un label :</p>
<p><span class="math display">\[Y \in \mathcal{Y}\]</span></p>
</section>
<section id="information-mutuelle-totale" class="level5">
<h5 class="anchored" data-anchor-id="information-mutuelle-totale">Information mutuelle totale</h5>
<p><span class="math display">\[I(X_1, X_2, \ldots, X_N; Y) = \sum_{i=1}^{N} I(X_i; Y | X_{i-1}, \ldots, X_1)\]</span></p>
<p><strong>Interprétation :</strong> Chaque terme <span class="math inline">\(I(X_i; Y | X_{i-1}, \ldots, X_1)\)</span> représente l’information <strong>additionnelle</strong> apportée par le pixel <span class="math inline">\(X_i\)</span> sur le label <span class="math inline">\(Y\)</span>, sachant les pixels précédents.</p>
</section>
</section>
</section>
<section id="décompositions-complexes" class="level3">
<h3 class="anchored" data-anchor-id="décompositions-complexes">Décompositions Complexes</h3>
<section id="deux-variables-et-deux-labels" class="level4">
<h4 class="anchored" data-anchor-id="deux-variables-et-deux-labels">Deux variables et deux labels</h4>
<p>Pour <span class="math inline">\(X_1, X_2\)</span> et <span class="math inline">\(Y_1, Y_2\)</span> :</p>
<p><span class="math display">\[I(X_1, X_2; Y_1, Y_2) = I(X_1; Y_1, Y_2) + I(X_2; Y_1, Y_2 | X_1)\]</span></p>
<section id="décomposition-de-ix_1-y_1-y_2" class="level5">
<h5 class="anchored" data-anchor-id="décomposition-de-ix_1-y_1-y_2">Décomposition de <span class="math inline">\(I(X_1; Y_1, Y_2)\)</span></h5>
<p><span class="math display">\[I(X_1; Y_1, Y_2) = I(X_1; Y_1) + I(X_1; Y_2 | Y_1)\]</span></p>
<p>ou alternativement :</p>
<p><span class="math display">\[I(X_1; Y_1, Y_2) = I(X_1; Y_2) + I(X_1; Y_1 | Y_2)\]</span></p>
</section>
<section id="décomposition-de-ix_2-y_1-y_2-x_1" class="level5">
<h5 class="anchored" data-anchor-id="décomposition-de-ix_2-y_1-y_2-x_1">Décomposition de <span class="math inline">\(I(X_2; Y_1, Y_2 | X_1)\)</span></h5>
<p><span class="math display">\[I(X_2; Y_1, Y_2 | X_1) = I(X_2; Y_1 | X_1) + I(X_2; Y_2 | X_1, Y_1)\]</span></p>
<p>ou :</p>
<p><span class="math display">\[I(X_2; Y_1, Y_2 | X_1) = I(X_2; Y_2 | X_1) + I(X_2; Y_1 | X_1, Y_2)\]</span></p>
</section>
</section>
</section>
<section id="inégalité-de-traitement-des-données-data-processing-inequality" class="level3">
<h3 class="anchored" data-anchor-id="inégalité-de-traitement-des-données-data-processing-inequality">Inégalité de Traitement des Données (Data Processing Inequality)</h3>
<section id="chaîne-de-markov" class="level4">
<h4 class="anchored" data-anchor-id="chaîne-de-markov">Chaîne de Markov</h4>
<section id="configuration-2" class="level5">
<h5 class="anchored" data-anchor-id="configuration-2">Configuration</h5>
<p>Considérons une <strong>chaîne de Markov</strong> :</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    X --&gt; Y
    Y --&gt; Z
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Notation :</strong> <span class="math inline">\(X \to Y \to Z\)</span></p>
<p><strong>Définition formelle :</strong></p>
<p><span class="math display">\[p_{X,Y,Z}(x, y, z) = p_X(x) \cdot p_{Y|X}(y | x) \cdot p_{Z|Y}(z | y)\]</span></p>
<p><strong>Propriété clé :</strong></p>
<p><span class="math display">\[X \perp Z | Y\]</span></p>
<p>c’est-à-dire : <span class="math inline">\(p(x, z | y) = p(x | y) p(z | y)\)</span></p>
</section>
</section>
<section id="inégalité-fondamentale" class="level4">
<h4 class="anchored" data-anchor-id="inégalité-fondamentale">Inégalité fondamentale</h4>
<section id="énoncés" class="level5">
<h5 class="anchored" data-anchor-id="énoncés">Énoncés</h5>
<p>Pour une chaîne de Markov <span class="math inline">\(X \to Y \to Z\)</span> :</p>
<p><span class="math display">\[I(X; Y) \geq I(X; Z)\]</span></p>
<p><span class="math display">\[I(Y; Z) \geq I(X; Z)\]</span></p>
</section>
<section id="cas-dégalité-1" class="level5">
<h5 class="anchored" data-anchor-id="cas-dégalité-1">Cas d’égalité</h5>
<p><span class="math display">\[I(X; Y) = I(X; Z) \quad \Leftrightarrow \quad X \leftrightarrow Y \leftrightarrow Z \text{ (chaîne réversible)}\]</span></p>
</section>
</section>
<section id="cas-particulier-important" class="level4">
<h4 class="anchored" data-anchor-id="cas-particulier-important">Cas particulier important</h4>
<section id="fonction-déterministe" class="level5">
<h5 class="anchored" data-anchor-id="fonction-déterministe">Fonction déterministe</h5>
<p>Si <span class="math inline">\(Z = g(Y)\)</span> où <span class="math inline">\(g\)</span> est une fonction déterministe :</p>
<p><span class="math display">\[I(X; Y) \geq I(X; g(Y))\]</span></p>
<p><strong>Interprétation :</strong> Toute transformation de <span class="math inline">\(Y\)</span> <strong>réduit</strong> (ou laisse inchangée) l’information mutuelle avec <span class="math inline">\(X\)</span>.</p>
</section>
</section>
<section id="interprétation-2" class="level4">
<h4 class="anchored" data-anchor-id="interprétation-2">Interprétation</h4>
<section id="principe-de-non-créativité-de-linformation" class="level5">
<h5 class="anchored" data-anchor-id="principe-de-non-créativité-de-linformation">Principe de non-créativité de l’information</h5>
<p><strong>Le traitement des données ne peut pas créer d’information :</strong></p>
<p>La quantité d’information <strong>ne peut pas être augmentée</strong> par un traitement quelconque (transformation, filtrage, etc.).</p>
</section>
<section id="applications-1" class="level5">
<h5 class="anchored" data-anchor-id="applications-1">Applications</h5>
<p><strong>Réseaux de neurones profonds :</strong></p>
<p>Pour un réseau <span class="math inline">\(X \to h_1 \to h_2 \to \cdots \to h_L \to Y\)</span> :</p>
<p><span class="math display">\[I(X; Y) \leq I(X; h_L) \leq \cdots \leq I(X; h_2) \leq I(X; h_1)\]</span></p>
<p><strong>Compression :</strong></p>
<p>Toute compression réduit l’information mutuelle avec la source originale.</p>
<p><strong>Communication :</strong></p>
<p>L’information ne peut pas être augmentée par un canal bruité.</p>
</section>
</section>
<section id="démonstration-6" class="level4">
<h4 class="anchored" data-anchor-id="démonstration-6">Démonstration</h4>
<section id="utilisation-de-la-règle-de-chaîne" class="level5">
<h5 class="anchored" data-anchor-id="utilisation-de-la-règle-de-chaîne">Utilisation de la règle de chaîne</h5>
<p><span class="math display">\[I(X; Y, Z) = I(X; Z) + I(X; Y | Z) \quad \text{...(a)}\]</span></p>
<p><span class="math display">\[I(X; Y, Z) = I(X; Y) + I(X; Z | Y) \quad \text{...(b)}\]</span></p>
</section>
<section id="propriété-de-la-chaîne-de-markov" class="level5">
<h5 class="anchored" data-anchor-id="propriété-de-la-chaîne-de-markov">Propriété de la chaîne de Markov</h5>
<p>Pour <span class="math inline">\(X \to Y \to Z\)</span>, on a <span class="math inline">\(X \perp Z | Y\)</span>, donc :</p>
<p><span class="math display">\[I(X; Z | Y) = 0\]</span></p>
</section>
<section id="conclusion" class="level5">
<h5 class="anchored" data-anchor-id="conclusion">Conclusion</h5>
<p>De (b) :</p>
<p><span class="math display">\[I(X; Y, Z) = I(X; Y) + 0 = I(X; Y)\]</span></p>
<p>En combinant avec (a) :</p>
<p><span class="math display">\[I(X; Y) = I(X; Z) + I(X; Y | Z)\]</span></p>
<p>Puisque <span class="math inline">\(I(X; Y | Z) \geq 0\)</span>, on obtient :</p>
<p><span class="math display">\[I(X; Y) \geq I(X; Z)\]</span></p>
</section>
</section>
</section>
</section>
<section id="variables-continues-entropie-différentielle" class="level2">
<h2 class="anchored" data-anchor-id="variables-continues-entropie-différentielle">Variables Continues : Entropie Différentielle</h2>
<section id="motivation-et-limite" class="level3">
<h3 class="anchored" data-anchor-id="motivation-et-limite">Motivation et Limite</h3>
<section id="passage-du-discret-au-continu" class="level4">
<h4 class="anchored" data-anchor-id="passage-du-discret-au-continu">Passage du discret au continu</h4>
<section id="quantification" class="level5">
<h5 class="anchored" data-anchor-id="quantification">Quantification</h5>
<p>Pour une variable continue <span class="math inline">\(X\)</span> avec densité <span class="math inline">\(f_X(x)\)</span>, on peut l’approximer par une variable discrète en quantifiant :</p>
<p><span class="math display">\[P[x_k; \Delta x] = \int_{x_k}^{x_k + \Delta x} f_X(x) dx \approx f_X(x_k) \Delta x\]</span></p>
</section>
<section id="entropie-de-la-version-quantifiée" class="level5">
<h5 class="anchored" data-anchor-id="entropie-de-la-version-quantifiée">Entropie de la version quantifiée</h5>
<p><span class="math display">\[H(X; \Delta x) = -\sum_{k=1}^{N} P[x_k; \Delta x] \log_2 P[x_k; \Delta x]\]</span></p>
<p><span class="math display">\[= -\sum_{k=1}^{N} f_X(x_k) \Delta x \log_2[f_X(x_k) \Delta x]\]</span></p>
</section>
</section>
<section id="décomposition-1" class="level4">
<h4 class="anchored" data-anchor-id="décomposition-1">Décomposition</h4>
<p>En utilisant <span class="math inline">\(\log(ab) = \log a + \log b\)</span> :</p>
<p><span class="math display">\[H(X; \Delta x) = -\sum_{k=1}^{N} f_X(x_k) \Delta x \log_2 f_X(x_k) - \sum_{k=1}^{N} f_X(x_k) \Delta x \log_2 \Delta x\]</span></p>
<p><span class="math display">\[= -\sum_{k=1}^{N} f_X(x_k) \Delta x \log_2 f_X(x_k) - \log_2 \Delta x \underbrace{\sum_{k=1}^{N} f_X(x_k) \Delta x}_{\approx 1}\]</span></p>
</section>
<section id="passage-à-la-limite" class="level4">
<h4 class="anchored" data-anchor-id="passage-à-la-limite">Passage à la limite</h4>
<section id="limite-continue" class="level5">
<h5 class="anchored" data-anchor-id="limite-continue">Limite continue</h5>
<p>Lorsque <span class="math inline">\(\Delta x \to 0\)</span> et <span class="math inline">\(N \to \infty\)</span> :</p>
<p><span class="math display">\[-\sum_{k=1}^{N} f_X(x_k) \Delta x \log_2 f_X(x_k) \to -\int_{-\infty}^{\infty} f_X(x) \log_2 f_X(x) dx\]</span></p>
</section>
<section id="problème-avec-le-second-terme" class="level5">
<h5 class="anchored" data-anchor-id="problème-avec-le-second-terme">Problème avec le second terme</h5>
<p><span class="math display">\[\log_2 \Delta x \to -\infty \quad \text{lorsque } \Delta x \to 0\]</span></p>
<p>Donc :</p>
<p><span class="math display">\[H(X; \Delta x) \to +\infty\]</span></p>
<p><strong>Conclusion :</strong> L’entropie d’une variable continue avec la définition discrète diverge !</p>
</section>
</section>
</section>
<section id="définition-de-lentropie-différentielle" class="level3">
<h3 class="anchored" data-anchor-id="définition-de-lentropie-différentielle">Définition de l’Entropie Différentielle</h3>
<section id="définition-formelle-1" class="level4">
<h4 class="anchored" data-anchor-id="définition-formelle-1">Définition formelle</h4>
<p>Pour contourner le problème de divergence, on définit l’<strong>entropie différentielle</strong> :</p>
<p><span class="math display">\[h(X) = -\int_{\mathcal{X}} f_X(x) \log_2 f_X(x) dx\]</span></p>
<p><span class="math display">\[= -\mathbb{E}_{f_X}[\log_2 f_X(X)]\]</span></p>
</section>
<section id="notations" class="level4">
<h4 class="anchored" data-anchor-id="notations">Notations</h4>
<ul>
<li><strong>Minuscule</strong> <span class="math inline">\(h(X)\)</span> : entropie différentielle (variables continues)</li>
<li><strong>Majuscule</strong> <span class="math inline">\(H(X)\)</span> : entropie (variables discrètes)</li>
</ul>
</section>
<section id="différences-avec-lentropie-discrète" class="level4">
<h4 class="anchored" data-anchor-id="différences-avec-lentropie-discrète">Différences avec l’entropie discrète</h4>
<section id="peut-être-négative" class="level5">
<h5 class="anchored" data-anchor-id="peut-être-négative">Peut être négative</h5>
<p>Contrairement à <span class="math inline">\(H(X) \geq 0\)</span> toujours, on peut avoir :</p>
<p><span class="math display">\[h(X) &lt; 0\]</span></p>
<p><strong>Exemple :</strong> Distribution uniforme sur <span class="math inline">\([0, a]\)</span> avec <span class="math inline">\(a &lt; 1\)</span> :</p>
<p><span class="math display">\[h(X) = \log_2 a &lt; 0\]</span></p>
</section>
<section id="pas-dinterprétation-directe-en-bits" class="level5">
<h5 class="anchored" data-anchor-id="pas-dinterprétation-directe-en-bits">Pas d’interprétation directe en bits</h5>
<p>L’entropie différentielle <strong>n’a pas</strong> d’interprétation directe en termes de “nombre de bits”.</p>
<p>Elle mesure plutôt l’<strong>incertitude relative</strong> ou la <strong>dispersion</strong> de la distribution.</p>
</section>
<section id="dépend-des-unités" class="level5">
<h5 class="anchored" data-anchor-id="dépend-des-unités">Dépend des unités</h5>
<p>Si <span class="math inline">\(X\)</span> est mesuré en mètres et <span class="math inline">\(Y = X\)</span> en centimètres (<span class="math inline">\(Y = 100X\)</span>), alors :</p>
<p><span class="math display">\[h(Y) = h(X) + \log_2 100\]</span></p>
</section>
</section>
<section id="lien-avec-lentropie-quantifiée" class="level4">
<h4 class="anchored" data-anchor-id="lien-avec-lentropie-quantifiée">Lien avec l’entropie quantifiée</h4>
<p><span class="math display">\[H(X; \Delta x) \approx h(X) - \log_2 \Delta x\]</span></p>
<p>Pour <span class="math inline">\(\Delta x\)</span> petit.</p>
</section>
</section>
<section id="entropie-différentielle-dune-gaussienne" class="level3">
<h3 class="anchored" data-anchor-id="entropie-différentielle-dune-gaussienne">Entropie Différentielle d’une Gaussienne</h3>
<section id="variable-gaussienne-univariée" class="level4">
<h4 class="anchored" data-anchor-id="variable-gaussienne-univariée">Variable gaussienne univariée</h4>
<section id="distribution" class="level5">
<h5 class="anchored" data-anchor-id="distribution">Distribution</h5>
<p><span class="math display">\[X \sim \mathcal{N}(\mu, \sigma^2)\]</span></p>
<p><strong>Densité de probabilité :</strong></p>
<p><span class="math display">\[f_X(x) = \frac{1}{\sqrt{2\pi\sigma^2}} \exp\left(-\frac{(x-\mu)^2}{2\sigma^2}\right)\]</span></p>
</section>
<section id="entropie-différentielle" class="level5">
<h5 class="anchored" data-anchor-id="entropie-différentielle">Entropie différentielle</h5>
<p><span class="math display">\[h(X) = \frac{1}{2} \log_2(2\pi e \sigma^2) \quad \text{[bits]}\]</span></p>
<p>ou en nats (logarithme naturel) :</p>
<p><span class="math display">\[h(X) = \frac{1}{2} \ln(2\pi e \sigma^2) \quad \text{[nats]}\]</span></p>
</section>
<section id="propriété" class="level5">
<h5 class="anchored" data-anchor-id="propriété">Propriété</h5>
<p>L’entropie différentielle d’une gaussienne <strong>ne dépend pas</strong> de la moyenne <span class="math inline">\(\mu\)</span>, seulement de la variance <span class="math inline">\(\sigma^2\)</span>.</p>
</section>
</section>
<section id="démonstration-7" class="level4">
<h4 class="anchored" data-anchor-id="démonstration-7">Démonstration</h4>
<section id="cas-centré-mu-0" class="level5">
<h5 class="anchored" data-anchor-id="cas-centré-mu-0">Cas centré (<span class="math inline">\(\mu = 0\)</span>)</h5>
<p><strong>PDF :</strong></p>
<p><span class="math display">\[f_X(x) = \frac{1}{\sqrt{2\pi\sigma^2}} \exp\left(-\frac{x^2}{2\sigma^2}\right)\]</span></p>
<p><strong>Logarithme :</strong></p>
<p><span class="math display">\[\ln f_X(x) = -\frac{1}{2} \ln(2\pi\sigma^2) - \frac{x^2}{2\sigma^2}\]</span></p>
<p><strong>Entropie différentielle (en nats) :</strong></p>
<p><span class="math display">\[h(X) = -\int_{-\infty}^{\infty} f_X(x) \ln f_X(x) dx\]</span></p>
<p><span class="math display">\[= -\int_{-\infty}^{\infty} f_X(x) \left[-\frac{x^2}{2\sigma^2} - \frac{1}{2} \ln(2\pi\sigma^2)\right] dx\]</span></p>
<p><span class="math display">\[= \int_{-\infty}^{\infty} f_X(x) \frac{x^2}{2\sigma^2} dx + \frac{1}{2} \ln(2\pi\sigma^2) \underbrace{\int_{-\infty}^{\infty} f_X(x) dx}_{= 1}\]</span></p>
</section>
<section id="calcul-de-la-première-intégrale" class="level5">
<h5 class="anchored" data-anchor-id="calcul-de-la-première-intégrale">Calcul de la première intégrale</h5>
<p><span class="math display">\[\int_{-\infty}^{\infty} f_X(x) \frac{x^2}{2\sigma^2} dx = \frac{1}{2\sigma^2} \mathbb{E}[X^2] = \frac{1}{2\sigma^2} \cdot \sigma^2 = \frac{1}{2}\]</span></p>
<p>car <span class="math inline">\(\mathbb{E}[X^2] = \text{Var}[X] = \sigma^2\)</span> (puisque <span class="math inline">\(\mathbb{E}[X] = 0\)</span>).</p>
</section>
<section id="résultat" class="level5">
<h5 class="anchored" data-anchor-id="résultat">Résultat</h5>
<p><span class="math display">\[h(X) = \frac{1}{2} + \frac{1}{2} \ln(2\pi\sigma^2) = \frac{1}{2}[1 + \ln(2\pi\sigma^2)]\]</span></p>
<p><span class="math display">\[= \frac{1}{2}[\ln e + \ln(2\pi\sigma^2)] = \frac{1}{2} \ln(2\pi e \sigma^2) \quad \text{[nats]}\]</span></p>
</section>
<section id="conversion-en-bits" class="level5">
<h5 class="anchored" data-anchor-id="conversion-en-bits">Conversion en bits</h5>
<p><span class="math display">\[h(X) = \frac{1}{2} \log_2(2\pi e \sigma^2) \quad \text{[bits]}\]</span></p>
</section>
</section>
<section id="gaussienne-multivariée" class="level4">
<h4 class="anchored" data-anchor-id="gaussienne-multivariée">Gaussienne multivariée</h4>
<p>Pour <span class="math inline">\(X \sim \mathcal{N}(\mu, \Sigma)\)</span> avec <span class="math inline">\(X \in \mathbb{R}^n\)</span> :</p>
<p><span class="math display">\[h(X) = \frac{1}{2} \log_2[(2\pi e)^n |\Sigma|]\]</span></p>
<p><span class="math display">\[= \frac{n}{2} \log_2(2\pi e) + \frac{1}{2} \log_2 |\Sigma|\]</span></p>
<p>où <span class="math inline">\(|\Sigma|\)</span> est le déterminant de la matrice de covariance.</p>
</section>
</section>
<section id="propriétés-de-lentropie-différentielle" class="level3">
<h3 class="anchored" data-anchor-id="propriétés-de-lentropie-différentielle">Propriétés de l’Entropie Différentielle</h3>
<section id="invariance-par-translation" class="level4">
<h4 class="anchored" data-anchor-id="invariance-par-translation">Invariance par translation</h4>
<section id="énoncé-1" class="level5">
<h5 class="anchored" data-anchor-id="énoncé-1">Énoncé</h5>
<p>Pour une constante <span class="math inline">\(a\)</span> (scalaire ou vecteur) :</p>
<p><span class="math display">\[h(X + a) = h(X)\]</span></p>
</section>
<section id="interprétation-3" class="level5">
<h5 class="anchored" data-anchor-id="interprétation-3">Interprétation</h5>
<p><strong>Déplacer</strong> une distribution ne change pas son entropie différentielle.</p>
<p>Seule la <strong>forme</strong> de la distribution compte, pas sa <strong>position</strong>.</p>
</section>
<section id="démonstration-8" class="level5">
<h5 class="anchored" data-anchor-id="démonstration-8">Démonstration</h5>
<p>Si <span class="math inline">\(Y = X + a\)</span> avec <span class="math inline">\(a\)</span> constant, alors :</p>
<p><span class="math display">\[f_Y(y) = f_X(y - a)\]</span></p>
<p><span class="math display">\[h(Y) = -\int f_Y(y) \log f_Y(y) dy = -\int f_X(x) \log f_X(x) dx = h(X)\]</span></p>
<p>(par changement de variable <span class="math inline">\(x = y - a\)</span>).</p>
</section>
</section>
<section id="effet-de-la-mise-à-léchelle" class="level4">
<h4 class="anchored" data-anchor-id="effet-de-la-mise-à-léchelle">Effet de la mise à l’échelle</h4>
<section id="variable-scalaire" class="level5">
<h5 class="anchored" data-anchor-id="variable-scalaire">Variable scalaire</h5>
<p>Si <span class="math inline">\(Y = aX\)</span> avec <span class="math inline">\(a\)</span> une constante non nulle :</p>
<p><span class="math display">\[h(Y) = h(aX) = h(X) + \log_2 |a|\]</span></p>
</section>
<section id="variable-vectorielle" class="level5">
<h5 class="anchored" data-anchor-id="variable-vectorielle">Variable vectorielle</h5>
<p>Si <span class="math inline">\(Y = AX\)</span> avec <span class="math inline">\(A\)</span> une matrice inversible :</p>
<p><span class="math display">\[h(Y) = h(AX) = h(X) + \log_2 |\det(A)|\]</span></p>
<p>où <span class="math inline">\(\det(A)\)</span> est le <strong>déterminant</strong> de la matrice <span class="math inline">\(A\)</span>.</p>
</section>
<section id="interprétation-4" class="level5">
<h5 class="anchored" data-anchor-id="interprétation-4">Interprétation</h5>
<ul>
<li><strong>Étirer</strong> la distribution (<span class="math inline">\(|a| &gt; 1\)</span>) <strong>augmente</strong> l’entropie différentielle</li>
<li><strong>Compresser</strong> la distribution (<span class="math inline">\(|a| &lt; 1\)</span>) <strong>diminue</strong> l’entropie différentielle</li>
</ul>
<p>Le facteur <span class="math inline">\(\log_2 |\det(A)|\)</span> représente le changement de “volume” dans l’espace.</p>
</section>
<section id="démonstration-cas-scalaire" class="level5">
<h5 class="anchored" data-anchor-id="démonstration-cas-scalaire">Démonstration (cas scalaire)</h5>
<p>Si <span class="math inline">\(Y = aX\)</span>, alors :</p>
<p><span class="math display">\[f_Y(y) = \frac{1}{|a|} f_X\left(\frac{y}{a}\right)\]</span></p>
<p><span class="math display">\[h(Y) = -\int f_Y(y) \log_2 f_Y(y) dy\]</span></p>
<p><span class="math display">\[= -\int \frac{1}{|a|} f_X\left(\frac{y}{a}\right) \log_2 \left[\frac{1}{|a|} f_X\left(\frac{y}{a}\right)\right] dy\]</span></p>
<p>Par changement de variable <span class="math inline">\(x = y/a\)</span> :</p>
<p><span class="math display">\[h(Y) = -\int f_X(x) \log_2 \left[\frac{1}{|a|} f_X(x)\right] dx\]</span></p>
<p><span class="math display">\[= -\int f_X(x) [\log_2 f_X(x) - \log_2 |a|] dx\]</span></p>
<p><span class="math display">\[= h(X) + \log_2 |a|\]</span></p>
</section>
</section>
<section id="exemple-gaussienne-et-mise-à-léchelle" class="level4">
<h4 class="anchored" data-anchor-id="exemple-gaussienne-et-mise-à-léchelle">Exemple : gaussienne et mise à l’échelle</h4>
<p>Pour <span class="math inline">\(X \sim \mathcal{N}(0, \sigma^2)\)</span> et <span class="math inline">\(Y = aX\)</span> :</p>
<p><span class="math display">\[Y \sim \mathcal{N}(0, (a\sigma)^2)\]</span></p>
<p><strong>Vérification :</strong></p>
<p><span class="math display">\[h(Y) = \frac{1}{2} \log_2(2\pi e (a\sigma)^2) = \frac{1}{2} \log_2(2\pi e \sigma^2) + \frac{1}{2} \log_2 a^2\]</span></p>
<p><span class="math display">\[= h(X) + \log_2 |a|\]</span></p>
<p>✓ Confirme la propriété.</p>
</section>
<section id="maximum-dentropie-sous-contrainte-de-variance" class="level4">
<h4 class="anchored" data-anchor-id="maximum-dentropie-sous-contrainte-de-variance">Maximum d’entropie sous contrainte de variance</h4>
<section id="théorème-1" class="level5">
<h5 class="anchored" data-anchor-id="théorème-1">Théorème</h5>
<p>Parmi toutes les distributions continues sur <span class="math inline">\(\mathbb{R}\)</span> avec variance fixée <span class="math inline">\(\sigma^2\)</span>, la <strong>gaussienne</strong> maximise l’entropie différentielle.</p>
<p><span class="math display">\[\max_{f_X : \text{Var}[X] = \sigma^2} h(X) = \frac{1}{2} \log_2(2\pi e \sigma^2)\]</span></p>
<p>atteint pour <span class="math inline">\(X \sim \mathcal{N}(\mu, \sigma^2)\)</span> (avec <span class="math inline">\(\mu\)</span> quelconque).</p>
</section>
<section id="interprétation-5" class="level5">
<h5 class="anchored" data-anchor-id="interprétation-5">Interprétation</h5>
<p>La gaussienne est la distribution de <strong>maximum d’incertitude</strong> étant donné une contrainte sur la variance.</p>
</section>
</section>
</section>
</section>
<section id="applications-en-machine-learning" class="level2">
<h2 class="anchored" data-anchor-id="applications-en-machine-learning">Applications en Machine Learning</h2>
<section id="fonctions-de-perte" class="level3">
<h3 class="anchored" data-anchor-id="fonctions-de-perte">Fonctions de Perte</h3>
<section id="cross-entropy-en-classification" class="level4">
<h4 class="anchored" data-anchor-id="cross-entropy-en-classification">Cross-Entropy en Classification</h4>
<section id="configuration-3" class="level5">
<h5 class="anchored" data-anchor-id="configuration-3">Configuration</h5>
<p><strong>Problème :</strong> Classification multi-classes avec <span class="math inline">\(C\)</span> classes.</p>
<p><strong>Pour un exemple <span class="math inline">\((x, y)\)</span> :</strong> - <span class="math inline">\(y\)</span> : vrai label (encodé en one-hot : <span class="math inline">\(y \in \{0, 1\}^C\)</span> avec <span class="math inline">\(\sum_c y_c = 1\)</span>) - <span class="math inline">\(\hat{y} = q(y|x; \theta)\)</span> : distribution prédite par le modèle</p>
</section>
<section id="fonction-de-perte" class="level5">
<h5 class="anchored" data-anchor-id="fonction-de-perte">Fonction de perte</h5>
<p><strong>Pour un exemple :</strong></p>
<p><span class="math display">\[\mathcal{L}(y, \hat{y}) = -\sum_{c=1}^{C} y_c \log \hat{y}_c = H(y, \hat{y})\]</span></p>
<p><strong>Pour un batch de <span class="math inline">\(N\)</span> exemples :</strong></p>
<p><span class="math display">\[\mathcal{L} = -\frac{1}{N} \sum_{i=1}^{N} \sum_{c=1}^{C} y_{i,c} \log \hat{y}_{i,c}\]</span></p>
</section>
<section id="cas-binaire-binary-cross-entropy" class="level5">
<h5 class="anchored" data-anchor-id="cas-binaire-binary-cross-entropy">Cas binaire (Binary Cross-Entropy)</h5>
<p>Pour <span class="math inline">\(C = 2\)</span> (ou équivalent <span class="math inline">\(y \in \{0, 1\}\)</span>) :</p>
<p><span class="math display">\[\mathcal{L}(y, \hat{y}) = -[y \log \hat{y} + (1-y) \log(1-\hat{y})]\]</span></p>
<p>où <span class="math inline">\(\hat{y} = P(y=1|x)\)</span> est la probabilité prédite.</p>
</section>
</section>
<section id="lien-avec-maximum-de-vraisemblance" class="level4">
<h4 class="anchored" data-anchor-id="lien-avec-maximum-de-vraisemblance">Lien avec Maximum de Vraisemblance</h4>
<section id="équivalence" class="level5">
<h5 class="anchored" data-anchor-id="équivalence">Équivalence</h5>
<p>Minimiser la cross-entropy est <strong>équivalent</strong> à maximiser la log-vraisemblance :</p>
<p><span class="math display">\[\min_\theta \mathcal{L} = \min_\theta H(p_{\text{data}}, p_{\theta}) \equiv \max_\theta \mathbb{E}_{(x,y) \sim p_{\text{data}}}[\log p_\theta(y|x)]\]</span></p>
</section>
<section id="justification-2" class="level5">
<h5 class="anchored" data-anchor-id="justification-2">Justification</h5>
<p>Pour un dataset <span class="math inline">\(\{(x_i, y_i)\}_{i=1}^N\)</span> :</p>
<p><strong>Vraisemblance :</strong></p>
<p><span class="math display">\[\mathcal{L}(\theta) = \prod_{i=1}^{N} p_\theta(y_i | x_i)\]</span></p>
<p><strong>Log-vraisemblance :</strong></p>
<p><span class="math display">\[\log \mathcal{L}(\theta) = \sum_{i=1}^{N} \log p_\theta(y_i | x_i)\]</span></p>
<p><strong>Minimisation de la cross-entropy empirique :</strong></p>
<p><span class="math display">\[\min_\theta \left[-\frac{1}{N} \sum_{i=1}^{N} \log p_\theta(y_i | x_i)\right] \equiv \max_\theta \frac{1}{N} \log \mathcal{L}(\theta)\]</span></p>
</section>
</section>
</section>
<section id="sélection-de-features-1" class="level3">
<h3 class="anchored" data-anchor-id="sélection-de-features-1">Sélection de Features</h3>
<section id="utilisation-de-linformation-mutuelle" class="level4">
<h4 class="anchored" data-anchor-id="utilisation-de-linformation-mutuelle">Utilisation de l’Information Mutuelle</h4>
<section id="principe-2" class="level5">
<h5 class="anchored" data-anchor-id="principe-2">Principe</h5>
<p>Pour sélectionner les features les plus informatives par rapport à un label <span class="math inline">\(Y\)</span>, on mesure :</p>
<p><span class="math display">\[I(X_i; Y)\]</span></p>
<p>pour chaque feature <span class="math inline">\(X_i\)</span>.</p>
</section>
<section id="critère" class="level5">
<h5 class="anchored" data-anchor-id="critère">Critère</h5>
<p><strong>Garder les features avec <span class="math inline">\(I(X_i; Y)\)</span> élevée.</strong></p>
<p>Les features ayant une forte information mutuelle avec le label apportent plus d’information pour la prédiction.</p>
</section>
</section>
<section id="méthodes-de-sélection" class="level4">
<h4 class="anchored" data-anchor-id="méthodes-de-sélection">Méthodes de sélection</h4>
<section id="approche-univariée" class="level5">
<h5 class="anchored" data-anchor-id="approche-univariée">Approche univariée</h5>
<p><strong>Rang par information mutuelle :</strong></p>
<ol type="1">
<li>Calculer <span class="math inline">\(I(X_i; Y)\)</span> pour chaque feature <span class="math inline">\(i = 1, \ldots, d\)</span></li>
<li>Trier les features par <span class="math inline">\(I(X_i; Y)\)</span> décroissant</li>
<li>Sélectionner les top-<span class="math inline">\(k\)</span> features</li>
</ol>
<p><strong>Avantage :</strong> Simple et rapide</p>
<p><strong>Limitation :</strong> Ignore les dépendances entre features (redondance)</p>
</section>
<section id="approche-conditionnelle" class="level5">
<h5 class="anchored" data-anchor-id="approche-conditionnelle">Approche conditionnelle</h5>
<p><strong>Maximum Relevance Minimum Redundancy (mRMR) :</strong></p>
<p>Maximiser :</p>
<p><span class="math display">\[\max_{S} \left[\frac{1}{|S|} \sum_{X_i \in S} I(X_i; Y) - \frac{1}{|S|^2} \sum_{X_i, X_j \in S} I(X_i; X_j)\right]\]</span></p>
<p><strong>Objectif :</strong> Sélectionner des features pertinentes mais peu redondantes.</p>
</section>
<section id="approche-greedy-avec-règle-de-chaîne" class="level5">
<h5 class="anchored" data-anchor-id="approche-greedy-avec-règle-de-chaîne">Approche greedy avec règle de chaîne</h5>
<p>En utilisant la règle de chaîne :</p>
<p><span class="math display">\[I(X_1, \ldots, X_k; Y) = \sum_{i=1}^{k} I(X_i; Y | X_1, \ldots, X_{i-1})\]</span></p>
<p><strong>Algorithme :</strong></p>
<ol type="1">
<li>Sélectionner <span class="math inline">\(X_1 = \arg\max_{X_i} I(X_i; Y)\)</span></li>
<li>Sélectionner <span class="math inline">\(X_2 = \arg\max_{X_i \notin \{X_1\}} I(X_i; Y | X_1)\)</span></li>
<li>Continuer jusqu’à <span class="math inline">\(k\)</span> features</li>
</ol>
</section>
</section>
</section>
<section id="régularisation-et-variational-autoencoders" class="level3">
<h3 class="anchored" data-anchor-id="régularisation-et-variational-autoencoders">Régularisation et Variational Autoencoders</h3>
<section id="variational-autoencoders-vae" class="level4">
<h4 class="anchored" data-anchor-id="variational-autoencoders-vae">Variational Autoencoders (VAE)</h4>
<section id="architecture" class="level5">
<h5 class="anchored" data-anchor-id="architecture">Architecture</h5>
<p><strong>Encodeur :</strong> <span class="math inline">\(q_\phi(z|x)\)</span> (distribution approximative du posterior)</p>
<p><strong>Décodeur :</strong> <span class="math inline">\(p_\theta(x|z)\)</span> (distribution générative)</p>
<p><strong>Prior :</strong> <span class="math inline">\(p(z)\)</span> (souvent <span class="math inline">\(\mathcal{N}(0, I)\)</span>)</p>
</section>
<section id="fonction-objectif-elbo" class="level5">
<h5 class="anchored" data-anchor-id="fonction-objectif-elbo">Fonction objectif (ELBO)</h5>
<p>L’Evidence Lower Bound (ELBO) à maximiser :</p>
<p><span class="math display">\[\mathcal{L}_{\text{ELBO}} = \mathbb{E}_{q_\phi(z|x)}[\log p_\theta(x|z)] - D_{\text{KL}}(q_\phi(z|x) \| p(z))\]</span></p>
</section>
<section id="terme-de-régularisation-kl" class="level5">
<h5 class="anchored" data-anchor-id="terme-de-régularisation-kl">Terme de régularisation KL</h5>
<p><span class="math display">\[\mathcal{L}_{\text{KL}} = D_{\text{KL}}(q_\phi(z|x) \| p(z))\]</span></p>
<p><strong>Rôle :</strong> - Force l’encodeur à produire des distributions proches du prior - Régularise l’espace latent pour qu’il soit continu et structuré - Empêche l’overfitting dans l’espace latent</p>
</section>
<section id="interprétation-6" class="level5">
<h5 class="anchored" data-anchor-id="interprétation-6">Interprétation</h5>
<p><strong>Compromis reconstruction-régularisation :</strong></p>
<p><span class="math display">\[\mathcal{L}_{\text{VAE}} = \underbrace{\text{Terme de reconstruction}}_{\text{fidélité aux données}} + \beta \cdot \underbrace{D_{\text{KL}}(q(z|x) \| p(z))}_{\text{régularisation}}\]</span></p>
<p>où <span class="math inline">\(\beta\)</span> est un hyperparamètre (souvent <span class="math inline">\(\beta = 1\)</span>).</p>
</section>
</section>
<section id="autres-applications-de-la-kl-divergence" class="level4">
<h4 class="anchored" data-anchor-id="autres-applications-de-la-kl-divergence">Autres applications de la KL divergence</h4>
<section id="distillation-de-connaissances" class="level5">
<h5 class="anchored" data-anchor-id="distillation-de-connaissances">Distillation de connaissances</h5>
<p><strong>Objectif :</strong> Transférer les connaissances d’un grand modèle (teacher) vers un petit modèle (student)</p>
<p><strong>Loss :</strong></p>
<p><span class="math display">\[\mathcal{L}_{\text{distill}} = D_{\text{KL}}(p_{\text{student}}(y|x) \| p_{\text{teacher}}(y|x))\]</span></p>
</section>
<section id="policy-gradient-en-rl" class="level5">
<h5 class="anchored" data-anchor-id="policy-gradient-en-rl">Policy Gradient en RL</h5>
<p><strong>Trust Region Policy Optimization (TRPO) :</strong></p>
<p>Contrainte : <span class="math inline">\(D_{\text{KL}}(\pi_{\text{old}} \| \pi_{\text{new}}) \leq \delta\)</span></p>
<p>Empêche les changements trop brusques de la politique.</p>
</section>
<section id="adversarial-training" class="level5">
<h5 class="anchored" data-anchor-id="adversarial-training">Adversarial Training</h5>
<p><strong>Génération adversaire :</strong></p>
<p>Minimiser : <span class="math inline">\(D_{\text{KL}}(p_{\text{model}} \| p_{\text{data}})\)</span> ou l’inverse</p>
</section>
</section>
</section>
</section>
<section id="aide-mémoire-et-synthèse" class="level2">
<h2 class="anchored" data-anchor-id="aide-mémoire-et-synthèse">Aide-Mémoire et Synthèse</h2>
<section id="formules-essentielles" class="level3">
<h3 class="anchored" data-anchor-id="formules-essentielles">Formules Essentielles</h3>
<section id="entropie" class="level4">
<h4 class="anchored" data-anchor-id="entropie">Entropie</h4>
<section id="entropie-discrète-1" class="level5">
<h5 class="anchored" data-anchor-id="entropie-discrète-1">Entropie discrète</h5>
<p><span class="math display">\[H(X) = -\sum_{x} p(x) \log_2 p(x) = \mathbb{E}[-\log_2 p(X)]\]</span></p>
</section>
<section id="entropie-jointe-1" class="level5">
<h5 class="anchored" data-anchor-id="entropie-jointe-1">Entropie jointe</h5>
<p><span class="math display">\[H(X,Y) = -\sum_{x,y} p(x,y) \log_2 p(x,y)\]</span></p>
</section>
<section id="entropie-conditionnelle-1" class="level5">
<h5 class="anchored" data-anchor-id="entropie-conditionnelle-1">Entropie conditionnelle</h5>
<p><span class="math display">\[H(X|Y) = -\sum_{x,y} p(x,y) \log_2 p(x|y) = \mathbb{E}_{p(Y)}[H(X|Y=y)]\]</span></p>
</section>
<section id="entropie-différentielle-1" class="level5">
<h5 class="anchored" data-anchor-id="entropie-différentielle-1">Entropie différentielle</h5>
<p><span class="math display">\[h(X) = -\int f_X(x) \log_2 f_X(x) dx\]</span></p>
</section>
<section id="entropie-dune-gaussienne" class="level5">
<h5 class="anchored" data-anchor-id="entropie-dune-gaussienne">Entropie d’une gaussienne</h5>
<p><span class="math display">\[h(X) = \frac{1}{2} \log_2(2\pi e \sigma^2)\]</span></p>
</section>
</section>
<section id="relations-entre-entropies" class="level4">
<h4 class="anchored" data-anchor-id="relations-entre-entropies">Relations entre Entropies</h4>
<section id="règle-de-chaîne" class="level5">
<h5 class="anchored" data-anchor-id="règle-de-chaîne">Règle de chaîne</h5>
<p><span class="math display">\[H(X,Y) = H(X) + H(Y|X) = H(Y) + H(X|Y)\]</span></p>
<p><span class="math display">\[H(X_1, \ldots, X_N) = \sum_{i=1}^{N} H(X_i | X_{i-1}, \ldots, X_1)\]</span></p>
</section>
<section id="inégalités-fondamentales" class="level5">
<h5 class="anchored" data-anchor-id="inégalités-fondamentales">Inégalités fondamentales</h5>
<p><span class="math display">\[H(X|Y) \leq H(X)\]</span> (le conditionnement réduit l’entropie)</p>
<p><span class="math display">\[H(X,Y) \leq H(X) + H(Y)\]</span> (égalité ssi <span class="math inline">\(X \perp Y\)</span>)</p>
<p><span class="math display">\[H(X) \leq \log_2 |\mathcal{X}|\]</span> (égalité ssi distribution uniforme)</p>
</section>
</section>
<section id="information-mutuelle-1" class="level4">
<h4 class="anchored" data-anchor-id="information-mutuelle-1">Information Mutuelle</h4>
<section id="définitions-équivalentes" class="level5">
<h5 class="anchored" data-anchor-id="définitions-équivalentes">Définitions équivalentes</h5>
<p><span class="math display">\[I(X;Y) = H(X) - H(X|Y)\]</span></p>
<p><span class="math display">\[I(X;Y) = H(Y) - H(Y|X)\]</span></p>
<p><span class="math display">\[I(X;Y) = H(X) + H(Y) - H(X,Y)\]</span></p>
<p><span class="math display">\[I(X;Y) = D_{\text{KL}}(p(x,y) \| p(x)p(y))\]</span></p>
</section>
<section id="information-mutuelle-conditionnelle-1" class="level5">
<h5 class="anchored" data-anchor-id="information-mutuelle-conditionnelle-1">Information mutuelle conditionnelle</h5>
<p><span class="math display">\[I(X;Y|Z) = H(X|Z) - H(X|Y,Z)\]</span></p>
</section>
<section id="règle-de-chaîne-1" class="level5">
<h5 class="anchored" data-anchor-id="règle-de-chaîne-1">Règle de chaîne</h5>
<p><span class="math display">\[I(X_1, \ldots, X_N; Y) = \sum_{i=1}^{N} I(X_i; Y | X_{i-1}, \ldots, X_1)\]</span></p>
</section>
</section>
<section id="divergences" class="level4">
<h4 class="anchored" data-anchor-id="divergences">Divergences</h4>
<section id="kl-divergence" class="level5">
<h5 class="anchored" data-anchor-id="kl-divergence">KL divergence</h5>
<p><span class="math display">\[D_{\text{KL}}(p \| q) = \sum_x p(x) \log_2 \frac{p(x)}{q(x)} = \mathbb{E}_p\left[\log \frac{p(X)}{q(X)}\right]\]</span></p>
</section>
<section id="cross-entropy" class="level5">
<h5 class="anchored" data-anchor-id="cross-entropy">Cross-entropy</h5>
<p><span class="math display">\[H(p,q) = -\sum_x p(x) \log_2 q(x) = H(p) + D_{\text{KL}}(p \| q)\]</span></p>
</section>
</section>
</section>
<section id="propriétés-clés-à-retenir" class="level3">
<h3 class="anchored" data-anchor-id="propriétés-clés-à-retenir">Propriétés Clés à Retenir</h3>
<section id="propriétés-de-lentropie" class="level4">
<h4 class="anchored" data-anchor-id="propriétés-de-lentropie">Propriétés de l’entropie</h4>
<ol type="1">
<li><strong>Non-négativité</strong> : <span class="math inline">\(H(X) \geq 0\)</span></li>
<li><strong>Règle de chaîne</strong> : <span class="math inline">\(H(X,Y) = H(X) + H(Y|X)\)</span></li>
<li><strong>Ajout de variables augmente l’entropie</strong> : <span class="math inline">\(H(X) \leq H(X,Y)\)</span></li>
<li><strong>Conditionnement réduit l’entropie</strong> : <span class="math inline">\(H(X) \geq H(X|Y)\)</span></li>
<li><strong>Maximum pour distribution uniforme</strong> : <span class="math inline">\(H(X) \leq \log |\mathcal{X}|\)</span></li>
</ol>
</section>
<section id="propriétés-de-linformation-mutuelle" class="level4">
<h4 class="anchored" data-anchor-id="propriétés-de-linformation-mutuelle">Propriétés de l’information mutuelle</h4>
<ol type="1">
<li><strong>Symétrie</strong> : <span class="math inline">\(I(X;Y) = I(Y;X)\)</span></li>
<li><strong>Non-négativité</strong> : <span class="math inline">\(I(X;Y) \geq 0\)</span></li>
<li><strong>Annulation avec indépendance</strong> : <span class="math inline">\(I(X;Y) = 0 \Leftrightarrow X \perp Y\)</span></li>
<li><strong>Auto-information</strong> : <span class="math inline">\(I(X;X) = H(X)\)</span></li>
<li><strong>Data processing inequality</strong> : <span class="math inline">\(X \to Y \to Z \Rightarrow I(X;Y) \geq I(X;Z)\)</span></li>
</ol>
</section>
<section id="propriétés-de-la-divergence-kl" class="level4">
<h4 class="anchored" data-anchor-id="propriétés-de-la-divergence-kl">Propriétés de la divergence KL</h4>
<ol type="1">
<li><strong>Non-négativité</strong> : <span class="math inline">\(D_{\text{KL}}(p \| q) \geq 0\)</span></li>
<li><strong>Asymétrie</strong> : <span class="math inline">\(D_{\text{KL}}(p \| q) \neq D_{\text{KL}}(q \| p)\)</span></li>
<li><strong>Annulation</strong> : <span class="math inline">\(D_{\text{KL}}(p \| q) = 0 \Leftrightarrow p = q\)</span></li>
<li><strong>Pas une distance</strong> : ne vérifie ni la symétrie ni l’inégalité triangulaire</li>
</ol>
</section>
<section id="propriétés-de-lentropie-différentielle-1" class="level4">
<h4 class="anchored" data-anchor-id="propriétés-de-lentropie-différentielle-1">Propriétés de l’entropie différentielle</h4>
<ol type="1">
<li><strong>Peut être négative</strong> : <span class="math inline">\(h(X)\)</span> peut être <span class="math inline">\(&lt; 0\)</span></li>
<li><strong>Invariance par translation</strong> : <span class="math inline">\(h(X+a) = h(X)\)</span></li>
<li><strong>Mise à l’échelle</strong> : <span class="math inline">\(h(aX) = h(X) + \log |a|\)</span></li>
<li><strong>Maximum pour gaussienne</strong> : sous contrainte de variance fixée</li>
</ol>
</section>
</section>
<section id="questions-types-dexamen" class="level3">
<h3 class="anchored" data-anchor-id="questions-types-dexamen">Questions Types d’Examen</h3>
<section id="questions-conceptuelles" class="level4">
<h4 class="anchored" data-anchor-id="questions-conceptuelles">Questions conceptuelles</h4>
<section id="sur-lentropie" class="level5">
<h5 class="anchored" data-anchor-id="sur-lentropie">Sur l’entropie</h5>
<ol type="1">
<li>Définir l’entropie et expliquer ses interprétations (incertitude, bits moyens, etc.)</li>
<li>Quelle distribution maximise l’entropie pour un ensemble fini de <span class="math inline">\(N\)</span> symboles ?</li>
<li>Pourquoi <span class="math inline">\(H(X|Y) \leq H(X)\)</span> ? Donner une interprétation intuitive</li>
<li>Différence entre entropie discrète et entropie différentielle</li>
<li>Que représente <span class="math inline">\(H(X,Y)\)</span> versus <span class="math inline">\(H(X) + H(Y)\)</span> ?</li>
</ol>
</section>
<section id="sur-linformation-mutuelle" class="level5">
<h5 class="anchored" data-anchor-id="sur-linformation-mutuelle">Sur l’information mutuelle</h5>
<ol type="1">
<li>Qu’est-ce que l’information mutuelle et que mesure-t-elle ?</li>
<li>Pourquoi <span class="math inline">\(I(X;Y) = 0\)</span> signifie-t-il que <span class="math inline">\(X\)</span> et <span class="math inline">\(Y\)</span> sont indépendants ?</li>
<li>Interpréter <span class="math inline">\(I(X;Y) = H(X) - H(X|Y)\)</span></li>
<li>Expliquer le principe du data processing inequality</li>
<li>Relation entre information mutuelle et divergence KL</li>
</ol>
</section>
<section id="sur-les-divergences" class="level5">
<h5 class="anchored" data-anchor-id="sur-les-divergences">Sur les divergences</h5>
<ol type="1">
<li>Définir la divergence KL et ses interprétations</li>
<li>Pourquoi la KL divergence n’est-elle pas une distance ?</li>
<li>Quelle est la différence entre <span class="math inline">\(D_{\text{KL}}(p \| q)\)</span> et <span class="math inline">\(D_{\text{KL}}(q \| p)\)</span> ?</li>
<li>Lien entre KL divergence et cross-entropy</li>
<li>Interprétation de la KL divergence en théorie du codage</li>
</ol>
</section>
</section>
<section id="questions-de-calcul" class="level4">
<h4 class="anchored" data-anchor-id="questions-de-calcul">Questions de calcul</h4>
<section id="calculs-dentropie" class="level5">
<h5 class="anchored" data-anchor-id="calculs-dentropie">Calculs d’entropie</h5>
<ol type="1">
<li>Calculer l’entropie d’une variable binaire avec <span class="math inline">\(P(X=1) = 0.3\)</span></li>
<li>Pour <span class="math inline">\(X\)</span> uniforme sur <span class="math inline">\(\{1, 2, 3, 4\}\)</span>, calculer <span class="math inline">\(H(X)\)</span></li>
<li>Soit <span class="math inline">\(X \sim \text{Bernoulli}(0.5)\)</span> et <span class="math inline">\(Y \sim \text{Bernoulli}(0.5)\)</span> indépendants. Calculer <span class="math inline">\(H(X,Y)\)</span></li>
<li>Calculer l’entropie différentielle de <span class="math inline">\(X \sim \mathcal{N}(0, 4)\)</span></li>
</ol>
</section>
<section id="calculs-dinformation-mutuelle" class="level5">
<h5 class="anchored" data-anchor-id="calculs-dinformation-mutuelle">Calculs d’information mutuelle</h5>
<ol type="1">
<li>Pour <span class="math inline">\(X\)</span> et <span class="math inline">\(Y\)</span> indépendants, que vaut <span class="math inline">\(I(X;Y)\)</span> ?</li>
<li>Si <span class="math inline">\(Y = 2X\)</span>, que vaut <span class="math inline">\(I(X;Y)\)</span> ?</li>
<li>Calculer <span class="math inline">\(I(X;Y)\)</span> pour une distribution jointe donnée</li>
</ol>
</section>
<section id="calculs-de-divergence" class="level5">
<h5 class="anchored" data-anchor-id="calculs-de-divergence">Calculs de divergence</h5>
<ol type="1">
<li>Calculer <span class="math inline">\(D_{\text{KL}}(p \| q)\)</span> pour deux distributions binaires données</li>
<li>Calculer <span class="math inline">\(H(p,q)\)</span> et vérifier <span class="math inline">\(H(p,q) = H(p) + D_{\text{KL}}(p \| q)\)</span></li>
</ol>
</section>
</section>
<section id="questions-de-démonstration" class="level4">
<h4 class="anchored" data-anchor-id="questions-de-démonstration">Questions de démonstration</h4>
<section id="démonstrations-essentielles" class="level5">
<h5 class="anchored" data-anchor-id="démonstrations-essentielles">Démonstrations essentielles</h5>
<ol type="1">
<li>Démontrer la règle de chaîne : <span class="math inline">\(H(X,Y) = H(X) + H(Y|X)\)</span></li>
<li>Montrer que <span class="math inline">\(H(X|Y) \leq H(X)\)</span> (le conditionnement réduit l’entropie)</li>
<li>Prouver que <span class="math inline">\(I(X;Y) \geq 0\)</span></li>
<li>Démontrer le data processing inequality</li>
<li>Montrer que la distribution uniforme maximise l’entropie</li>
</ol>
</section>
<section id="démonstrations-pour-variables-continues" class="level5">
<h5 class="anchored" data-anchor-id="démonstrations-pour-variables-continues">Démonstrations pour variables continues</h5>
<ol type="1">
<li>Calculer l’entropie différentielle d’une gaussienne <span class="math inline">\(\mathcal{N}(0, \sigma^2)\)</span></li>
<li>Montrer que <span class="math inline">\(h(aX) = h(X) + \log |a|\)</span></li>
<li>Prouver que <span class="math inline">\(h(X+a) = h(X)\)</span></li>
</ol>
</section>
</section>
<section id="questions-sur-le-codage" class="level4">
<h4 class="anchored" data-anchor-id="questions-sur-le-codage">Questions sur le codage</h4>
<section id="codage-de-huffman-1" class="level5">
<h5 class="anchored" data-anchor-id="codage-de-huffman-1">Codage de Huffman</h5>
<ol type="1">
<li>Appliquer l’algorithme de Huffman à une distribution donnée</li>
<li>Calculer la longueur moyenne d’un code de Huffman</li>
<li>Comparer la longueur moyenne avec l’entropie de la source</li>
</ol>
</section>
<section id="codes-préfixes-1" class="level5">
<h5 class="anchored" data-anchor-id="codes-préfixes-1">Codes préfixes</h5>
<ol type="1">
<li>Qu’est-ce qu’un code préfixe et pourquoi est-il important ?</li>
<li>Vérifier si un code donné est un code préfixe</li>
<li>Donner un exemple de code qui n’est pas préfixe et montrer le problème de décodage</li>
</ol>
</section>
<section id="compression" class="level5">
<h5 class="anchored" data-anchor-id="compression">Compression</h5>
<ol type="1">
<li>Calculer le taux de compression pour un exemple donné</li>
<li>Expliquer pourquoi <span class="math inline">\(H(X)\)</span> représente la longueur minimale moyenne</li>
<li>Différence entre compression sans perte et avec perte</li>
</ol>
</section>
</section>
<section id="questions-dapplication" class="level4">
<h4 class="anchored" data-anchor-id="questions-dapplication">Questions d’application</h4>
<section id="machine-learning" class="level5">
<h5 class="anchored" data-anchor-id="machine-learning">Machine Learning</h5>
<ol type="1">
<li>Expliquer le rôle de la cross-entropy comme fonction de perte</li>
<li>Comment utiliser l’information mutuelle pour la sélection de features ?</li>
<li>Rôle de la divergence KL dans les VAEs</li>
</ol>
</section>
<section id="théorie-de-linformation" class="level5">
<h5 class="anchored" data-anchor-id="théorie-de-linformation">Théorie de l’information</h5>
<ol type="1">
<li>Expliquer le lien entre entropie et quantité d’information</li>
<li>Interpréter la divergence KL en termes de bits supplémentaires</li>
<li>Application du data processing inequality aux réseaux de neurones</li>
</ol>
</section>
</section>
</section>
<section id="tableaux-récapitulatifs" class="level3">
<h3 class="anchored" data-anchor-id="tableaux-récapitulatifs">Tableaux Récapitulatifs</h3>
<section id="entropie-comparaison-discret-vs-continu" class="level4">
<h4 class="anchored" data-anchor-id="entropie-comparaison-discret-vs-continu">Entropie : comparaison discret vs continu</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 37%">
<col style="width: 46%">
</colgroup>
<thead>
<tr class="header">
<th>Propriété</th>
<th>Entropie discrète <span class="math inline">\(H(X)\)</span></th>
<th>Entropie différentielle <span class="math inline">\(h(X)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Notation</td>
<td><span class="math inline">\(H\)</span> (majuscule)</td>
<td><span class="math inline">\(h\)</span> (minuscule)</td>
</tr>
<tr class="even">
<td>Formule</td>
<td><span class="math inline">\(-\sum_x p(x) \log p(x)\)</span></td>
<td><span class="math inline">\(-\int f(x) \log f(x) dx\)</span></td>
</tr>
<tr class="odd">
<td>Signe</td>
<td>Toujours <span class="math inline">\(\geq 0\)</span></td>
<td>Peut être <span class="math inline">\(&lt; 0\)</span></td>
</tr>
<tr class="even">
<td>Unités</td>
<td>Bits (ou nats)</td>
<td>Pas d’unité absolue</td>
</tr>
<tr class="odd">
<td>Interprétation</td>
<td>Nombre moyen de bits</td>
<td>Incertitude relative</td>
</tr>
<tr class="even">
<td>Translation</td>
<td>N/A</td>
<td>Invariant : <span class="math inline">\(h(X+a) = h(X)\)</span></td>
</tr>
<tr class="odd">
<td>Mise à l’échelle</td>
<td>N/A</td>
<td><span class="math inline">\(h(aX) = h(X) + \log|a|\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="relations-fondamentales-1" class="level4">
<h4 class="anchored" data-anchor-id="relations-fondamentales-1">Relations fondamentales</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 25%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Relation</th>
<th>Formule</th>
<th>Interprétation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Règle de chaîne</td>
<td><span class="math inline">\(H(X,Y) = H(X) + H(Y\|X)\)</span></td>
<td>Décomposition de l’entropie jointe</td>
</tr>
<tr class="even">
<td>Info mutuelle 1</td>
<td><span class="math inline">\(I(X;Y) = H(X) - H(X\|Y)\)</span></td>
<td>Réduction d’incertitude</td>
</tr>
<tr class="odd">
<td>Info mutuelle 2</td>
<td><span class="math inline">\(I(X;Y) = H(X) + H(Y) - H(X,Y)\)</span></td>
<td>En termes d’entropies</td>
</tr>
<tr class="even">
<td>Cross-entropy</td>
<td><span class="math inline">\(H(p,q) = H(p) + D_{\text{KL}}(p \|\| q)\)</span></td>
<td>Décomposition</td>
</tr>
<tr class="odd">
<td>Conditionnement</td>
<td><span class="math inline">\(H(X) \geq H(X\|Y)\)</span></td>
<td>Conditionnement réduit l’entropie</td>
</tr>
</tbody>
</table>
</section>
<section id="inégalités-importantes" class="level4">
<h4 class="anchored" data-anchor-id="inégalités-importantes">Inégalités importantes</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 44%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Inégalité</th>
<th>Condition d’égalité</th>
<th>Signification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(H(X) \geq 0\)</span></td>
<td><span class="math inline">\(X\)</span> déterministe</td>
<td>Non-négativité</td>
</tr>
<tr class="even">
<td><span class="math inline">\(H(X\|Y) \leq H(X)\)</span></td>
<td><span class="math inline">\(X \perp Y\)</span></td>
<td>Conditionnement réduit</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(H(X,Y) \leq H(X) + H(Y)\)</span></td>
<td><span class="math inline">\(X \perp Y\)</span></td>
<td>Sous-additivité</td>
</tr>
<tr class="even">
<td><span class="math inline">\(I(X;Y) \geq 0\)</span></td>
<td><span class="math inline">\(X \perp Y\)</span></td>
<td>Non-négativité</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(D_{\text{KL}}(p \|\| q) \geq 0\)</span></td>
<td><span class="math inline">\(p = q\)</span></td>
<td>Inégalité de Gibbs</td>
</tr>
<tr class="even">
<td><span class="math inline">\(I(X;Y) \geq I(X;Z)\)</span> pour <span class="math inline">\(X \to Y \to Z\)</span></td>
<td><span class="math inline">\(X \leftrightarrow Y \leftrightarrow Z\)</span></td>
<td>Data processing</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="cas-particuliers-importants" class="level3">
<h3 class="anchored" data-anchor-id="cas-particuliers-importants">Cas Particuliers Importants</h3>
<section id="variables-binaires" class="level4">
<h4 class="anchored" data-anchor-id="variables-binaires">Variables binaires</h4>
<p><strong>Variable de Bernoulli</strong> : <span class="math inline">\(X \in \{0,1\}\)</span> avec <span class="math inline">\(P(X=1) = \theta\)</span></p>
<p><span class="math display">\[H(X) = H(\theta) = -\theta \log \theta - (1-\theta) \log(1-\theta)\]</span></p>
<ul>
<li>Maximum en <span class="math inline">\(\theta = 0.5\)</span> : <span class="math inline">\(H(0.5) = 1\)</span> bit</li>
<li><span class="math inline">\(H(0) = H(1) = 0\)</span></li>
<li>Symétrie : <span class="math inline">\(H(\theta) = H(1-\theta)\)</span></li>
</ul>
</section>
<section id="variables-gaussiennes" class="level4">
<h4 class="anchored" data-anchor-id="variables-gaussiennes">Variables gaussiennes</h4>
<p><strong>Gaussienne univariée</strong> : <span class="math inline">\(X \sim \mathcal{N}(\mu, \sigma^2)\)</span></p>
<p><span class="math display">\[h(X) = \frac{1}{2} \log_2(2\pi e \sigma^2)\]</span></p>
<ul>
<li>Ne dépend pas de <span class="math inline">\(\mu\)</span></li>
<li>Augmente avec <span class="math inline">\(\sigma\)</span> (plus de dispersion = plus d’entropie)</li>
</ul>
<p><strong>Gaussienne multivariée</strong> : <span class="math inline">\(X \sim \mathcal{N}(\mu, \Sigma)\)</span> avec <span class="math inline">\(X \in \mathbb{R}^n\)</span></p>
<p><span class="math display">\[h(X) = \frac{n}{2} \log_2(2\pi e) + \frac{1}{2} \log_2 |\Sigma|\]</span></p>
</section>
<section id="variables-indépendantes-1" class="level4">
<h4 class="anchored" data-anchor-id="variables-indépendantes-1">Variables indépendantes</h4>
<p>Si <span class="math inline">\(X \perp Y\)</span> :</p>
<ul>
<li><span class="math inline">\(H(X,Y) = H(X) + H(Y)\)</span></li>
<li><span class="math inline">\(H(X|Y) = H(X)\)</span> et <span class="math inline">\(H(Y|X) = H(Y)\)</span></li>
<li><span class="math inline">\(I(X;Y) = 0\)</span></li>
<li><span class="math inline">\(p(x,y) = p(x)p(y)\)</span></li>
</ul>
</section>
</section>
<section id="conseils-pour-lexamen" class="level3">
<h3 class="anchored" data-anchor-id="conseils-pour-lexamen">Conseils pour l’Examen</h3>
<section id="stratégies-de-résolution" class="level4">
<h4 class="anchored" data-anchor-id="stratégies-de-résolution">Stratégies de résolution</h4>
<section id="pour-les-calculs-dentropie" class="level5">
<h5 class="anchored" data-anchor-id="pour-les-calculs-dentropie">Pour les calculs d’entropie</h5>
<ol type="1">
<li><strong>Identifier le type</strong> : discrète ou continue ?</li>
<li><strong>Vérifier</strong> : <span class="math inline">\(\sum p_i = 1\)</span> ou <span class="math inline">\(\int f(x)dx = 1\)</span></li>
<li><strong>Appliquer la formule</strong> : <span class="math inline">\(H(X) = -\sum p_i \log p_i\)</span></li>
<li><strong>Unités</strong> : préciser bits ou nats selon la base du log</li>
</ol>
</section>
<section id="pour-les-preuves" class="level5">
<h5 class="anchored" data-anchor-id="pour-les-preuves">Pour les preuves</h5>
<ol type="1">
<li><strong>Commencer par les définitions</strong> formelles</li>
<li><strong>Utiliser les propriétés</strong> connues (règle de chaîne, etc.)</li>
<li><strong>Manipulations algébriques</strong> : <span class="math inline">\(\log(a/b) = \log a - \log b\)</span></li>
<li><strong>Inégalités</strong> : Jensen, Gibbs, etc.</li>
</ol>
</section>
<section id="pour-le-codage-de-huffman" class="level5">
<h5 class="anchored" data-anchor-id="pour-le-codage-de-huffman">Pour le codage de Huffman</h5>
<ol type="1">
<li><strong>Ordonner</strong> les symboles par probabilité décroissante</li>
<li><strong>Fusionner</strong> itérativement les deux plus petits</li>
<li><strong>Assigner</strong> 0 et 1 aux branches</li>
<li><strong>Lire</strong> les codes de la racine aux feuilles</li>
<li><strong>Calculer</strong> <span class="math inline">\(\ell_{av} = \sum p_i \ell_i\)</span></li>
</ol>
</section>
</section>
<section id="erreurs-communes-à-éviter" class="level4">
<h4 class="anchored" data-anchor-id="erreurs-communes-à-éviter">Erreurs communes à éviter</h4>
<ol type="1">
<li><strong>Confondre</strong> <span class="math inline">\(H(X|Y)\)</span> et <span class="math inline">\(H(Y|X)\)</span> (pas symétriques !)</li>
<li><strong>Oublier</strong> que <span class="math inline">\(I(X;Y) = I(Y;X)\)</span> (symétrique)</li>
<li><strong>Penser</strong> que <span class="math inline">\(D_{\text{KL}}(p||q) = D_{\text{KL}}(q||p)\)</span> (faux !)</li>
<li><strong>Croire</strong> que l’entropie différentielle est toujours positive (faux)</li>
<li><strong>Confondre</strong> <span class="math inline">\(H(p,q)\)</span> et <span class="math inline">\(D_{\text{KL}}(p||q)\)</span></li>
<li><strong>Oublier</strong> la convention <span class="math inline">\(0 \log 0 = 0\)</span></li>
</ol>
</section>
<section id="vérifications-rapides" class="level4">
<h4 class="anchored" data-anchor-id="vérifications-rapides">Vérifications rapides</h4>
<ul>
<li><strong>Somme de probabilités</strong> : toujours vérifier <span class="math inline">\(\sum p_i = 1\)</span></li>
<li><strong>Non-négativité</strong> : <span class="math inline">\(H(X) \geq 0\)</span>, <span class="math inline">\(I(X;Y) \geq 0\)</span>, <span class="math inline">\(D_{\text{KL}} \geq 0\)</span></li>
<li><strong>Bornes</strong> : <span class="math inline">\(H(X) \leq \log |\mathcal{X}|\)</span></li>
<li><strong>Cohérence</strong> : si <span class="math inline">\(X \perp Y\)</span>, alors <span class="math inline">\(I(X;Y) = 0\)</span></li>
<li><strong>Unités</strong> : toujours préciser bits ou nats</li>
</ul>
</section>
</section>
<section id="ressources-et-approfondissements" class="level3">
<h3 class="anchored" data-anchor-id="ressources-et-approfondissements">Ressources et Approfondissements</h3>
<section id="concepts-à-maîtriser-absolument" class="level4">
<h4 class="anchored" data-anchor-id="concepts-à-maîtriser-absolument">Concepts à maîtriser absolument</h4>
<ol type="1">
<li><strong>Entropie</strong> : définition, interprétations, propriétés</li>
<li><strong>Règle de chaîne</strong> : pour probabilités et entropies</li>
<li><strong>Information mutuelle</strong> : définitions multiples, lien avec entropie</li>
<li><strong>Divergence KL</strong> : définition, asymétrie, interprétations</li>
<li><strong>Codage de Huffman</strong> : algorithme, optimalité</li>
<li><strong>Data processing inequality</strong> : énoncé et conséquences</li>
</ol>
</section>
<section id="pour-aller-plus-loin" class="level4">
<h4 class="anchored" data-anchor-id="pour-aller-plus-loin">Pour aller plus loin</h4>
<section id="sujets-avancés" class="level5">
<h5 class="anchored" data-anchor-id="sujets-avancés">Sujets avancés</h5>
<ul>
<li><strong>Capacité de canal</strong> (théorème de Shannon-Hartley)</li>
<li><strong>Théorie rate-distortion</strong> pour la compression avec perte</li>
<li><strong>Entropie conditionnelle maximale</strong> (MaxEnt)</li>
<li><strong>Information mutuelle normalisée</strong></li>
<li><strong>Divergences de Rényi et Tsallis</strong></li>
<li><strong>Information de Fisher</strong></li>
</ul>
</section>
<section id="applications-modernes" class="level5">
<h5 class="anchored" data-anchor-id="applications-modernes">Applications modernes</h5>
<ul>
<li><strong>Deep learning</strong> : information bottleneck theory</li>
<li><strong>Causal inference</strong> : conditional independence testing</li>
<li><strong>Neurosciences</strong> : quantification de l’information neuronale</li>
<li><strong>Économie</strong> : théorie de l’information économique</li>
<li><strong>Génomique</strong> : mesure de l’information génétique</li>
</ul>


</section>
</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>